### ISSUE TITLE
Unmet expectations on mocks should cause test to fail, rather than error

### ISSUE THREAD

**Issue by philomory** [seattlerb/minitest#209]
An unmet expectation is a way in which tests can fail; Mock#verify is effectively assert_expectations_met, so I'd expect it to report as such, rather than being reported as an exception.

**Comment by utilum** [comment]
@zenspider @philomory This still on? Awaiting pr?

**Comment by zenspider** [comment]
I've pushed a simple change to add `assert_mock`. I don't know if that addresses this issue tho.

**Comment by zenspider** [comment]
https://github.com/seattlerb/minitest/commit/110548c9f59ad46dbe994036b7bf5d5e7da75e98

**Comment by zenspider** [comment]
No response. I'm gonna assume this is handled. Closing.
