### ISSUE TITLE
this_test_sucks_and_is_order_dependent

### ISSUE THREAD

**Issue by geeksam** [seattlerb/minitest#366]
So... @zenspider just regaled me with a highly entertaining story about trying to finding two tests in a large test suite that were order-dependent, and then working out whether or not his approach could be generalized into an arbitrary "which tests are order-dependent?" finder.  My intuition is that that's probably an NP problem, but it *could* be possible to give MiniTest a hint that only *some* of the tests in a test suite are known to be order-dependent.  I suggested a ```.this_test_sucks_and_is_order_dependent``` macro that could flag either specific tests, or entire test cases, as being problematic.  I mostly use everything *but* minitest at work, so I'm not going to advocate strongly for this, but thought I'd at least capture the idea for later digestion and/or amusement.  :)

**Comment by zenspider** [comment]
I'm going to close this. It can be solved by simply documenting your tests well.
