### ISSUE TITLE
Impossible to stub out a method that yields a block

### ISSUE THREAD

**Issue by judofyr** [seattlerb/minitest#414]
I want to stub out this method:

```ruby
Mail.deliver do
  to "…"
  reply_to "…"
end
```

This doesn't work as expected:

```ruby
Mail.stub(:deliver, nil) do
  code_that_calls_mail_deliver
end
```

This will *always* invoke the block: https://github.com/seattlerb/minitest/commit/76d57a06b1c81a6bd9cca5772afa080eeda66d26#diff-00a18d559ad9a1e984068e38e5009047R208

**Comment by zenspider** [comment]
I think this is closable. Reopen if you feel otherwise.
