### ISSUE TITLE
Minitest version 5.3.4 - lot of tests failing

### ISSUE THREAD

**Issue by clod81** [seattlerb/minitest#431]
Hi,
I have a project running under Rails 4.1.1.
I'm using minitest version 5.3.3 with all my tests passing.
When I switch to minitest 5.3.4 I have heaps of errors.
I have few subclasses of the same parent class (pure ruby, non active record or anything).
If I run the test file for the single subclass, all tests are green.
If I run all tests together, or just test:units, I have lot of failures.

**Comment by zenspider** [comment]
Sorry @tmornini. I missed this notification. Unfortunately I have almost zero experience with celluloid. 

https://github.com/celluloid/celluloid/wiki/Gotchas seems to hint that there are thread local vars that can get confusing at times. You wouldn't happen to be using minitest/spec, would you?

Hrm, it also hints that you're gonna have a bad time with mutexes, which minitest uses. If you can get away with it (I don't know what your stuff does, so it is up for grabs), you might want to try using something like `Celluloid.exclusive(&block)` on a per-test basis. I'm afraid that might negate any benefit you get from `parallelize_me!`, other than stricter test independence enforcement (which is all _I_ care about wrt parallelization, but I'm not you).

**Comment by tmornini** [comment]
@zenspider As it turns out, I *am* using minitest/spec :-)

I'll take a look at `Celluloid.exclusive(&block)`, all I do care about is stricter test independence.

**Comment by clod81** [comment]
@zenspider sorry I just went back to work since 3 days. I will try to keep posted on the status of this

**Comment by zenspider** [comment]
> On Feb 11, 2015, at 19:30, Claudio Contin <notifications@github.com> wrote:
> 
> @zenspider sorry I just went back to work since 3 days. I will try to keep posted on the status of this

No worries. I'm in no rush if you aren't.

**Comment by clod81** [comment]
@zenspider good one :)

anyway, my team mate finally had a good chance to dig into it, it turned out it had something to do with timezones, something was set global in one of the test... :-1:  old legacy test, took a while, but we finally have our tests working on latest version. 
Thanks

**Comment by zenspider** [comment]
I would have liked to have seen what minitest-bisect would have pointed out. I'm glad you got your problem fixed.

**Comment by zenspider** [comment]
@tmornini (and others) if you are having any other problems, open a new ticket so it can be tracked independently.

**Comment by tmornini** [comment]
@zenspider All good here. Thanks!
