### ISSUE TITLE
Mock#expect with block raising Exception does not verify properly

### ISSUE THREAD

**Issue by corecode** [seattlerb/minitest#440]
When a mocking a method that will raise an Exception, the expectation is not recorded as satisfied.  The goal of this test is to test error handling behavior.

In [mock.rb](https://github.com/seattlerb/minitest/blob/80041efe8198082ce257485844bfb076d067310b/lib/minitest/mock.rb#L134): Probably the fact should be recorded before calling the block, rather than after.

```ruby
require 'minitest/autorun'

class TestExpectRaise < Minitest::Unit::TestCase
  def test_expect_raise
    m = Minitest::Mock.new
    m.expect(:raiser, nil) do |args|
      raise RuntimeError, "this code path triggers an exception"
    end

    assert_raises RuntimeError do
      m.raiser
    end
    m.verify		# fails, but shouldn't
  end
end
```

**Comment by zenspider** [comment]
I am betting thta @kytrinyx and I both fall into the solid "stateist tdd" camp and don't understand your mindset. I certainly don't. (that's on me, not you.)

I've got a change in place that simply moves up the recording of the call to be before invoking the block. That makes your test pass. That said, I don't see the value in your test or why you're using mocks for it. I would test like @kytrinyx did. To show another example that is closer to your sample code:

```ruby
def tested_function(some_obj, mode)
  some_obj.some_function mode
rescue RuntimeError => e
  false
end

class TestExpectRaise < Minitest::Test
  def test_exception_handling
    m = Object.new
    def m.some_function mode
      raise "this code path triggers an exception"
    end

    assert_equal false, tested_function(m, :ignored)
  end
end
```

Our versions differ only in how we're stubbing. For me my go-to tool is "def is my stub framework" and in her case she's using minitest's stub. They're functionally equivalent. Notice how in both of our cases, we're testing the result, not whether something is called (I never ever care if something is called. I care that I get the result I expect to get).
