### ISSUE TITLE
Test cases aren't marshalable when exceptions happen

### ISSUE THREAD

**Issue by tenderlove** [seattlerb/minitest#447]
Ideally test cases should be marshal-able so we can send them over the wire.  Unfortunately, [captured exceptions](https://github.com/seattlerb/minitest/blob/ab412f8693ad2e03860e8c785e55ba677cce3fa1/lib/minitest/test.rb#L210) could point at stuff that can't be marshalled.  I'm running in to this IRL while trying to make ActiveRecord's tests distributed.  We get an exception from PostgreSQL, and the exception contains a reference to the database connection, that can't be marshalled, and boom.

Here is a (probably incomplete) test case to demo the issue:

```diff
diff --git a/test/minitest/test_minitest_unit.rb b/test/minitest/test_minitest_unit.rb
index 2c40300..111bc48 100644
--- a/test/minitest/test_minitest_unit.rb
+++ b/test/minitest/test_minitest_unit.rb
@@ -691,6 +691,27 @@ class TestMinitestRunnable < Minitest::Test
 
     assert_marshal %w(@NAME @assertions @failures)
   end
+
+  class BadNews < Exception
+    attr_accessor :mutex
+  end
+
+  def test_america
+    tc = setup_marshal(Minitest::Test) do |tc|
+      def tc.whatever
+        mutex = Mutex.new
+        ex = BadNews.new "oops!"
+        ex.mutex = mutex
+        raise ex
+      end
+    end
+
+    tc.run
+    new_tc = Marshal.load(Marshal.dump(tc))
+    assert_equal tc.name, new_tc.name
+    assert_equal tc.assertions, new_tc.assertions
+    assert_equal tc.failures, new_tc.failures
+  end
 end
 
 class TestMinitestTest < TestMinitestRunnable
```

My workaround is going to be to modify [marshal_dump](https://github.com/seattlerb/minitest/blob/ab412f8693ad2e03860e8c785e55ba677cce3fa1/lib/minitest.rb#L337-339) to translate un-marshalable errors in to marshalable errors.  I'll post the code for that when I finish it, but I'm not sure it's the optimal solution.

**Comment by zenspider** [comment]
Where is this?

**Comment by utilum** [comment]
@tenderlove What would an optimal solution do differently?

**Comment by zenspider** [comment]
@tenderlove ping

**Comment by zenspider** [comment]
No response. AFAIK, we marshal just fine. See `minitest-server` and friends for examples.
