### ISSUE TITLE
When used with Guard, the randomized test sequence makes it very difficult to easily isolate whether a change corrected the test.

### ISSUE THREAD

**Issue by armahillo** [seattlerb/minitest#448]
I am using Guard + Minitest + Minitest:Spec. I have a backtrace filter installed that omits all of the Rails stack trace, and only shows the app's stack trace (that would be a great native feature, btw... 99+% of the time I don't care about the rails stack).

Last night, I had 18 tests failing. Guard is running my tests. When I change a controller, Guard re-runs Mintest on the whole controller's test file (as expected) and *this is fine*. 

The problem I am having is that, since the tests run in random order (and I understand WHY they do), there is no easy way to identify which test is the one I am attempting to fix, and even with the reduced-output from that backtrace filter, it's still very tedious to scan through the failures to find the one I'm working on.

I can think of two approaches to easing this issue:
1) (This may be a Guard issue instead) Make it easier to run a single test or test file, so that I can target just one test (similar to RSpec's "--fail-fast" option, though where it would consistently always fail on the same test)

2) Clean up the output some more. We're using progress-bar, but even with that, the failure / error output of Minitest is very verbose and disorganized. I normally use RSpec for my tests, so that's the kind of output I'm used to -- the line breaks, coloring, and text alignments all make it much more easily to quickly identify (a) the test name and (b) the failure message.

**Comment by zenspider** [comment]
Is this addressed well enough?

**Comment by zenspider** [comment]
No response. Closing.
