### ISSUE TITLE
Missing assertions accessors

### ISSUE THREAD

**Issue by byrnejb** [seattlerb/minitest#450]
As requested here is the bug report.

In our case we are moving a non-Rails ActiveRecord based CLI application from AR-4.0 to AR-4.1 and our previously passing Cucumber/Aruba features are failing because of this error: 

      undefined method `assertions' for #<String:0x00000003ba4688> (NoMethodError)
      /home/byrnejb/Projects/Software/theHeart/code/hll_th_cadex_xfer/libexec/bundler/ruby/2.1.0/gems/rspec-expectations-3.0.3/lib/rspec/matchers.rb:902:in `method_missing'
      /home/byrnejb/Projects/Software/theHeart/code/hll_th_cadex_xfer/libexec/bundler/ruby/2.1.0/gems/minitest-5.4.0/lib/minitest/assertions.rb:126:in `assert'
      /usr/lib64/ruby/2.1.0/test/unit/assertions.rb:36:in `assert'
      /home/byrnejb/Projects/Software/theHeart/code/hll_th_cadex_xfer/features/step_definitions/hll_dbms_steps.rb:15:in `find_table_model_for'

The Cucumber step definition that fails is calling this method defined in the Cucumber World class:

    def find_table_model_for( tname )
      tname = tname.gsub(/ +/,"_").singularize.camelcase
      expected = true
      actual = defined?( tname )
      message = "Expected #{tname} model class but it is not defined"
      assert( ( expected == actual ), message )
    end

Minitest 5.1 requires an assertions attribute that is not provided anywhere in the ActiveSupport testing stack and thus must be defined elsewhere on a project by project basis.  Consequently our first response to this was to simply lock the minitest gem to 4.0.

Howerver, ActiveRecord-4.1 has a dependency on ActiveSupport-4.1 which in turn has a dependency on Minitest 5.1.  

  In Gemfile:
    minitest (~> 4.0) ruby

    hll_th_cadex_xfer (>= 0) ruby depends on
      activerecord (>= 0) ruby depends on
        activesupport (= 4.1.4) ruby depends on
          minitest (5.1.0)

So we are compelled to deal with the minitest 5.1 assertions accessor issue. We have worked around this at the moment by including this method in a file located in our cucumber/aruba `features/support/` directory:

    require 'minitest/autorun'
    require 'test/unit/assertions'
    World( Test::Unit::Assertions )
        require 'minitest'
        module Minitest
          attr_accessor :assertions
        end

I am not sure whether this should be a minitest issue or an aruba issue -- since the blow up occurs in an rspec gem that aruba pulls in.  In either case it is annoying to have an ORM gem depend upon a specific version of a test library since Minitest 4 does not have this problem.  That dependency issue is of course a Rails problem and not yours.

However, if I might make so bold as to ask: if such an accessor is critical to the use of minitest why is it not simply provided for in the gem itself?  What is the benefit of requiring the end user to define over and over again what appears to be a standard ruby attr_accessor( :assertions) method?

**Comment by zenspider** [comment]
I think this is dead. Closing. Please reopen if you feel otherwise.
