### ISSUE TITLE
Where should custom assertions be defined?

### ISSUE THREAD

**Issue by singpolyma** [seattlerb/minitest#462]
I want to define a custom assertion helper for the tests in one of my files (basically, I have a describe block I'm generating in a loop and when dealing with hash data I want to do must_equal and when dealing with array data I want to do must_equal for each member of the array).  I can do this easily as follows:

    [:object, :array].each do |k|
         describe "#{k} data" do
            let(:data) { public_send(k) }
            define_method(:all_equal) { |a, b|
               if k == :array
                  a.each { |x| x.must_equal(b) }
               else
                  a.must_equal(b)
               end
            }
            it 'should filter out everything by default' do
               all_equal (... my library call ...), {a: :b}
            end
         end
    end

However this results in every test failure being reported as the line inside the `define_method` instead of the line in my actual test.  I tried moving it to a class at the top of my test file, and the same thing happened.  Any insight into a better way to handle this?

**Comment by zenspider** [comment]
Where is this?

**Comment by zenspider** [comment]
No response. Closing.
