### ISSUE TITLE
parrallel.rb:9 times - no block given

### ISSUE THREAD

**Issue by DanRathbun** [seattlerb/minitest#464]
OK I get a enumerator error under 1.8.6-p287:
**".../lib/minitest/parallel.rb:9:in `times': no block given>**
using:
```ruby
@pool = size.times.map {
```
should use a Range (for older Ruby,):
```ruby
@pool = (1..size).map {
```

The readme says 1.8 is supported. We need to test under 1.8.6-p287, for older app versions that run this interpreter.

**Comment by zenspider** [comment]
I don't feel that this is a valid issue with minitest. While you don't have control over what version of ruby you use, you do control what version of minitest you use.

Closing.
