### ISSUE TITLE
Issue when testing fork method

### ISSUE THREAD

**Issue by arthurnn** [seattlerb/minitest#467]
Script bellow passes on minitest 4.7.5, but fails on 5.3.3
```ruby
class BugTest < MiniTest::Unit::TestCase
  def test_forking
    pid = fork { p("HI") }
    Process.waitpid(pid)
    assert $?.success?
  end
end
```

On minitest5 the forked process exit 1, for some unknown reason.
Am I missing something?  or is this an actual bug ?

**Comment by ddarbyson** [comment]
Same issue here... using `Kernel.exit!` inside the fork doesn't work and Minitest still shows non 0 exit status for `$?.success?` after `waitpid` is called.

```ruby
class BugTest < MiniTest::Unit::TestCase
  def test_forking
    pid = fork { p("HI"); Kernel.exit! }

    $?.success? # => true
    assert $?.success? # => minitest pass

    Process.waitpid(pid)

    $?.success? # => false
    assert $?.success? # => minitest fails

  end
end
```

any idea's how to get around this in the short-term?

**Comment by ddarbyson** [comment]
After several months I found myself back to this same issue. Can't seem to get around the forked process always returning exitstatus of `1` even with @zenspider suggestions.

**Comment by arthurnn** [comment]
To get around this, what I did was:
```ruby
fork do
 # some code here
 Process.exit!(true)
end
```

**Comment by ddarbyson** [comment]
@arthurnn I came to the same solution with `Process.exit!(0)`. I'll close this ticket now.
