### ISSUE TITLE
Debugging string encoding mismatches is hard

### ISSUE THREAD

**Issue by rkday** [seattlerb/minitest#476]
I spent a while this evening debugging an issue that boiled down to trying to compare a UTF-8 string to an ASCII string. Minimal testcase (ruby 2.0.0p353, minitest 5.4.0):

`"\x00\xac".must_equal "\x00\xac".force_encoding("ASCII-8BIT")`

results in:

```
Expected: "\x00\xAC"
  Actual: "\u0000\xAC"
```

and

`"\xac".must_equal "\xac".force_encoding("ASCII-8BIT")`

results in the even more confusing:

```
No visible difference in the String#inspect output.
You should look at the implementation of #== on String or its members.
"\xAC"
```

(I'm encountering bytes like \xAC because I'm adding tests for https://github.com/rkday/ruby-diameter, checking that the binary data generated by functions is right).

I think it might be nice to print a warning at https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L163 if you're comparing two strings, the encodings don't match, and it fails. I'm happy to do this and create a pull request, if this seems like a good idea.

However, I can see that:
* it might generate unnecessary warnings for users not comparing binary data
* this isn't really minitest's problem - it's something that Ruby's == method should do (e.g. https://bugs.ruby-lang.org/issues/9111)

so I wanted to discuss it in an issue before submitting a PR.

**Comment by zenspider** [comment]
No discussion. I've rolled my own.
