### ISSUE TITLE
Rails helper with method named "diff" conficted with the assert_equal `diff`

### ISSUE THREAD

**Issue by chengguangnan** [seattlerb/minitest#483]
I noticed that in `assert_equal` would call `diff`.

```
def assert_equal exp, act, msg = nil
  msg = message(msg, "") { diff exp, act }
  assert exp == act, msg
end

def diff exp, act
  require "tempfile"

  expect = mu_pp_for_diff exp
  butwas = mu_pp_for_diff act
   ...
```

However, in an Rails 4 helper test, the diff method on *the helper* get invoked rather than the minitest one. 

```
module MyHelper

  DMP = DiffMatchPatch.new

  def diff(x, y)
    warn x
    warn y
    result = DMP.diff_main(x, y)
    DMP.diff_cleanupSemantic(result)
    result
  end

end
```

I'm not an expert in the method scope thing, maybe you know how to resolve this?

I'm using `assert` rather than `assert_equal` to pass around this issue.

**Comment by zenspider** [comment]
Yup. Your method's module is lower in the ancestry than my Assertions module, so yours will get picked up. `Assertions#diff` is published API and you're overriding it. The easiest way to resolve it is to rename it. Kinda looks like you should be folding that into an assertion anyways? `assert_diff`?

**Comment by zenspider** [comment]
Anything?

**Comment by chengguangnan** [comment]
I'm using `assert_equal` and that good for me.

**Comment by zenspider** [comment]
OK. Please close if you're good.
