### ISSUE TITLE
Apply bbatsov's Ruby Styleguide to MiniTest

### ISSUE THREAD

**Issue by hauleth** [seattlerb/minitest#484]
Most changes can be done using `rubocop -a`.

**Comment by zenspider** [comment]
I have zero interest in this. Sorry.

**Comment by sadovnik** [comment]
@zenspider still no interest? :)

**Comment by nateberkopec** [comment]
@sadovnik Ryan basically goes over everyone's contributions/PRs anyway with a fine-toothed comb (applies them as patches rather than directly hitting "merge"), so there isn't really a point I think.

**Comment by sadovnik** [comment]
@nateberkopec this issue is not about integrating Rubocop. It is about applying de facto Ruby coding style standard: https://github.com/bbatsov/ruby-style-guide.

**Comment by blowmage** [comment]
I don't think any Seattle.rb projects will be dropping Seattle-style. :laughing:

**Comment by nateberkopec** [comment]
What @blowmage said. Seattle-style (and maybe minitest?) is at least three times as old as that styleguide. This is a project that doesn't even use Bundler. 

You wouldn't rewrite Shakespeare in Millennial English would you? ;)

Styleguides are for the prevention of bikeshedding, not the creation of it. Minitest doesn't have style issues, because @zenspider commits 100% of the code.

**Comment by sadovnik** [comment]
@nateberkopec

> three times as old as that styleguide

> doesn't even use Bundler

These are just not valid arguments.

> You wouldn't rewrite Shakespeare in Millennial English would you? ;)

Have no idea how this is applicable to the subject. I don't think it is analogy.

> Styleguides are for the prevention of bikeshedding

Not only. They make programmers experience reading someone's code like their own. They save energy and time.

---

Anyway, I got the point. These guys have their own party and play by their own rules. And that's ok. This is open source after all. :)

**Comment by zenspider** [comment]
I closed this over a **year** ago and for some reason @sadovnik sought to revive it... OK...

> this issue is not about integrating Rubocop. It is about applying de facto Ruby coding style standard

i'm afraid you're misusing "de facto" ("in fact, or in effect, whether by right or not"). The "de facto" ruby coding style standard _on minitest_ is Seattle Style. It always has been, it always will be. I disagree with a lot of bbatsov's style guide and that isn't going to change... but in fact, this isn't even up for debate...

But I'm afraid you _also_ misunderstand the point of the style guide:

> Many projects have their own coding style guidelines (often derived from this guide). In the event of any conflicts, such project-specific guides take precedence for that project.

and:

> There are some areas in which there is no clear consensus in the Ruby community regarding a particular style (like string literal quoting, spacing inside hash literals, dot position in multi-line method chaining, etc.). **In such scenarios all popular styles are acknowledged and it's up to you to pick one and apply it consistently.**

It isn't intended to make the entire ruby community code by one style. That idea is dogma and I reject it.

> These guys have their own party and play by their own rules.

The style _**guide**_... Not the style _rules_.
