### ISSUE TITLE
Expand the expectation

### ISSUE THREAD

**Issue by penibelst** [seattlerb/minitest#485]
I want to extend Minitest to validate text files. The usage should be:

```ruby
require "minitest/autorun"
require "minitest/validator" # my file

describe "validate files" do
  parallelize_me!

  it "follows the foo algorithm" do
    "**/*.txt".must_validate :foo
  end

end
```

`must_validate` should 

1. Store the files in an array `files`.
2. Expand the one expectation to `files.length` expectations. Every generated expectation should be named by the original expectation and the filename.
3. Validate all files in parallel.

For 22 files the user should see something like:

```
Run options: --seed 1858

# Running:

..F...................

Finished in 0.051691s, 425.6025 runs/s, 1180.0798 assertions/s.

  1) Failure:
validate files#test_0003_follows the foo algorithm '/foo/bar.txt'


22 runs, 61 assertions, 1 failures, 0 errors, 0 skips

```

My question is: how do I expand the expectation? Is there a plugin which does something similar? Can you provide a working example?

**Comment by zenspider** [comment]
I'd define something like `generate_validates` as a class method and call that in the `describe` block. `generate_validates` takes your arg and then does a bunch of `it` or `define_method` calls (same thing, really) to make test methods to run when the tests actually start running.

By the time you get to a test, everything has been introspected and the loop over the methods has already started. Doing it beforehand makes things clean and simple.

**Comment by zenspider** [comment]
Does that make sense?

**Comment by penibelst** [comment]
@zenspider Thank you for help. I will try your proposal at weekend. If it does make sense, I’ll close the issue.

**Comment by zenspider** [comment]
anything?

**Comment by penibelst** [comment]
> anything?

No. I will reopen if I have more questions.

**Comment by penibelst** [comment]
This is what I get so far.

```ruby
# generated.rb
require "minitest/autorun"

class Generated < Minitest::Test

  define_method :test_string do
    assert_equal "a", "b"
  end

  %w(foo bar).each do |name|
    define_method "test_exist_#{name}" do
      assert_exist "#{name}.txt"
    end
  end

  private

  def assert_exist path
    assert File.exist?(path), "File “#{path}” doesn’t exist"
  end

end
```

I see 3 tests as expected.

```shell
# ruby generated.rb 
ruby generated.rb 
Run options: --seed 5803

# Running:

FFF

Finished in 0.001590s, 1887.0322 runs/s, 1887.0322 assertions/s.

  1) Failure:
Generated#test_string [generated.rb:5]:
Expected: "a"
  Actual: "b"


  2) Failure:
Generated#test_exist_foo [generated.rb:10]:
File “foo.txt” doesn’t exist


  3) Failure:
Generated#test_exist_bar [generated.rb:10]:
File “bar.txt” doesn’t exist

3 runs, 3 assertions, 3 failures, 0 errors, 0 skips
```
But I can’t figure out how to place the `define_method` in a method. This code crashes.

```ruby
require "minitest/autorun"

class Generated < Minitest::Test
  generate_validates!

  private

  def generate_validates!
    define_method :test_number do
      assert_equal 1, 2
    end
  end
end
```

```shell
# ruby generated.rb 
generated.rb:4:in `<class:Generated>': undefined method `generate_validates!' for Generated:Class (NoMethodError)
	from generated.rb:3:in `<main>'
```

**Comment by zenspider** [comment]
1. Don't wrap it in a method. There's no benefit.
2. At line 4, `self` is `Generated`, the class, so you need a class method. But it still isn't defined at that point.
3. See 1.

**Comment by penibelst** [comment]
> Don't wrap it in a method. There's no benefit.

I understand. Now I can test much smarter. Thank you.
