### ISSUE TITLE
Performance bottleneck in `Minitest::Runnable.on_signal`

### ISSUE THREAD

**Issue by tenderlove** [seattlerb/minitest#490]
@eileencodes and I are investigating performance of integration tests in Rails applications, so we're benchmarking the test runs.  We have two tests, a functional test and an integration test that both do about the same thing.  When we look at a stack profile of the runs, `Minitest::Runnable.on_signal` is the top bottleneck in both.

[Here is the test we're using](https://github.com/tenderlove/integration_performance_test/blob/c21e2ba7eea4e898b45dcf78ad25c91ecd2295db/test/controllers/benchmark_index.rb).

Here is the stackprof output:

```
==================================
  Mode: cpu(1000)
  Samples: 4442 (0.00% miss rate)
  GC: 319 (7.18%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      4123  (92.8%)        2051  (46.2%)     Minitest::Runnable.on_signal
        67   (1.5%)          67   (1.5%)     ActiveSupport::PerThreadRegistry#instance
        73   (1.6%)          61   (1.4%)     SQLite3::Database#prepare
        58   (1.3%)          58   (1.3%)     ThreadSafe::NonConcurrentCacheBackend#[]
        54   (1.2%)          54   (1.2%)     block in ActionDispatch::Journey::Formatter#non_recursive
        52   (1.2%)          46   (1.0%)     block (2 levels) in Class#class_attribute
        46   (1.0%)          46   (1.0%)     ActiveSupport::Notifications::Fanout::Subscribers::Evented#subscribed_to?
        42   (0.9%)          42   (0.9%)     Set#include?
        41   (0.9%)          41   (0.9%)     ActiveSupport::Configurable::ClassMethods#config
        97   (2.2%)          41   (0.9%)     ActiveSupport::Subscriber#start
        39   (0.9%)          39   (0.9%)     ActiveSupport::Notifications::Event#initialize
        44   (1.0%)          34   (0.8%)     ActiveSupport::HashWithIndifferentAccess#update
        43   (1.0%)          33   (0.7%)     ActionDispatch::Http::ParameterFilter::CompiledFilter.compile
        32   (0.7%)          32   (0.7%)     ActiveRecord::Base.logger
        45   (1.0%)          28   (0.6%)     ActionDispatch::Routing::RouteSet::Generator#initialize
        30   (0.7%)          27   (0.6%)     ActionDispatch::TestRequest#initialize
        33   (0.7%)          26   (0.6%)     ActiveSupport::Configurable#config
      2072  (46.6%)          24   (0.5%)     Minitest::Test#time_it
       846  (19.0%)          22   (0.5%)     ActionController::Instrumentation#process_action
        22   (0.5%)          22   (0.5%)     block (4 levels) in Class#class_attribute
        27   (0.6%)          21   (0.5%)     block in ActiveSupport::Notifications::Fanout#unsubscribe
        21   (0.5%)          21   (0.5%)     Minitest::Assertions#message
        19   (0.4%)          19   (0.4%)     ActiveSupport::InheritableOptions#initialize
        18   (0.4%)          18   (0.4%)     MonitorMixin#mon_enter
        46   (1.0%)          18   (0.4%)     ActionDispatch::Journey::Route#score
       177   (4.0%)          18   (0.4%)     ActionDispatch::Routing::RouteSet#url_for
       284   (6.4%)          18   (0.4%)     ActionController::TestCase::Behavior#build_request_uri
        22   (0.5%)          17   (0.4%)     ActionDispatch::Request#request_method
        17   (0.4%)          17   (0.4%)     block in AbstractController::Rendering#view_assigns
        16   (0.4%)          16   (0.4%)     ActionDispatch::Http::URL#raw_host_with_port
```

I have some ideas for speeding up `on_signal`, and I'll send a PR with that later.  I just wanted to file this issue so we can track it in case my ideas don't pan out.

**Comment by zenspider** [comment]
I'm guessing by now based on our other discussions that this is false and there's some issue with StackProf?

I'd like to see what a non-sampling profiler has to say.

**Comment by eileencodes** [comment]
Hey @zenspider if you wan to look at a non-sampling profiler I have profiles for the index methods. I have a flamegraph (https://github.com/SamSaffron/flamegraph), HtmlGraph (table format) from RubyProf and a CallStack graph (colored stack format) from RubyProf. Below are both integration and controller profiles.

**Index method integration tests**:
[RubyProf CallStack Printer](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_integration_callstack.html)
[RubyProf HtmlGraph Printer](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_integration_html_graph.html)
[Flamegraph](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_integration_flamegraph.html)

**Index Controller Tests**:
[RubyProf CallStack Printer](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_controller_callstack.html)
[RubyProf HtmlGraph Printer](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_controller_html_graph.html)
[Flamegraph](https://github.com/eileencodes/integration_performance_test/blob/master/graphs/including_minitest/index_controller_flamegraph.html)

**Comment by tenderlove** [comment]
@eileencodes I was debugging this with @ko1 last night, and it looks like we ran in to a bug in the profiler. Unfortunately it's specific to OS X.  :cry: 

I will file a bug in Ruby's tracker, or in the stackprof tracker.  But Minitest isn't our bottleneck.

**Comment by eileencodes** [comment]
Well that's no fun but at least we know. Is the issue with stackprof and OSX overall or stackprof/osx/miniprofiler? 

This issue can probably be closed then.
