### ISSUE TITLE
tenderlove on Minitest vs Rspec

### ISSUE THREAD

**Issue by abatko** [seattlerb/minitest#495]
This is more of an FYI than an issue...

Have you read [@tenderlove's experience with Minitest and RSpec](http://tenderlovemaking.com/2015/01/23/my-experience-with-minitest-and-rspec.html)?

The only two things he prefers in Rspec over Minitest are:

* if there is a failure, Rspec **prints how to run just that one failed test** at the bottom of the output, thereby enabling one to **easily copy and paste that line and run just the one test**.
* if you do `rspec --color`, you’ll get **colored output**. It helps me **quickly see the most important parts** of the test output, the assertion failure, and stack traces (though I highly suspect that the RSpec core team all use black backgrounds in their terminals because sometimes the colors aren’t so nice on my white terminal).

**Comment by zenspider** [comment]
Yup. I've read it. See `minitest-sprint` for the first bullet. There are plugins already available for the second one.

**Comment by billturner** [comment]
@abatko for the colored output, the minitest-rg gem is small and works well: https://github.com/blowmage/minitest-rg

**Comment by blowmage** [comment]
I can submit a PR adding minitest-rg if you want. You may consider changing it to minitest/color to closer match the rspec terminology.

**Comment by zenspider** [comment]
@blowmage assuming that was directed at me, yes please.

**Comment by kbrock** [comment]
I just stumbled across [minitest-utils](https://github.com/fnando/minitest-utils) which addresses the first bullet as well

**Comment by zenspider** [comment]
Closing.
