### ISSUE TITLE
[Question] How to stub/mock the file result of Kernel.open on a URL

### ISSUE THREAD

**Issue by kkirsche** [seattlerb/minitest#499]
I have been trying to use Minitest to test my code ([full repo][1]) but am having trouble with one method which downloads a SHA1 hash from a .txt file on a website and returns the value.

Method:
```ruby
def download_remote_sha1
  @log.info('Downloading Elasticsearch SHA1.')

  @remote_sha1 = ''
  Kernel.open(@verify_url) do |file|
    @remote_sha1 = file.read
  end

  @remote_sha1 = @remote_sha1.split(/\s\s/)[0]

  @remote_sha1
end
```
You can see that I log what is occurring to the command line, create  an object to hold my SHA1 value, open the url (e.g. [https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.deb.sha1.txt][2])

I then split the string so that I only have the SHA1 value.

The problem is that during a test, I want to stub the [`Kernel.open`][3] which uses OpenURI to open the URL. I would like to ensure that I'm not actually reaching out to download any file, but rather I'm just passing the block my own mock IO object testing just that it correctly splits stuff.

I attempted it like the block below but when `@remote_sha1 = file.read` occurs the file item is `nil`.
```ruby
@mock_file = Minitest::Mock.new
@mock_file.expect(:read, 'd377e39343e5cc277104beee349e1578dc50f7f8  elasticsearch-1.4.2.deb')

Kernel.stub :open, @mock_file do
  @downloader = ElasticsearchUpdate::Downloader.new(hash, true)
  @downloader.download_remote_sha1.must_equal 'd377e39343e5cc277104beee349e1578dc50f7f8'
end
```

Any help would be really appreciated.

  [1]: https://github.com/kkirsche/elasticsearch_update
  [2]: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.deb.sha1.txt
  [3]: http://www.ruby-doc.org/stdlib-2.1.5//libdoc/open-uri/rdoc/Kernel.html#method-c-open

**Comment by zenspider** [comment]
I honestly don't know as I _never_ mock. This looks related to #414 tho, so there's been some work in this direction but I honestly can't say how well it works. Here's how I'd test it: Remove the reference to `Kernel`, it does nothing for you except needlessly lock you down with an extra dependency. Then it is a simple matter to test:

```ruby
require "minitest/autorun"

class Downloader
  def initialize
    @verify_url = "http://example.com/woot"
  end

  def download_remote_sha1
    # @log.info('Downloading Elasticsearch SHA1.')

    @remote_sha1 = ''
    open(@verify_url) do |file| # NOTE: not Kernel.open, just open
      @remote_sha1 = file.read
    end

    @remote_sha1 = @remote_sha1.split(/\s\s/)[0]

    @remote_sha1
  end
end

class TestDownloader < Downloader
  def open url, &b
    b.call StringIO.new("d377e39  elasticsearch-1.4.2.deb")
  end
end

describe Downloader do
  it "should work" do
    @downloader = TestDownloader.new
    @downloader.download_remote_sha1.must_equal 'd377e39'
  end
end
```

I had to make minor changes to get your test code to run in isolation (removed namespacing, add dumb initialize w/ the missing ivar set, shortened strings, etc. All minor).

**Comment by kkirsche** [comment]
Thanks! That works but ultimately I found it was easier to stub it a different way thanks to some StackOverflow response. I was unaware of the fact that stub can take a third argument, which it will yield to a block (e.g. `Kernel.stub :open, result, yield_to_block do...`

Would you be open to having stubs and Mocks better documented? If so, where would be the best place in your opinion for me to add documentation of the use of Minitest Stubs and Mocks

**Comment by zenspider** [comment]
Ah, right. the block args to stub. I totally overlooked that, and I think I probably added them. :)

You do see that there is zero need for a mock here tho, right?

Yes, I'm totally open to having better doco. The readme can be enhanced, but in this particular case the rdoc itself fell down.

**Comment by zenspider** [comment]
Getting back to the zero-mock comment. Above is (still) how I would test this code. Subclass in the test file, override open, yield with a StringIO instance. For your version, I would still remove Kernel from the implementation and stub it against the instance itself. Another way to test is to define a singleton method on the downloader instance. Here are all three versions with some cleanup against your code (needless @ivars, etc):

```ruby
class Downloader
  def initialize
    @verify_url = "http://example.com/woot"
  end

  def download_remote_sha1
    # @log.info("Downloading Elasticsearch SHA1.")

    remote_sha1 = ""
    open(@verify_url) do |file| # NOTE: not Kernel.open, just open
      remote_sha1 = file.read
    end

    remote_sha1 = remote_sha1.split(/\s\s/)[0]

    remote_sha1
  end
end

if ENV["BEST"] then
  class TestDownloader < Downloader
    def open url, &b
      b.call StringIO.new "d377e39  elasticsearch-1.4.2.deb"
    end
  end

  describe Downloader do
    it "should work" do
      downloader = TestDownloader.new
      downloader.download_remote_sha1.must_equal "d377e39"
    end
  end
elsif ENV["GOOD"] then
  class TestDownloader < Downloader
    def open url
      yield StringIO.new "d377e39  elasticsearch-1.4.2.deb"
    end
  end

  describe Downloader do
    it "should work" do
      downloader = TestDownloader.new

      def downloader.read url
        yield StringIO.new "d377e39  elasticsearch-1.4.2.deb"
      end

      downloader.download_remote_sha1.must_equal "d377e39"
    end
  end
else
  describe Downloader do
    it "should work" do
      mock_file = StringIO.new "d377e39  elasticsearch-1.4.2.deb"

      downloader = Downloader.new
      downloader.stub :open, nil, mock_file do
        downloader.download_remote_sha1.must_equal "d377e39"
      end
    end
  end
end
```

All three versions pass, just run them with `BEST=1 ruby blah.rb` and `GOOD=1` for the middle one.

**Comment by kkirsche** [comment]
That makes perfect sense. I guess my only leftover question is why is the preference to use `StringIO` instead of a mock? Nonetheless, I trust your experience and will make adjustments to mine to match :+1: 

I really appreciate your time to help me with this.

**Comment by zenspider** [comment]
I guess I'll answer with a question: Why _not_ use an IO where an IO is normally used?

```ruby
# compare:
@mock_file = Minitest::Mock.new
@mock_file.expect(:read, 'd377e39  elasticsearch-1.4.2.deb')

# to:
StringIO.new "d377e39  elasticsearch-1.4.2.deb"
```
