### ISSUE TITLE
"Warning: you should require 'minitest/autorun' instead." But I did!

### ISSUE THREAD

**Issue by PaulMakepeace** [seattlerb/minitest#502]
This error is somewhat puzzling:

    $ cat > mta.rb
    require "minitest/autorun"
    $ ruby mta.rb
    Warning: you should require 'minitest/autorun' instead.
    Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
    From:
      /Users/makepeace/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/minitest/autorun.rb:15:in `<top (required)>'
      mta.rb:1:in `<main>'
    MiniTest::Unit.autorun is now Minitest.autorun. From /Users/makepeace/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/minitest/autorun.rb:19:in `<top (required)>'
    Run options: --seed 24481
    
    # Running:
    
    
    
    Finished in 0.000762s, 0.0000 runs/s, 0.0000 assertions/s.
    
    0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
    makepeace:tmp makepeace$ gem list minitest
    
    *** LOCAL GEMS ***
    
    guard-minitest (2.3.2)
    minitest (5.4.2)
    minitest-reporters (1.0.5)
    $ cat /Users/makepeace/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/minitest/autorun.rb
    # encoding: utf-8
    ######################################################################
    # This file is imported from the minitest project.
    # DO NOT make modifications in this repo. They _will_ be reverted!
    # File a patch instead and assign it to Ryan Davis.
    ######################################################################
    
    begin
      require 'rubygems'
      gem 'minitest'
    rescue Gem::LoadError
      # do nothing
    end
    
    require 'minitest/unit'
    require 'minitest/spec'
    require 'minitest/mock'
    
    MiniTest::Unit.autorun
    $

**Comment by PaulMakepeace** [comment]
This seemed to go away on a fresh `rvm install ruby-2.0.0-p247` Hmm.

**Comment by zenspider** [comment]
Did you have minitest 5 installed? Install it and retest.
