### ISSUE TITLE
feature request: show test run summary on Interrupt

### ISSUE THREAD

**Issue by riffraff** [seattlerb/minitest#503]
`Interrupt` is considered a PASSTHROUGH_EXCEPTION, which means it causes a test run to finish without any test-specific reporting other than the ruby stacktrace. 

It would be great if it could be handled so that the current test run state is reported anyway. 
This is useful in the case of e.g. a test suite running for some time then getting stuck because of network operations, I'd like to be able to CTRL+C the process but still be able to examine other errors/failures/skips. 

I _think_ this mostly makes sense for `Interrupt` but I think a case could be made for doing this for all exceptions re-raised from `capture_exceptions`.

**Comment by zenspider** [comment]
That's what siginfo does. Trigger with ^t on Systems that support siginfo (BSDs, OS X, etc)

**Comment by riffraff** [comment]
sorry I failed to explain myself, ^t allows me to see which test method is currently stuck, but doesn't let me see what happened with the other tests. I.e. what I'd want is

~~~
$ ruby tmp.rb 
Run options: --seed 52255

# Running:
.S..^C
Finished in 5s, 1 runs/s, 1 assertions/s.

 1) Error:
TestFoo#test_that_will_stall:
Interrupt: 
    tmp.rb:24:in `test_that_it_will_not_blend'

5 runs, 10 assertions, 0 failures, 1 errors, 1 skips

(here maybe the normal process killing backtrace from re-raising the exception at the top level?)
~~~

to clarify, I'm asking for a similar behaviour to what the test-unit gem currently provides.

**Comment by zenspider** [comment]
> On Feb 12, 2015, at 08:21, gabriele renzi <notifications@github.com> wrote:
> 
> sorry I failed to explain myself, ^t allows me to see which test method is currently stuck, but doesn't let me see what happened with the other tests. I.e. what I'd want is
> 
> $ ruby tmp.rb 
> Run options: --seed 52255
> 
> # Running:
> .S..^C
> Finished in 5s, 1 runs/s, 1 assertions/s.
> 
>  1) Error:
> TestFoo#test_that_will_stall:
> Interrupt: 
>     tmp.rb:24:in `test_that_it_will_not_blend'
> 
> 5 runs, 10 assertions, 0 failures, 1 errors, 1 skips
> 
> (here maybe the normal process killing backtrace from re-raising the exception at the top level?)
> 
> to clarify, I'm asking for a similar behaviour to what the test-unit gem currently provides.

Yes, it does:

https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L305-L316

**Comment by zenspider** [comment]
now that I have some coffee in me...

Wait... are you saying you JUST want the report to print and to have it quit as normal?

**Comment by zenspider** [comment]
```diff
@@ -125,7 +125,11 @@
 
     self.parallel_executor.start if parallel_executor.respond_to?(:start)
     reporter.start
-    __run reporter, options
+    begin
+      __run reporter, options
+    rescue Interrupt
+      warn "Interrupted. Exiting..."
+    end
     self.parallel_executor.shutdown
     reporter.report
```

**Comment by riffraff** [comment]
correct, that was what I was looking for thanks. 

Related to ^t it turns out I had an old version of minitest which apparently had a less informative report, sorry.

**Comment by zenspider** [comment]
submitted.

**Comment by judofyr** [comment]
This feature is a bit annoying. I have a test that is hanging somewhere, but I'm unable to get a backtrace to *where* the infinite loop is :-(

**Comment by zenspider** [comment]
Verbosity option?
