### ISSUE TITLE
Add negative filtering so tools like minitest-bisect can work better

### ISSUE THREAD

**Issue by zenspider** [seattlerb/minitest#519]
Sometimes it'd be better to exclude what we don't want to run. It'd allow all tests to be considered during randomization, but then filtering out the tests we don't want. This allows stable order runs while minitest-bisect filters out entire files.

Negative filtering should be able to do both tests by name (opposite of `--name /regexp/`) as well as entire files (which will require being able to map files to tests?).

**Comment by zenspider** [comment]
Assigning to myself so it stays on my radar, but **please** feel free to submit a pull request for this.

**Comment by utilum** [comment]
Do you see test name and file filtering triggered by a single option?

**Comment by zenspider** [comment]
Probably not. That'd probably be confusing. `--exclude` and `--exclude-file` maybe?

**Comment by utilum** [comment]
@zenspider 
- Is it cool to create an actual file to test file filtering?
- I filter by file name, but perhaps duplicates may exist and it'd be better to use a longer path?

**Comment by zenspider** [comment]
> On Sep 15, 2015, at 22:55, utilum <notifications@github.com> wrote:
> 
> @zenspider
> 
> 	• Is it cool to create an actual file to test file filtering?
> 	• I filter by file name, but perhaps duplicates may exist and it'd be better to use a longer path?

Absolutely cool to create an actual file to test file filtering. Maybe under test/fixtures or test/data or somesuch?

Mmmmmm... don't worry about duplicates for now.

**Comment by utilum** [comment]
Um... actually, there's a compatibility issue in this last PR. Better coming up.

**Comment by zenspider** [comment]
Closing. This is basically done, just not merged because of the issues in #609.
