### ISSUE TITLE
Is there any easy way to re-try failed test in ruby minitest?

### ISSUE THREAD

**Issue by leo-altiscale** [seattlerb/minitest#520]
Hi
  I have a bunch of ruby selenium tests and I am using minitest.

  my questions is 
     Is there any easy way to re-try failed test in ruby minitest? like what TestNG provides retryAnaylze for java?

Thx
Leo

**Comment by zenspider** [comment]
Can you further describe what you mean by "retry"? I can't figure out what `retryAnalyze` is supposed to be. It looks like a simple accessor that returns a class.

Do you want to re-run failures after the fact? or within the same test process? or?

If the former, take a look at minitest-autotest.

**Comment by leo-altiscale** [comment]
Hi 
  Thx for your quick reply, here is a senario which describe what I wana do

  When we run some frontend test within some network, the test can sometime fail due to network issue, in this case, the failure is NOT actually a bug but a false failure, to avoid such situation, we could wana re-try the same test several time till all the tries failed we say this test fails.

  I think what I want is once the test fail I wana re-run it right away within the same test process, cuz we are running tests parallel and don't wana mess up the re-run with other test process.

  TestNG retryAnalyze provides the things I describe above for java tests, it works as a listener, once the test failed the listener will catch it and re-run the test right away.


Thx for your answer
Leo

**Comment by leo-altiscale** [comment]
I have search online, seems several ruby gem provide such retry thing, but they either lacking sufficient documents or can not work with minitest directly

such this one, barely having any documents
https://github.com/grosser/minitest-rerun/blob/master/lib/minitest/rerun.rb

this one, looks really great, but can not work with minitest directly
https://github.com/lantins/resque-retry
:(

I am wondering if minitest provides its own re-try, I think this is kinda useful for a testing framework

Leo

**Comment by zenspider** [comment]
I don't know of any such thing for minitest. Not sure if it actually fits, to be honest. I suppose you could roll your own if you really wanted.

Personally, I'd focus on "due to network issue" and try to fix that rather than add a bandaid to a symptom.

**Comment by leo-altiscale** [comment]
Hi,
  Thx for your reply
  we are running our test on BrowserStack which is a 3rd party vendor provides envs for running tests.
 "due to network issue", we can not do anything about this issue, cuz we are running tests within someone else's network

Thx for your reply
Leo

**Comment by zenspider** [comment]
Closing
