### ISSUE TITLE
Different test names for a single test case in the test result

### ISSUE THREAD

**Issue by leo-altiscale** [seattlerb/minitest#523]
Hi 

  I have a selenium test case named - test_linux_os_section, by pass different params to the test, this test will be able to written once and run on different environments (different browser+os combinations).

  My question, if I run this test_linux_os_section on 5 different envs, in the console report I will have something below, the test case name will all be the same - test_linux_os_section, cuz the test method written once BUT can run on different envs by pass different params

   test_linux_os_section   PASS
   test_linux_os_section   PASS
   test_linux_os_section   PASS
   test_linux_os_section   PASS
   test_linux_os_section   PASS

  The 5 test case name will all be test_linux_os_section, BUT I want to distinguish the 5 tests by the different envs where they run, something like below

   test_linux_os_section-win-ff                      PASS
   test_linux_os_section-osx-chrome            PASS
   test_linux_os_section-osx-safari               PASS
   test_linux_os_section-win-8                      PASS
   test_linux_os_section-osx-ff                      PASS

  Can give me some clue how I can achieve this by using minitest.

Thx so much

**Comment by leo-altiscale** [comment]
like in minitest, how to have several artificial test names in test report in the console

**Comment by zenspider** [comment]
```ruby
envs.each do |env|
  define_method "test_linux_os_section-#{env}" do
    # ...
  end
end
```

**Comment by leo-altiscale** [comment]
Thx very much for you reply, I have just tired define_method to define a method dynamically. Here below I have another question.

I actually wana run the test in a parallel way. so basically I start several processes, each process have different set of ENV variables. each process will run the same test with different set of env vars

This is how I kick off the test in a parallel way
    Parallel.map(@browsers, :in_threads => @parallel_limit) do |browser|
            ENV['SELENIUM_BROWSER'] = browser['browser']
            ENV['SELENIUM_VERSION'] = browser['browser_version']
            ENV['BS_AUTOMATE_OS'] = browser['os']
            ENV['BS_AUTOMATE_OS_VERSION'] = browser['os_version']

            ENV['TEST_SUFFIX'] = "-#{ENV['SELENIUM_BROWSER']}-#{ENV['SELENIUM_VERSION']}-#{ENV['BS_AUTOMATE_OS']}-#{ENV['BS_AUTOMATE_OS_VERSION']}"

            #this how I start the test in the test suite - the ruby class
            IO.popen("ruby #{test_suite} --name #{test_case}") do |io|
              io.each do |line|
                puts line
              end
            end

          end

And below is how I define the test in the test suite

class AltiscalePortalAddonsTest < MiniTest::Test
  ...

  define_method "test_linux_test_multiple_test_name#{ENV['TEST_SUFFIX']}" do
    puts "testing multiple test name ...."
  end

 ...

end


So here comes my question: when I solely run the cmd - "ruby altiscale_portal_addons_test.rb --name test_linux_test_multiple_test_name " it give what I want
BUT when I run it in a parallel way as I mentioned above. it doesn't actually run the test, it gives something below

Started with run options --name test_linux_test_multiple_test_name --seed 22411


Finished in 0.00285s
0 tests, 0 assertions, 0 failures, 0 errors, 0 skips

Thx for your help, it was really helpful. looking forward to your reply at your convenience again.

Leo

**Comment by leo-altiscale** [comment]
But when I dynamically define test without the suffix as below, it actually works in the parallel way

![screen shot 2015-04-19 at 8 42 21 am](https://cloud.githubusercontent.com/assets/11167652/7220075/1e949c82-e670-11e4-8bdc-e42de5429735.png)

seems only I add some var after the dynamic defined method, it doesn't work, without the var it works fine in the parallel way.

**Comment by leo-altiscale** [comment]
Hi 
  Never mind, I think I did something wrong, it actually works in the parallel way.

Thx for your help

Leo

**Comment by zenspider** [comment]
Enjoy!
