### ISSUE TITLE
How to record all the failed tests and test throw error in minitest

### ISSUE THREAD

**Issue by leo-altiscale** [seattlerb/minitest#524]
Hi

  How to record all the failed tests and test throws error after all the test finish running in minitest

  Supposed after I run 100 tests, test_name in NameTestSuite failed, test_date in DateTestSuite throws a timeout error. after the 100 tests finish running
   I wana record the information below in some file, like failedtest.txt or failedtest.xml
     test_name in NameTestSuite & test_date in DateTestSuite
  
Thx for your time

Leo

**Comment by zenspider** [comment]
I'm not sure I understand your question. minitest is already recording and reporting such information. If you want it in a text file, redirect the run to a text file:

```
rake > failedtest.txt
```

If you want something more specialized than that, you probably need to write a custom reporter.

**Comment by zenspider** [comment]
No response. Closing.
