### ISSUE TITLE
described class

### ISSUE THREAD

**Issue by sivagollapalli** [seattlerb/minitest#526]
In rspec, we can access the described class using `described_class` method. Could we have the similar kind of method in minitest. If not then could we add it to minitest?

**Comment by teoljungberg** [comment]
That should be the same as `self.class`, if you want the `described_class` syntax you can just add this in your `test_helper`

```ruby
class Minitest::Spec
  def described_class
    self.class
  end
end
```

**Comment by teoljungberg** [comment]
Actually, I was wrong. `self.class` will be the test-class and no the implementation-class

**Comment by zenspider** [comment]
Personally, I think this style of testing is obfuscatory at best, but the value you want is in the civar named `@desc`.

**Comment by zenspider** [comment]
#Please close this if you think it has been resolved. #

**Comment by zenspider** [comment]
No response. Closing.
