### ISSUE TITLE
How to get test file path for test?

### ISSUE THREAD

**Issue by ArturT** [seattlerb/minitest#531]
I need to get path to the test file where the particular test is located.

I wrote simple MinitestPlugin with `before_setup` and `after_setup` methods. I'd like to get test file path from one of those method. I need it to write adapter for my gem knapsack
https://github.com/ArturT/knapsack/pull/16/files

short version of plugin:
```ruby
module BindTimeTrackerMinitestPlugin
  def before_setup
    super

   # here I need to get test file path for the test before this before_setup was called
    Knapsack.tracker.test_path = MinitestAdapter.test_path(self.class, self)
    Knapsack.tracker.start_timer
  end

  def after_teardown
   # or get test file path here would be useful as well
    Knapsack.tracker.stop_timer
    super
  end
end

::Minitest::Test.send(:include, BindTimeTrackerMinitestPlugin)

```

Any clue? Thanks.

**Comment by zenspider** [comment]
This is probably easier if you don't do this so late in the game. See minitest-server + minitest-autotest for a better approach to running tests in a split-up manner.

That said, your best approach with what you're trying to do is probably Object#method + Method#source_location.

**Comment by ArturT** [comment]
I can use in `before_setup` this:
```ruby
self.method(self.name).source_location.first
```
to get test file path.

Thanks for help. :)
