### ISSUE TITLE
Disable Output Colouring

### ISSUE THREAD

**Issue by redbassett** [seattlerb/minitest#537]
Is there an existing flag that minitest can be run with that will disable output colouring like rspec's `--no-color`?

I am running tests from inside the Sublime Ruby Test plugin. The plugin provides its own syntax highlighting, but this conflicts with the highlighting being provided by the tests. For rspec, the documentation recommends using the flag listed above, but I haven't been able to find the equivalent for minitest.

**Comment by zenspider** [comment]
Minitest doesn't color output unless you're intentionally using minitest/pride or some other plugin.

**Comment by redbassett** [comment]
How would I disable these plugins in specific contexts though? Is there a command-line flag to disable them?

**Comment by blowmage** [comment]
```ruby
require "minutest/pride" unless ENV["NOCOLOR"]
```

Then to disable colors call it like this:

```shell
$ NOCOLOR=1 rake test
```

**Comment by zenspider** [comment]
@blowmage Obviously typed on your ios device. You'd think by now it would figure out that "minitest" is a word we use often enough. I can't say that I've _ever_ used the word "minutest" in everyday English.

**Comment by blowmage** [comment]
Ugh, yes. Nailed it. :)

**Comment by redbassett** [comment]
I like the `NOCOLOR` env variable, however it isn't working in the context I need. I am using the Sublime Text Ruby Test plugin ([maltize/sublime-text-2-ruby-tests](https://github.com/maltize/sublime-text-2-ruby-tests)) and changing the `run_ruby_unit_command` option in its settings, but this isn't accepting a env variable. :cry: 

Relevant issue: maltize/sublime-text-2-ruby-tests#245

**Comment by zenspider** [comment]
**You** are opting in to color. So opt out.

**Comment by zenspider** [comment]
IE: You can do the exact opposite of what @blowmage suggested.

**Comment by blowmage** [comment]
```ruby
require "minitest/pride" if ENV["COLOR"]
```

**Comment by redbassett** [comment]
While this works on the command line for `rake test`, it still isn't working for the plugin, sadly.

Thanks for your help! The idea of environment variables to turn parts on or off in place of flags is good!

**Comment by zenspider** [comment]
Since this is an issue with your code + your editor/editor-plugin I'm going to close. Please reopen if you think I've overlooked something.

**Comment by redbassett** [comment]
Yeah, I meant to request that it be closed. Thanks!

**Comment by arefaslani** [comment]
use this package: https://github.com/aziz/SublimeANSI
