### ISSUE TITLE
missing closing </head> tag in docs website

### ISSUE THREAD

**Issue by tompave** [seattlerb/minitest#539]
Is it me or the `<head>` in http://docs.seattlerb.org/minitest/ is never closed?

**Comment by zenspider** [comment]
So?

**Comment by tompave** [comment]
Was just wondering if it should be fixed. Is there a public repo for the website where I can send a PR?
Or is the <head> generated automatically by DarkFish?

**Comment by zenspider** [comment]
That's all rdoc. You could file a bug/PR on rdoc/rdoc I guess.

**Comment by tompave** [comment]
I see, thanks.
