### ISSUE TITLE
Documentation request: Please show how to test the inside of a block

### ISSUE THREAD

**Issue by egeland** [seattlerb/minitest#545]
As asked in https://stackoverflow.com/questions/30090884/how-can-i-mock-with-a-block-in-minitest (and I will update that with the answer(s) given here), how can I best test a block? Here's my example:
````
class Foo
  def initialize(name)
    @sqs    = Aws::SQS::Client.new
    @id     = @sqs.create_queue( queue_name: name ).fetch(:queue_url)
    @poller = Aws::SQS::QueuePoller.new(@id)
  end
  def pick_first
    @poller.poll(idle_timeout: 60) do |message|
      process_msg(message) if some_condition(message)
    end
  end
````
How can I mock/stub/something-else so that I can feed a `message` through to be tested by the `some_condition()` and possibly processed with `process_msg()`?

I.e. I want to test the `@poller.poll(idle_timeout: 60) do |message|`.

I have tried to stub the `Aws::SQS::QueuePoller#new` with a mock `poller`, but it's not yielding the message to `|message|` just returning it..

Via twitter, @zenspider kindly suggested (thanks for that, by the way!):
````
Liskov Sub. Prin.:
class TestFoo < Foo; def process_msg m; m; end; end
…
assert_equal 42, TestFoo.new .pick_first
````
Which I understand might mean something along the lines of
"Make a derived class that yields the expected message and test that"
But clarification and (non-twitter-size-constrained) example(s) would be great to help me and my fellow n00bs understand.

Maybe I could supply the `message` by replacing `@poller#poll` with a function that will `yield` some values, somehow? Not sure how, though... Maybe through the mocking of `Aws::SQS::QueuePoller#new` ..?

**Comment by phiggins** [comment]
What about something like:

```
class Foo
  def initialize(name, opts={})
    @sqs    = Aws::SQS::Client.new
    @id     = @sqs.create_queue( queue_name: name ).fetch(:queue_url)
    @poller = opts.fetch(:poller) { Aws::SQS::QueuePoller.new(@id) }
  end
  
  def pick_first
    @poller.poll(idle_timeout: 60) do |message|
      process_msg(message) if some_condition(message)
    end
  end
end

# later, in your tests
describe Foo do
  it "does the thing in the block" do
    # could be moved into top-level TestPoller, or into shared setup, etc.
    poller = Object.new
    def poller.poll(*) ; yield ; end
    
    foo = Foo.new("lol", :poller => poller)
    foo.pick_first

    assert foo.some_state_was_updated
  end
end
```

**Comment by zenspider** [comment]
*NOTE:* I'm anti-mock. I'm almost anti-stub for that matter. IMHO, if you can't test something without mocking it, you probably have a design issue. Calibrate accordingly against the text below.

I suggested using Liskov Substitution Principal (LSP) because I was focused on testing that `process_msg` did the right thing in that context. The idea is simple, subclass, override the method in question, and use the subclass within the tests. LSP says that testing a subclass is equivalent to testing the superclass.

In the case of the polling object, you have three concerns (polling, filtering, and processing) going on in that method, one of whom you shouldn't be testing (because it is third-party code). I'd refactor to something like this:

```ruby
class Foo
  # ....

  def poll
    @poller.poll(idle_timeout: 60) do |message|
      yield message
    end
  end

  def pick_first
    poll do |message|
      process_msg(message) if some_condition(message)
    end
  end
end
```

Then testing is a simple matter:

```ruby
class TestFoo1 < Foo
  def poll
    yield 42 # or whatever
  end

  # ...
end

# ...

assert_equal 42, TestFoo1.new.pick_first # some_condition truthy
assert_nil       TestFoo2.new.pick_first # some_condition falsey
```

There are shorter/"rubyier" ways to do this, but they're equivalent to the above and the above illustrates the point better.

**Comment by egeland** [comment]
Thank you, both @phiggins and @zenspider !

I'll give these techniques a go, and will update here and on SO.
I feel these examples will be very useful for people learning how to test in ruby - thank you for taking the time to provide them!

I'm neither pro- nor anti-mock, just happy to get some good tests into my project. :)

**Comment by zenspider** [comment]
It's been a week. How's it going?

**Comment by egeland** [comment]
I've mostly gone with your way, @zenspider , I'll do a write-up as promised sometime this week.

**Comment by zenspider** [comment]
Closing...

**Comment by egeland** [comment]
I've updated the [StackOverflow question](https://stackoverflow.com/questions/30090884/how-can-i-mock-with-a-block-in-minitest) with your responses.
Sorry to take so long to get back to you - I've been working on other things..
Anyway, I really appreciate your help. Thanks again
