### ISSUE TITLE
test "some description" in Minitest::Test

### ISSUE THREAD

**Issue by wojtekmach** [seattlerb/minitest#551]
Sorry if this issue was already discussed.

I think it would be really worthwhile to introduce [1] the `test "some description"` macro by default in Minitest.

Of course the same functionality is already available in `minitest/spec` with the `it` block, but over the years I found that some aspects of "spec-style" testing are causing all sorts of trouble:
* deeply nested describe blocks
* overusing `let`s, especially overwriting them in nested blocks

and some minitest/spec specifics:
* polluting Object with must_* methods (this is alleviated with expect(x) though)
* additional complexity associated with expectations (infect_an_assertion). It's so darn convenient to just write a custom assert_* helper

I think it could be a compromise and good default behaviour to allow folks to write readable test descriptions without bringing in `minitest/spec`. (and let the other fancy stuff like `describe`, `let` etc stay there.)
ActiveSupport::TestCase could also use this `test` method instead of re-implementing it. /cc @tenderlove 

[1] well, it would be changing behavior since MT::Test.test is already a method

**Comment by zenspider** [comment]
```ruby
def test_some_description
  # ...
end

# vs:

test "some description" do
  # ...
end
```

discuss...

**Comment by wojtekmach** [comment]
nothing to discuss in the example above, clearly it doesn't matter. I'd argue it does matter in some more wordy descriptions and that's the use case I'm after:

```ruby
class CachedScoreTest < Minitest::Test
  def test_remembers_score
  end

  def test_raises_an_exception_if_the_term_isnt_cached
  end

  def test_round_trips_no_scores_to_the_database
  end
  
  # vs

  test "remembers scores" do
  end

  test "raises an exception if the term isn't cached" do
  end

  test "round-trips NoScores to the database" do
  end
end
```

(stolen from https://github.com/garybernhardt/sucks-rocks/blob/master/spec/models/cached_score_spec.rb)

**Comment by blowmage** [comment]
There are times I prefer a `test "my thing does a thing" do` syntax, but that comes up far less than I'd expect. Even in rails where this is available I rarely make use of it and prefer `def test_does_a_thing`. But if this were available in Minitest I'm sure I'd use it more.

**Comment by zenspider** [comment]
If it doesn't matter at 2 words, why does it matter at 5? Where does it flip to mattering?

**Comment by wojtekmach** [comment]
> If it doesn't matter at 2 words, why does it matter at 5? Where does it flip to mattering?

I'd argue it's not a matter of amount of words, but how readable something is. I find value in describing behaviour in proper english to read like a specification (same reason I think rubyspec was a good idea.) This stuff is obviously available in minitest/spec, but that adds complexity especially around expectations. (I'd know after minitest-matchers :P) People can of course choose not to use expectations and just use assertions, but I suppose they're encouraged to use the former. Anyway, this would add a small indirection to minitest/test which would be against it's direct approach, so yeah, definitely there are pros & cons.

**Comment by zenspider** [comment]
Given that minitest/spec and minitest/test map 1:1, I don't agree with your argument "This stuff is obviously available in minitest/spec, but that adds complexity especially around expectations". There's no requirement to use expectations and there's nothing about minitest/spec that increases complexity (other than the added "do" keyword, but that's offset by not having "test_" on the front of a method name, sorta).

I guess I just don't see much point/value in this, but I'm very biased towards what is readable and what is not. I'm a programmer. I'm paid to read code. A string versus a method name makes zero difference to me.

**Comment by wojtekmach** [comment]
I still think minitest/spec brings some complexity:
- writing custom expectations is more complex than writing custom assertions (it's not a matter of just writing infect_an_assertion but understanding how all of this stuff works)
- spec inheritance: https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L204

which I suppose you could say "if you don't need/want that complexity just use minitest/test" - which is fair.

> I guess I just don't see much point/value in this, but I'm very biased towards what is readable and what is not

I guess this is subjective, I'm biased too, so it's kinda hard to reach an agreement. Since minitest/spec already supports the "readable" version of specs then I suppose that already covers the majority of use cases for people using minitest. Thanks for your time discussing this!

**Comment by zenspider** [comment]
Or use a hybrid. I know @blowmage likes to use "assertion style specs" (did I remember that right?). Basically, describe/it, but with assertions for actual testing.

**Comment by aar0nr** [comment]
I think this is a valid feature to support, especially for ruby.

It's common practice to include the method you are testing in the test method name, e.g.

```ruby
class Foo
  def bar
  end
end

class FooTest
  def test_bar_with_some_state
  end
end
```

However, this doesn't work well when methods include special characters, i.e. ```= ? !```.

```ruby
class Foo
  def bar
  end

  def bar=(val)
  end

  def bar?
  end

  def bar!
  end
end

class FooTest
  def test_bar_with_some_state # works fine
  end
  
  def test_bar=_with_some_state # ugh
  end
  
  def test_bar?_with_some_state # ugh
  end
  
  def test_bar!_with_some_state # ugh
  end
end
```

So you have to come up with some other way to distinguish which unit of work you're testing, e.g.

```ruby
class FooTest
  def test_bar_with_some_state # works fine
  end
 
  def test_bar= # works fine, but cannot add state or expected behavior
  end

  def test_bar_writer_with_some_state
  end

  def test_bar? # works fine, but cannot add state or expected behavior
  end

  def test_bar_predicate_with_some_state
  end
  
  def test_bar! # works fine, but cannot add state or expected behavior
  end

  def test_bar_danger_with_some_state
  end
end
```

It's much nicer to write these methods using strings:

```ruby
class FooTest
  test 'bar with some state' do
  end

  test 'bar= with some state' do
  end

  test 'bar? with some state' do
  end

  test 'bar! with some state' do
  end
end
```

Most languages don't have this problem because special characters other than underscores are not permitted.

What do you think? How do you deal with methods that have identical names but are different forms, i.e. reader, writer, predicate, danger? A test method that accepts a string seems like a good way to deal with this ruby idiom.

**Comment by aar0nr** [comment]
One option is to extend the Spec::DSL and alias "it":

```ruby
class TestCase < Minitest::Test
  extend Minitest::Spec::DSL

  class << self
    alias test it
  end
end
```

```ruby
class FooTest < TestCase
  test 'the truth' do
    assert true
  end
end
```
