### ISSUE TITLE
Thoughts about changing the message interface

### ISSUE THREAD

**Issue by gmalette** [seattlerb/minitest#553]
What are your thoughts about changing the message interface to prevent errors, as described in https://github.com/rails/rails/pull/20527 from 

```ruby
assert predicate, message
```

to

```
assert predicate, message: message
```

cc @rafaelfranca @arthurnn @zenspider

**Comment by zenspider** [comment]
I think that's a backwards-incompatible change for a very very small edge case and not much improvement overall. I'm not willing to accept it into minitest and I think accepting this into rails (or anything else) is a _very bad idea_. The size of your diff is, I believe, proof of how bad an idea this is. You're asking _every_ rails app that uses minitest to change their tests.

Instead, why not scan for the case you're trying to prevent?

**Comment by zenspider** [comment]
(Quick & Dirty) example of such a scanner: https://gist.github.com/zenspider/e4251e90cd908696682d

This points out the single occurance in rails (which @tenderlove just deleted in response, btw). I assume it'll have similar impact on the codebase that stimulated this PR. There might be some noise and adjustments to be made in the two consts to reduce the noise.

I can release this as a gem.

**Comment by gmalette** [comment]
> (Quick & Dirty) example of such a scanner: https://gist.github.com/zenspider/e4251e90cd908696682d

That might just work for most cases, but it's really just :lipstick: on :pig: 

> I assume it'll have similar impact on the codebase that stimulated this PR

There are only ~4K `assert` in Rails, so comparisons aren't entirely fair. In our codebase, there was ~200 such mistakes. When I "fixed" them 70 tests failed.

> which tenderlove just deleted in response, btw

Woptidoo, maybe I should've done that. 

Feel free to close this issue, I have to admit I never expected it to be accepted.

**Comment by zenspider** [comment]
Thanks for referring to minitest as a :pig:. :stuck_out_tongue: 

Did you run my scanner on your codebase (pre-your patch)? I'd like to how how it fared against the pathological case in pointing out potential erroneous uses of assert instead of assert_equal.

What do you mean by `"fixed"`. They were using assert instead of assert_equal, and which changed to be the correct assertion, they failed, no? Did they fail because the test was bad or was there a legitimate bug in the implementation under test?

**Comment by gmalette** [comment]
> Thanks for referring to minitest as a :pig: .

Please don't get me wrong, I wasn't referring to minitest but to the `assert` API. I meant that the scanner is not solving the problem, it's just camouflaging it by, you know, adding :lipstick: 

> They were using assert instead of assert_equal, and which changed to be the correct assertion, they failed, no?

Exactly

> Did they fail because the test was bad or was there a legitimate bug in the implementation under test?

Both, mostly bad tests. I went through a few PRs I'm amazed that we didn't see more prod failures. @tjoyal had started the work before me so I don't know exactly where.

> Did you run my scanner on your codebase (pre-your patch)?

I did; it found 86 issues but I have no way to know how they intersect with the actual problems other than spelunking over a significant amount of PRs, which quite frankly I will not do.

> I can release this as a gem.

Feel free to do so, but keep in mind that it should run inline when running the tests for a single file, otherwise you're just slowing down devs.

**Comment by zenspider** [comment]
Understood. Thanks for the feedback. I think I will release the scanner as a gem. I don't think it is camouflage any more than using something like rubocop and it can help people without breaking their code.

Closing (but feel free to reopen if you think there is more dialog to be had)

**Comment by gmalette** [comment]
I'd appreciate if you let me know when you do
