### ISSUE TITLE
Stubbing Sinatra helpers in specs

### ISSUE THREAD

**Issue by seban** [seattlerb/minitest#554]
How can I stub/mock methods from included modules in `Sinatra::Base` inherited class?
```
module AppHelpers

  def authorized?
    # check some stuff
  end

end

class MyApp < Sinatra::Base

   include AppHelpers

   get "/my-route" do
      halt 401 unless authorized?
     
     status 200
     body "authorized!"
   end

end

describe MyApp do

  let(:app) { MyApp }

  describe "GET /my-route" do
    describe "when not authorized" do
       # quite easy to test
    end

    describe "when authorized" do
      before do
        # some stub on `authorized?` method here?
        get "/my-route"
      end

     it { last_response.status.must_equal 200 } 
    end
  end

end
```

**Comment by teoljungberg** [comment]
Try

```ruby
app.stub(:authorized?, true) do
  #  do the test
end
```

**Comment by seban** [comment]
@teoljungberg I get "NameError: undefined method `authorized?' for `MyApp'".

**Comment by teoljungberg** [comment]
Oh right, `authorized` is on the instance of `MyApp`, if you assign `app = MyApp.new` and then stub as suggested above. That _should_ do it

**Comment by seban** [comment]
@teoljungberg it is not so easy. 
```
      let(:app) { MyApp.new }
      before do
        app.stub(:authorized?, true) do
          get "my-route'
        end
      end

      it { last_response.status.must_equal 200 }
```
Gives output NameError: undefined method `authorized?' for class `Sinatra::Wrapper'. 
Maybe it is not issue directly for minitest but I really would like to know how to test simple sinatra app with just minitest without taking other stubing gems.

**Comment by teoljungberg** [comment]
Agreed, this lies beyond minitest itself

**Comment by bhenderson** [comment]
I'm not at a computer. But I'm pretty sure Sinatra overrides new. New
returns a middleware. Not your app instance. Look for the aliases method to
call. I forget what it is.

**Comment by mkaschenko** [comment]
@seban Could you extract a class, let's say `Authorizer` instead?

**Comment by bhenderson** [comment]
here is the line I was referring to:

https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1465

try

```ruby
let(:app){ MyApp.new! }
```

however, I strongly encourage you to actually test your authorization process if you aren't already.

**Comment by zenspider** [comment]
I'm a bit out of the loop at this stage, but does this have anything to do with minitest at this point?

**Comment by zenspider** [comment]
No response. Closing.
