### ISSUE TITLE
Minitest output too long

### ISSUE THREAD

**Issue by tquill** [seattlerb/minitest#555]
I have a Rails 4.2.2 application and I was wondering what the default output for testing should be. I don't think I've changed any defaults, but my minitest output seems way too long.

It includes a lot of SQL and also shows each test individually.

Is this normal, or did I change something by accident? I'm using the default settings for minitest-reporters. I don't think my output is supposed to be this long.

![image](https://cloud.githubusercontent.com/assets/3828141/8272971/b85ff75a-181e-11e5-9066-9ba4a737b29c.png)

**Comment by tquill** [comment]
I'm not sure why I had to add this line, but adding `config.log_level = :error` in `test.rb` fixed it. Other repos which I've cloned don't have this line and have minimal testing output... so I'm not sure if what I've done differently

**Comment by zenspider** [comment]
Seems like an issue in rails or minitest-reporters. *shrug*

**Comment by l4u** [comment]
The logs should be written to `log/test.log`. If you use `config.log_level = :error`, logs with `info` tag will not be written.
