### ISSUE TITLE
Tag the releases of this gem

### ISSUE THREAD

**Issue by mojavelinux** [seattlerb/minitest#557]
Please tag the releases of this gem in the source code. Without tags, it is very difficult to navigate to the source code of a specific release to find out what was implemented at the time.

**Comment by zenspider** [comment]
I don't develop with git, I only replicate to it. The current replication script that I use does not support tags.  The code is at https://github.com/seattlerb/synchronizer if you want to try to understand it (I barely do).

**Comment by mojavelinux** [comment]
So where is the real source code then? I don't need the tags in git (although it would be nice) as long as it's possible to see them somewhere.

**Comment by zenspider** [comment]
The source is in my perforce repo. If you'd like an account on it, you're welcome to it.

**Comment by mojavelinux** [comment]
Moving on.

**Comment by zamith** [comment]
@zenspider I'm happy to add tags and create releases for you, if you want. This is also something I would find useful.

There is a "workaround" for this, which is `git log -G 5.8.2`, I then check out to that commit, @mojavelinux. This is not as good as tags, obviously.

**Comment by zenspider** [comment]
@zamith I'm happy to work with you on this.

**Comment by zamith** [comment]
Cool. How do you want to go about it?
