### ISSUE TITLE
Unable to access Ruby Kernel methods within let block

### ISSUE THREAD

**Issue by danielpclark** [seattlerb/minitest#559]
```ruby
let(:user){
  Object.new.tap do
    public def example
      "Hello World!"
    end
  end
}
```

#### NoMethodError: undefined method `public' for #<ExampleTest:0x0000000fb91dd8>

Other than this Minitest works fine for me.  I can use this usage of Object.new elsewhere without problems.

I just tried with `def user` and have received the same error.  Tried both in a describe block and `class Example < ActiveSupport::TestCase`  Here's the test_helper.rb

```ruby
ENV['RAILS_ENV'] ||= 'test'
require 'simplecov'
SimpleCov.start 'rails'
require File.expand_path('../../config/environment', __FILE__)
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each { |f| require f }
require 'rails/test_help'
require 'minitest/rails/capybara'
#require 'minitest/debugger' if ENV["DEBUG"]
require 'capybara-webkit'
require 'minitest/autorun'
require 'pry-rescue/minitest'
Capybara.javascript_driver = :webkit
require "minitest/reporters"
require "color_pound_spec_reporter"
Minitest::Reporters.use!(
  ColorPoundSpecReporter.new,
  ENV,
  Minitest.backtrace_filter
)     
class ActionController::TestCase
  include Devise::TestHelpers
end

class ActiveSupport::TestCase
  #ActiveRecord::Migration.check_pending!
    
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all
    
  #class << self
  #  remove_method :describe
  #end

  # Add more helper methods to be used by all tests here...
  #extend MiniTest::Spec::DSL

  #register_spec_type self do |desc|
  #  desc < ActiveRecord::Base if desc.is_a? Class
  #end                         
end 
```

**Comment by zenspider** [comment]
I'm not exactly sure what you want to have happen as there's a few fallacies in your problem description:

1. `public` isn't a kernel method. It's a method on Module and main:

```
>> method(:public)
=> #<Method: main.public>
>> Module.method(:public)
=> #<Method: Class(Module)#public>
>> Kernel.method(:public)
=> #<Method: Module#public>
```

2. That's not how tap works. It's still a block and is yielding `self` down. In other words, it isn't `instance_eval`'d:

```c
VALUE
rb_obj_tap(VALUE obj)
{
    rb_yield(obj);
    return obj;
}
```

This means, I suspect, that what you think is going on in your tap is not what is actually happening:

```
% irb22 --prompt xmp bug0559.rb
>> [].example rescue $!
=> #<NoMethodError: undefined method `example' for []:Array>
>> 
?> main = self # hack to give it a name
=> main
>> 
?> x = Object.new.tap do
?>   raise "BAD" unless self == main
>>   public def example
>>            "Hello World!"
>>          end
>> end
=> #<Object:0x007f8d109c4ba0>
>> 
?> x.example
=> "Hello World!"
>> x.method(:example)
=> #<Method: Object#example>
>> method(:example)              # this is globally defined, not scoped to x
=> #<Method: Object#example>
>> [].example                    # proof
=> "Hello World!"
>> 
?> y = Object.new.tap do |o|
?>   def o.example2
>>     "Hello World!"
>>   end
>> end
=> #<Object:0x007f8d1108c0f0>
>> 
?> method(:example2) rescue p $! # an error here is good
#<NameError: undefined method `example2' for class `Object'>
=> #<NameError: undefined method `example2' for class `Object'>
>> 
?> y.example2
=> "Hello World!"
```

So your other uses of the Object.new.tap/def pattern are leaking methods into the wild.

`let` does an `instance_eval` on the test instance, but that's the instance, not the class, so public won't work there either, I don't think.

**Comment by zenspider** [comment]
Not really sure about having public on main, given that all those methods wind up being private. Don't think it matters tho.

**Comment by danielpclark** [comment]
Ah!  Thanks for the insight!  I'd just come across what I thought was a simply way to build objects.  I didn't know about the leakage.  I now understand what the `self` is inside the `tap` method.  Apparently I've used it now and then without realizing its impact.

What I ended up doing to model the object for my test was moving the methods to a module outside of the test.  And to model sub-objects on the module I used OpenStruct.

It seemed strange to be able to define methods with public in IRB and not in a test.  Now that you've clarified it I'm not sure it's necessary.  I had also tried `include`... but that's not available within `let` either.  Not that you need it.  I was assuming that `public` was in `Kernel` and tried to `include Kernel`.  Perhaps I need to sharpen my debugging ability for something this core/low-level.

**Comment by zenspider** [comment]
Please close if you think this addresses your issue.
