### ISSUE TITLE
configurable signal for dumping current tests

### ISSUE THREAD

**Issue by nate** [seattlerb/minitest#560]
[I commented on an old issue](https://github.com/seattlerb/minitest/issues/304#issuecomment-116890803) but @zenspider [said an issue should be opened](https://twitter.com/the_zenspider/status/616359857126412289) so here I am. I'm running CentOS and there is no INFO signal so I was hoping that [the signal used to dump current tests](https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L319) could be made configurable.

I know that this isn't as nice as it is on BSD where you can use ^T, but I'm willing to send a signal from another terminal to trigger the behavior and I imagine others would be as well.

Thanks!

**Comment by zenspider** [comment]
So, are you triggering via kill in a different terminal? or are you doing something sneaky with stty or what?

**Comment by nate** [comment]
I'm triggering it via kill from a different terminal.

**Comment by nate** [comment]
```kill -SIGNAL <pid>```

**Comment by zenspider** [comment]
Can you please provide a PR for this?

**Comment by teoljungberg** [comment]
The PR seems to be merged, could this issue be closed?

**Comment by nate** [comment]
Yup, thanks!
