### ISSUE TITLE
Should assert_raises really rescue Exception ?

### ISSUE THREAD

**Issue by francoisjacques** [seattlerb/minitest#562]
The current implementation of assert_raises catches everything, which is reasonable for such test, but it is also likely to catch Interrupt which could have been raised during the block execution, and interferes with normal interrupt handling, if Ctrl-C is hit during the block execution.

I seem to get better results by slightly tweaking it with:

```
   rescue Minitest::Skip => e
        return e if exp.include? Minitest::Skip
        raise e
+   rescue SystemExit, Interrupt => e
+     raise e
     rescue Exception => e
```

Thoughts?

**Comment by zenspider** [comment]
> "it is also likely to catch Interrupt which could have been raised during the block execution"

It is also possible to have been raised by the code on purpose:

```
ruby -e 'begin; exit(1); rescue Exception => e; p e; end'
#<SystemExit: exit>
```

I would be hesitant to make your change without some extra logic to make it possible to still test for those exceptions.

**Comment by francoisjacques** [comment]
Ahh yes, true. Darn. Let's think about it some more. There's always the possibility to make it an opt-in option... but it would make the assert_raises syntax clumsy.

**Comment by zenspider** [comment]
Please close this if you think it has been resolved.

**Comment by francoisjacques** [comment]
It has been resolved indeed! Thanks!
