### ISSUE TITLE
Tests fail without an initial test before the first describe block in a Rails controller test

### ISSUE THREAD

**Issue by sealocal** [seattlerb/minitest#568]
Following up on a previous conversation, here is some information on a hack that I used to set up minitest in a Rails app.  It's possible that I'm "doing it wrong."

I used this guide to get started: http://blowmage.com/2013/07/08/minitest-spec-rails4.

**Gemfile**
```ruby
gem 'rails', '4.0.0'

group :test do
  # DIY approach to MiniTest::Spec
  # http://blowmage.com/2013/07/08/minitest-spec-rails4
  gem "minitest", "~> 4.7"
end
```

**test/test_helper.rb**

```ruby
require 'rails/test_help'
require "minitest/spec"

...

class ActiveSupport::TestCase

  # The describe method is removed in Rails 4.2.0,
  # so this remove_method technique can be removed after upgrading.
  class << self
    remove_method :describe
  end

  extend MiniTest::Spec::DSL
end
```

**test/controllers/users_controller_test.rb**

```ruby
require 'test_helper'

class UsersControllerTest < ActionController::TestCase
  setup do
    @user = users(:admin)
    login(@user)
  end

  test "the controller is not nil" do
    # This is the hack.
    # Without this test, the "will get #index" test will fail.
    # This assertion makes no difference in results,
    # but only helped me remember why I added an empty test to my code.
    assert_not_nil @controller
  end

  describe "when logged in" do
    it "will get #index" do
      get :index, window_id: window_id #line 24 in error output
      assert_response :success
      assert_not_nil assigns(:users)
      assert_template :index
    end
  end
end
```

The problem is that I would like to assign instances with my fixtures and login the admin before all of my tests.  If I remove the test named "the controller is not nil", then I get the following error output:

```console
# Running tests:

E

Finished tests in 1.769512s, 0.5651 tests/s, 0.0000 assertions/s.

  1) Error:
when logged in#test_0001_will get #index:
RuntimeError: @controller is nil: make sure you set it in your test's setup method.
    test/controllers/users_controller_test.rb:24:in `block (2 levels) in <class:UsersControllerTest>'

1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

Adding the test before the describe block makes both the tests pass:

```console
# Running tests:

..

Finished tests in 1.836679s, 1.0889 tests/s, 2.1778 assertions/s.

2 tests, 4 assertions, 0 failures, 0 errors, 0 skips
end
```

Maybe I should be using a before block instead of setup? However, the error output suggests a setup method, and I wanted to set variables and run the login method before all of the tests.

Any suggestions?

**Comment by zenspider** [comment]
You're mixing and matching minitest's describe with rails' setup. I am not sure what will happen in that case, since a minitest setup is just a method and rails' is some `register_callback` thing. I wouldn't trust it like that. Stick to `def setup`. I'd also be wary of mixing and matching `ActionController::TestCase` subclasses with nested `describe` blocks.

**Comment by sealocal** [comment]
Right, in my pursuit of laziness, mixing the syntaxes seems to work, but only with that meaningless test. With time, I will fix up my test suite.  I suppose this issue should be closed.

**Comment by zenspider** [comment]
If you use minitest-rails, you can use describe at the top level and have it properly subclass `ActionController::TestCase`. (or, you can register the test type yourself, just crib off of minitest-rails).
