### ISSUE TITLE
expectations attached to anonymous functions raise error?

### ISSUE THREAD

**Issue by siruguri** [seattlerb/minitest#569]
Hi - 
If I force Minitest to 5.5.1, I don't see this error but when I don't, and my bundle bumps up to 5.7.0, I get this error whenever there is an expectation of the form `lambda { ... }.wont_change`:

````

NoMethodError: private method `binding' called for nil:NilClass

````

The error goes away if I use the `assert_difference()` form of setting the same expectation.

**Comment by zenspider** [comment]
You're going to have to provide more info than that. `assert_change` is not a minitest method, so I need to know what you're depending on and how to reproduce.

**Comment by siruguri** [comment]
I apologize... I somehow omitted to notice that `wont_change` is a `minitest-rails` method - defined in (Minitest::Rails::Expectations)[https://github.com/blowmage/minitest-rails/blob/master/lib/minitest/rails/expectations.rb]

The bump of the `minitest` gem did not bump `minitest-rails` - the `minitest-rails` version is 2.1.1 for both versions of `minitest`

Is that adequate?

**Comment by blowmage** [comment]
Minitest 5.7 changed how blocks are dealt with in expectations. It was a breaking change. You need to upgrade to minitest-rails 2.2 if you want to use minitest 5.7.

**Comment by blowmage** [comment]
[This is the change](https://github.com/blowmage/minitest-rails/commit/90f3cfda7834c49841ee3c95b96eeb9394f4a5f1) you need for using expectations with blocks in minitest 5.7+.

**Comment by zenspider** [comment]
Closing
