### ISSUE TITLE
Mocks verify even when calling the mocked method a few times.

### ISSUE THREAD

**Issue by haihappen** [seattlerb/minitest#570]
Maybe I miss understand mocks, but shouldn't calling a mocked method more times than expected raise an error?

```ruby
require 'minitest'
require 'minitest/autorun'
require 'minitest/mock'

class Test < Minitest::Test
  def test_should_not_verify
    mock = Minitest::Mock.new
    mock.expect :foo!, nil, []

    mock.foo!
    mock.foo!

    refute mock.verify
  end
end
```

**Comment by zenspider** [comment]
Honestly, I see no value in such a thing erroring out, but I'm a TDD guy, not BDD. I'll leave this to someone else to address. @zamith, maybe?

**Comment by zamith** [comment]
@hailhappen That is how RSpec works, but I don't think it's necessarily true that mocks have to behave like that. We might, in the future, want to add the notion of how many times a message was received, but for now, mocks verify that a message was called. Not that was called once or twice, just that it was actually called.

Do you have any real example where this behaviour introduced a bug or had a negative impact on readability? It might be easier to reason about this if you do.

**Comment by haihappen** [comment]
It didn't introduced a bug, however I found no way to test following wrapper:

```ruby
class UnreliableService
  # ...
  def command(*args, **kwargs)
    @telnet.cmd(*args, **kwargs)
  end
end

class RetryingService < DelegateClass(UnreliableService)
  def command(*args, times: 3, **kwargs)
    super(*args, **kwargs)
  rescue Timeout::Error       #
    retry if (times -= 1) > 0 # How do I test this?
    raise                     #
  end
end
```

**Comment by zamith** [comment]
How are you trying to test this? I feel it's not going to be trivial, because of the `DelegateClass`, which means we don't have an easy way to mock the `UnreliableService`, I think.

**Comment by haihappen** [comment]
At the moment I'm testing it by ensuring that `@telnet.cmd` is called at least once.

**Comment by zamith** [comment]
Could you put the test code here as well? I'm trying to see if there is any other way around it other than mocks and counting the number of calls. If we find that there isn't, we can then go ahead and try to implement that.

**Comment by haihappen** [comment]
Ok, few things:
* You don't have to rewrite mocks only for me. :wink:
* This is not the exact code, because it wasn't open-sourced (yet).
* I'm a fan of dependency injection.

```ruby
  def test_execute_retries_if_failing
    telnet = Minitest::Mock.new    
    times = 3

    failing_telnet = SimpleDelegator.new(telnet)
    failing_telnet.define_singleton_method :cmd do |*args|
      # cmd will fail the first x times.
      return nil if (times -= 1) > 0

      __getobj__.cmd *args
      'error id=0 msg=ok'
    end

    telnet_class = Class.new do
      define_singleton_method :new do |*|
        failing_telnet
      end
    end

    telnet.expect :waitfor, nil, ['Match' => /^TS3\n/]
    telnet.expect :cmd, 'error id=0 msg=ok', ['String' => 'use 1', 'Timeout' => 3.seconds, 'Match' => /^error id=\d+/]
    
    service = RetryingService.new(UnreliableService.new)
    service.connect telnet_class: telnet_class # initialise Telnet connection and waitfor
    service.command 'use 1'

    telnet.verify
  end
```

**Comment by zamith** [comment]
Ok, would this be ok?

```ruby
class UnreliableServiceTest < Minitest::Test
  class FakeService
    def initialize(times)
      @times = times
    end

    def command(*args)
      fail Timeout::Error if (@times -= 1) > 0
      'error id=0 msg=ok'
    end
  end

  def test_retries_with_success
    service = RetryingService.new(FakeService.new(2))
    assert_equal 'error id=0 msg=ok', service.command('use 1', times: 3)
  end

  def test_retries_and_fails
    service = RetryingService.new(FakeService.new(4))
    assert_raises(Timeout::Error) do
      service.command('use 1', times: 3)
    end
  end
end
```

It tests the retrying system, by injecting a different service that we can control. You can then have other tests to make sure that telnet works as expected, but separating those two concerns makes this much easier to test, IMO. What do you think?

**Comment by haihappen** [comment]
Omg! Why didn't I came up with this solution?! This is so much cleaner. I will test it and keep you updated! :smile:

**Comment by zamith** [comment]
Cool. :)

**Comment by haihappen** [comment]
Worked for me.. so do we close this issue?

**Comment by zamith** [comment]
If your problem is solved I'd say yes. Let's keep postponing the addition
of further functionality to the mocks for as long as we can. Minitest mocks
are intended to be very simple and fast, and adding a lot of stuff will
surely break that principle.

Thanks for the healthy discussion, though.

**Comment by haihappen** [comment]
So long, and thanks for all the help :)
