### ISSUE TITLE
Instance method collisions

### ISSUE THREAD

**Issue by ivantsepp** [seattlerb/minitest#573]
One could accidentally override methods defined in `Minitest::Test` or `Minitest::Runnable` and get unexpected results. For example, this is along the lines of what I ran into recently:
```ruby
require "minitest/autorun"
module UsefulStuff
  def location
    "stuff"
  end
end

describe "Blah" do
  include UsefulStuff

  def test_whatever
    assert false
  end
end
```
This is the output:
```
minitest_example$ ruby example_from_readme.rb
Run options: --seed 50521

# Running:

F

Finished in 0.001216s, 822.5375 runs/s, 822.5375 assertions/s.

  1) Failure:
stuff:
Failed assertion, no message given.

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

If this is something we want to avoid, the only thing I can think of now is to rename internal methods to avoid collision. Maybe renaming `location` to `_location`?

**Comment by zenspider** [comment]
Sorry, but minitest's public API is very well documented and public. I'm not going to go changing it now without a major rev and a ton of backwards incompatible changes for an inconvenience. Assuming you're trying to test `UsefulStuff`, I'd suggest you not mix it into the test class itself and instead either test it directly or mix it into an appropriate instance and test that.

**Comment by ivantsepp** [comment]
Thanks for the insight and taking the time to look into this! :smile:

**Comment by zenspider** [comment]
No problem! Let me know if I can help.
