### ISSUE TITLE
(Question/Advice) Minitest Preemptive Queue

### ISSUE THREAD

**Issue by trabulmonkee** [seattlerb/minitest#574]
Is there a way to build a queue preemptively of tests that Minitest will execute, so that I have control over how much of the queue is executing at one time?

Given that I have multiple test suite files running in parallel, with one or more test cases in each file also running in parallel.

My first thought was to have Minitest run first as normal and use its test method gathering capability to write to a log file of all the tests first without executing them.  Then once that is all complete, actually build a queue from the log file and then run/execute the tests.

Looking for advice.

**Comment by zenspider** [comment]
What's your actual problem?

**Comment by trabulmonkee** [comment]
I use minitest to drive browser testing via selenium-webdriver.

I use the Se Grid hub to queue the tests.  But I slam the hub with all
tests via parallelism at the test class file level, which in turn uses
minitest-parallel to runs test methods.

I need to queue the queue, so to speak, to control the amount of tests sent
to the Se Grid hub queue.

**Comment by trabulmonkee** [comment]
Closing

My original implementation had issues, I was using my own threading at the file level instead of the tooling provided by minitest.  Hence my question about queuing the queue.  I have gained additional knowledge and since have gone in a different direction by using the parallel_executor ENV['N'] to allow minitest to control the queue.
