### ISSUE TITLE
Calling mock in other thread

### ISSUE THREAD

**Issue by panitaxx** [seattlerb/minitest#582]
Hello. 

When calling a mock from a thread exceptions get lost and mock.verify does not works (it asserts true). Is there any solution for this. Here is an example 

```ruby
require "minitest/autorun"

class C
  def initialize(pr)
    @pr=pr
  end

  def run(a,b)
    Thread.new(a,b,&@pr)
  end
end

class TestC  < Minitest::Test

  def test_multi_call
    pr_mock = MiniTest::Mock.new
    pr_mock.expect(:test,nil,[1,2])
    pr = Proc.new { |a,b| pr_mock.test(1,2) }
    cinst = C.new(pr)
    cinst.run(1,2)
    sleep(0.5)
    cinst.run(1,2)
    assert(pr_mock.verify)
  end
end
```

**Comment by zamith** [comment]
Do you have a real world scenario where this would be useful? This is an interesting problem, just unsure of whether it is something Minitest should resolve or not.

**Comment by panitaxx** [comment]
I have this "alarm" system where an alarm starts a thread. Each alarm has different procs. I just wanted to test out that the proc really gets called and gets called only once (since each alarm can repeat lots of times but the thread should be started only once). 

My workaround was to catch the exception in the  `Proc` and exit right there. Maybe just put some guidance on the readme so people knows how it works with threads.

**Comment by zamith** [comment]
Would testing side effects of that suffice?

Adding something on the README I think is a good idea regardless of whether we fix this or not. @zenspider what do you think? Should this be fixed, or taken as a feature and explained on the README, only?

**Comment by zenspider** [comment]
This code example isn't sound. You're spawning threads and throwing them away before verifying that they've finished running.

This is partially how threads work by default. See [Thread exception handling](http://docs.ruby-lang.org/en/2.2.0/Thread.html#class-Thread-label-Exception+handling) for more information.

**Comment by zenspider** [comment]
@zamith your call. Personally, I think the examples given are not good examples, so they're not valid reasons to force change. Want to see that a proc was called? Set a boolean:

```ruby
  def test_multi_call
    called = false
    pr = Proc.new { called = true }
    cinst = C.new(pr)
    cinst.run(1,2)
    sleep(0.5) # this seems bad
    cinst.run(1,2) # this seems bad, and unexplained
    assert called, "proc not called"
  end
```

**Comment by zamith** [comment]
@zenspider I agree with you. My question is more about how we go about documenting this for other people who wish to know how to do this. Is this PR enough? Do we assume people will know? Do we write on the README, on a wiki page on GitHub?

**Comment by zenspider** [comment]
I'm not gonna use the wiki. I want it under version control. Adding something to the readme is fine. My problem is that I'm blind to this type of issue because the LAST thing I reach for is a mock. In this case, a local variable works just fine. I'm not sure how much I want to document basic ruby programming patterns. That's a lot to cover.

Obviously(?) this case comes up enough. Want to attack it?

**Comment by zamith** [comment]
I can add a small note to the readme, telling people not to use mocks with threads, and how to do it with local variables. Would that work?

**Comment by zenspider** [comment]
Absolutely. Go for it.

**Comment by zenspider** [comment]
@zamith btw. Thanks for sticking this out w/ me. I know I've been dropping the ball on this shit. I'm catching up on my backlog and prioritizing minitest to the front.

**Comment by zenspider** [comment]
Merged readme patch. Closing this issue.
