### ISSUE TITLE
Options from Rake::TestTask are being ignore

### ISSUE THREAD

**Issue by odigity** [seattlerb/minitest#583]
I don't know if this is a Rake issue, Minitest issue, or combination of both -- but the options advertised by Rake::TestTask (TESTOPTS, TESTFILE) seem to do nothing when using Minitest::Test.

I've got a StackOverflow question open about it, but it hasn't received any attention yet:

http://stackoverflow.com/questions/32956801/what-is-the-point-of-setting-testopts-v-with-rake-test

**Comment by teoljungberg** [comment]
@odigity Do you have an example where this is replicated? I can't with replicate it with this example:

`foo.rb`:
```ruby
class Foo
  def bar
    "baz"
  end
end
```

`foo_test.rb`
```ruby
require "minitest/autorun"
require_relative "foo"

class FooTest < Minitest::Test
  def test_bar
    skip
  end
end
```

`Rakefile`
```ruby
require "rake/testtask"

Rake::TestTask.new do |t|
  t.pattern = "*_test.rb"
end
task default: :test
```

Output:
```
/tmp % TESTOPTS="-v" rake test
Run options: -v --seed 9686

# Running:

FooTest#test_bar = 0.00 s = S

Finished in 0.001044s, 957.8544 runs/s, 0.0000 assertions/s.

  1) Skipped:
FooTest#test_bar [/private/tmp/foo_test.rb:6]:
Skipped, no message given

1 runs, 0 assertions, 0 failures, 0 errors, 1 skips
/tmp % rake
Run options: --seed 52783

# Running:

S

Finished in 0.000940s, 1063.8298 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
```

**Comment by odigity** [comment]
Weird.  Now I do see the "-v" mentioned in the "Run options:" line, and I can see both TESTOPTS and TESTFILE env vars in my test_helper.rb, but it's still ignoring the TESTFILE value in terms of behavior.

I tried it both with a path relative to approot (`test/models/user_test.rb`) and relative to the test dir (`models/user_test.rb`), but in either case it runs all tests in all files.

**Comment by teoljungberg** [comment]
Still, can you provide reproduction steps?

**Comment by odigity** [comment]
I'll try to put something together soon.

In the meantime, I'm still confused about a few things:
1) If I search the repo on github for 'TESTOPTS' or 'TESTFILE', I find nothing.  How is that possible?
2) There's no .gemspec file in the repo.  How does this thing even get pushed to rubygems?

**Comment by zenspider** [comment]
> On Oct 10, 2015, at 13:08, Ofer Nave <notifications@github.com> wrote:
> 
> I'll try to put something together soon.
> 
> In the meantime, I'm still confused about a few things:
> 1) If I search the repo on github for 'TESTOPTS' or 'TESTFILE', I find nothing. How is that possible?
> 2) There's no .gemspec file in the repo. How does this thing even get pushed to rubygems?

1) Rake is responsible for TESTOPTS and TESTFILE, not minitest. Look in rake.

2) "Magic".

**Comment by odigity** [comment]
> 1) Rake is responsible for TESTOPTS and TESTFILE, not minitest. Look in rake.

But it's *minitest's* behaviour that is supposed to be altered by feeding those options to Rake.  How?  How does using those options with rake result in a change to *minitest's* behaviour?

I feel like I'm asking a very straightforward question that I should have already been able to answer with several hours of digging through docs and code... (which I have done already)

> 2) "Magic".

Seriously?  That's the answer you're going with?

**Comment by odigity** [comment]
I did some more digging, and while I still don't understand the details, I have now learned what hoe is and what it's used for and am guessing that's how the gemspec is autogenerated at build/push time.  So, that's one mystery solved...

**Comment by zenspider** [comment]
1. No, rake is invoking minitest. Not the other way around. Minitest doesn't know anything about rake. That's why you don't see anything to do with those environment variables in minitest. I said to go look at rake. What'd you find?

2. Yes. I was at a conference, on shitty wifi, tired, and busy. I'm not beholden to you and I don't owe you a comprehensive answer. You could have searched the project for gemspec and found an answer.

3. You still have yet to provide any reproduction.

**Comment by odigity** [comment]
Apparently the option is TEST, not TESTFILE, and it does work.  Don't know where I got the notion that it was TESTFILE.

Sorry.  Closing the issue now.
