### ISSUE TITLE
Print test descriptions

### ISSUE THREAD

**Issue by cmisenas** [seattlerb/minitest#587]
Is there a way to do this when tests are run? -v only shows progress right?

**Comment by zenspider** [comment]
"Do this" is vague

**Comment by cmisenas** [comment]
Oops. By "this" I meant if you have 
```
describe MemeAsker, :ask do
  describe "when passed an unpunctuated question" do
    it "should invoke the appropriate predicate method on the meme" do
       ....
    end
  end
end
```

It would output the string after `describe` and `it` when the tests are ran.

**Comment by blowmage** [comment]
Take a look at [minitest-reporters](https://github.com/kern/minitest-reporters) for more reporting options. It looks like you are aster the spec reporter.

**Comment by cmisenas** [comment]
Ah, Thanks! :+1:
