### ISSUE TITLE
Parallelize when stubbing ENV

### ISSUE THREAD

**Issue by mig-hub** [seattlerb/minitest#589]
Hello @zenspider ,

Since we discussed it on twitter, here is the test I am having problems with:
[admin_test](https://github.com/mig-hub/populate-me/blob/master/test/test_admin.rb)
And it tests this code:
[admin](https://github.com/mig-hub/populate-me/blob/master/lib/populate_me/admin.rb)

You'll find it a bit messy since it is all a big rewrite and I actually intend to change the tests since a lot of things are not tested in the best way possible, but still I'd like to understand what is wrong before doing so.

Basically when I run the test for it (`rake TESTONLY=admin`) without `parallelize_me!`, just randomized, it works well, but it does not pass in parallel, most likely because of the ENV that I am trying to stub. I tried different ways. Putting it in a mutex helps having less problems but it doesn't look this clean and still fail quite often.

It probably all falls down to my poor understanding of thread safety to be honest.

I am not exactly sure what you meant by accessing ENV locally and stubbing this access. I made the access a class method of Admin and stubbed this but I guess this is not what you meant.

You'll also see that I commented out the opposite (ENV variable not set) since it is the default anyway and I wanted to isolate as much as possible the problem. Removing it does not seem to change the outcome although I asked myself if this is better or not for thread safety to be explicit with this state as well.

Thank you in advance for your help.
mig

**Comment by zenspider** [comment]
Class methods are effectively global. So you moved a global from ENV to your class and that doesn't help you with parallelization. Make it an instance method so each test can stub their own version _in parallel_. Otherwise, this problem doesn't go away, it just moves.

**Comment by mig-hub** [comment]
@zenspider yeah this is pretty much the conclusion I came to. Although feel a bit guilty going further and change code only for the sake of passing tests in parallel since ENV is a constant and should not change.

But I think I'll go for it because the pleasure of passing tests in parallel is like no other. If I add a bit of Shellac playing in the background and a cup of coffee, I feel close to satori.

**Comment by zenspider** [comment]
Changing code to make tests pass is called "improving design". It is a good thing.

If this is handled, please close.

**Comment by zenspider** [comment]
No response. Closing.
