### ISSUE TITLE
Raise on nested stubs 

### ISSUE THREAD

**Issue by mig-hub** [seattlerb/minitest#590]
Not sure it is a bug since it is not a good way of doing this and it is better to do one stub with logic on it, but anyway, this nested stub raises `undefined method __minitest_stub__big__`:

```ruby
my_object.stub(:big, false, [1]) do
  my_object.stub(:big, true, [700]) do
    # Asserts
  end
end
```

**Comment by zamith** [comment]
I don't think this is a use case we want to allow. You should only stub something once. That being said, maybe the error message could be more informative. What do you think?

**Comment by mig-hub** [comment]
@zamith, I discovered it accidentally while turning some RSpec tests into Minitest and trying the closest code first, which obviously doesn't work because stubs in RSpec behave differently. So yeah this is a pretty unlikely case.

Although like you said, an error message which describes exactly what is happening would be nice.

I suppose we could check if `self.respond_to?(new_name)`.

**Comment by mig-hub** [comment]
I drafted [this pull request](https://github.com/seattlerb/minitest/pull/591)

**Comment by zenspider** [comment]
Since #591 was closed, I'm closing this one. Thanks for the report.
