### ISSUE TITLE
Question: Trying to get an understanding around serial/parallel execution

### ISSUE THREAD

**Issue by trabulmonkee** [seattlerb/minitest#608]
Please help me understand,

I see that in minitest > self.__run that serial test cases run first then parallel test cases due to reporter locks and it looks like this is based on per file execution.

Is there a way to gather all test cases in all files first, then run the test cases in parallel as appropriate?

**Comment by zenspider** [comment]
It's definitely not on a per-file basis as minitest has no notion of files. The rake test task or a simple file that requires all your test files is all you need to ensure all your parallel tests run together.

**Comment by trabulmonkee** [comment]
ah, so I see, I believe it is with how I am gathering the files to run via the rake task.  My understanding was incorrect.  Thanks for pointing me in the right direction.
