### ISSUE TITLE
add before_tests hook

### ISSUE THREAD

**Issue by natesholland** [seattlerb/minitest#611]
There is a helpful after_tests hook which runs a block of code after the tests have completed. It would be nice to have a complementary before_test hook that ran before all the tests ran. Would people be interested in this?

I'd be happy to work up some kind of draft for a pull request if this would be accepted into the main repo.

**Comment by zenspider** [comment]
The thing is, a hook isn't really isn't needed to run things before your tests... you just write code and it executes.

**Comment by natesholland** [comment]
I'm talking about a place to tie into that runs once before any tests run, not a before suite for a specific file. I've found ways to monkey patch this into minitest. Where would you suggest I put code to be run before any tests are run?

**Comment by zenspider** [comment]
At the top of any file. test_helper.rb is a common one, tho I usually don't use one. It's just code. Files only "run" once.

**Comment by zenspider** [comment]
No response. Closing.
