### ISSUE TITLE
Question: Is there a way to speed up test output?

### ISSUE THREAD

**Issue by jonahx** [seattlerb/minitest#612]
Running trivial tests from the command line takes about half a second, eg:

```
time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 26670

# Running:

.

Finished in 0.001189s, 840.9227 runs/s, 840.9227 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
real	0m0.659s
```

whereas without the "report" part it executes almost instantly:

```
time ruby -rminitest/spec -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'

real	0m0.146s
```
Is there any way to get a simple report *and* the almost instant speed?  I'm using minitest in a TDD loop where the tests are triggered when I `:w` in vim, and I'd like to see the results almost instantly in growl.

**Comment by phiggins** [comment]
In the second example your tests aren't running:

```
pete@balloon:~$ time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do raise("lol") end end'
Run options: --seed 29705

# Running:

E

Finished in 0.001502s, 665.7816 runs/s, 0.0000 assertions/s.

  1) Error:
blah#test_0001_blah:
RuntimeError: lol
    -e:1:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

real	0m0.207s
user	0m0.156s
sys	0m0.024s
```

**Comment by jonahx** [comment]
then my follow-up question is: why does it take half a second to test 2+2 = 4, and is there anyway to make it faster?  






On Wed, Mar 9, 2016 at 3:56 PM -0800, "pete higgins" <notifications@github.com> wrote:












In the second example your tests aren't running:

pete@balloon:~$ time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do raise("lol") end end'
Run options: --seed 29705

# Running:

E

Finished in 0.001502s, 665.7816 runs/s, 0.0000 assertions/s.

  1) Error:
blah#test_0001_blah:
RuntimeError: lol
    -e:1:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

real    0m0.207s
user    0m0.156s
sys 0m0.024s

**Comment by phiggins** [comment]
Running your example on my machine, a 4 year old Lenovo, does not take half a second:

```
pete@balloon:~$ time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 4610

# Running:

.

Finished in 0.001330s, 752.0075 runs/s, 752.0075 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real	0m0.159s
user	0m0.136s
sys	0m0.024s
```

What version of ruby are you using? How many gems do you have installed? How did you install ruby?

**Comment by jonahx** [comment]
Weird.  I’m on an ~3 yo macbook pro, 8G ram, and activity monitor 
looks fine.

I have a bunch of gems installed, but see the same behavior when I run 
with `bundle exec` on a minimal Gemfile.

Ruby version is ruby 2.1.2p95, installed with rbenv.

Thanks for your help troubleshooting.

**Comment by phiggins** [comment]
I asked about the number of gems installed because of things like this: https://twitter.com/tenderlove/status/707321253388914688

Not saying that is your problem, necessarily, just curious.

Is the time better or worse when you use your system ruby?

If you do a fresh install of ruby 2.2 or 2.3 without installing any gems, does that make a big difference? It might be worth seeing if there are any gotchas around installing rubies with rbenv on OSX, but I am not an expert in such things.

**Comment by jonahx** [comment]
So you were definitely on the right track.  Here's what I found so far...

I installed a fresh ruby 2.3.0 + gems for my project: Time got even worse, about 0.55 on avg.
I installed a fresh ruby 2.2.4 + no gems: Time was like yours, about 0.15 avg.
I added my project gems: Time jumped to 0.35 avg.

Version does matter, and number of gems matter, presumably because it makes `require` calls slower?  

In any case, not a minitest issue, but if you do know of any solutions I'd appreciate it.  Thanks again for your help.

**Comment by blowmage** [comment]
I can't say for sure, but I suspect this is an issue with the environment you are running these commands in. Are you using a ruby version manager like RVM or rbenv? If so, then you are using a shim which adds some additional overhead every time you call `ruby` or `gem`. Or are you perhaps invoking bundler in your rake tasks? Or using a shim for rake that was created by bundler?

I'm using chruby, which doesn't use a shim, and I don't see the slowdown you are reporting. I also don't have bundler installed. Here is my baseline:

```
$ time ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

real 0m0.010s
user 0m0.006s
sys  0m0.003s

$ time ruby -e ""

real 0m0.059s
user 0m0.039s
sys  0m0.017s

$ time gem -v
2.5.1

real 0m0.109s
user 0m0.081s
sys  0m0.024s
```

And here is your first test:

```
$ time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 61678

# Running:

.

Finished in 0.000813s, 1230.0426 runs/s, 1230.0426 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real 0m0.089s
user 0m0.064s
sys  0m0.022s
```

And here is your second test without the reporting:

```
$ time ruby -rminitest/spec -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'

real 0m0.081s
user 0m0.057s
sys  0m0.020s
```

Another thing to check is if you have any minitest plugin gems installed. They will get loaded by minitest at startup. Hope this helps.

**Comment by phiggins** [comment]
Thanks @blowmage!

**Comment by jonahx** [comment]
@blowmage,

Thanks for your reply.  Per my previous answer, yes I am indeed using rbenv, perhaps I should consider chruby instead.  

> Another thing to check is if you have any minitest plugin gems installed. They will get loaded by minitest at startup. Hope this helps.

Yes, I am using "guard-minitest".   When I remove it, my numbers jump back down to ~0.15.  It surprised me that it affects peformance merely by *being installed*.

In any case, do you know of an alternative I can use?  Ultimately, I am using guard + guard-minitest simply because I want my workflow to be:

1. Save with `:w` in vim
2.  Instantly rerun any relevant tests 
3.  See the results instantly in growl

My current solution achieves this, but with effectively a half-second or longer delay between pressing save and seeing the result.  It may seem like a small thing, but instant results give a very different feel to the flow of it, and there's not reason I shouldn't be able to achieve that when the tests themselves run essentially instantly.

**Comment by blowmage** [comment]
I prefer [minitest-autotest](https://github.com/seattlerb/minitest-autotest) myself...

**Comment by jonahx** [comment]
@blowmage Thanks for the recommendation.

I just read the minitest-autotest docs: Is it correct to assume that this is used as a standalone library?  That is, I don't use this *with* guard but as a replacement for guard + guard-minitest?

Also, I noticed that a separate gem was required for the "spec" style?  If I am worried about speed, should I just use that unit style?  Ie, will the autotest-spec gem slow things down?

**Comment by zenspider** [comment]
Here are my numbers. Tho I'm happy to help you look into this, I assure you, the problem won't be in minitest:

### mike's basic numbers:

```
10010 % X=1 time ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
        0.00 real         0.00 user         0.00 sys
10011 % X=1 time ruby -e 0
        0.03 real         0.02 user         0.00 sys
10012 % X=1 time gem -v
2.4.5
        0.09 real         0.07 user         0.01 sys
```

### Pure ruby, no rubygems:

```
10004 % time ruby --disable-gems -Ilib -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 56518

# Running:

.

Finished in 0.001564s, 639.3862 runs/s, 639.3862 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real	0m0.094s
user	0m0.078s
sys	0m0.014s
```

### rubygems + direct pathing

```
10005 % time ruby -Ilib -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 39947

# Running:

.

Finished in 0.001264s, 791.1392 runs/s, 791.1392 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real	0m0.094s
user	0m0.079s
sys	0m0.013s
10006 % 
```

### loaded via rubygems:

```
10006 % time ruby -rminitest/autorun -e 'describe "blah" do it "blah" do (2+2).must_equal 4 end end'
Run options: --seed 60303

# Running:

.

Finished in 0.002049s, 488.0429 runs/s, 488.0429 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

real	0m0.092s
user	0m0.075s
sys	0m0.013s
```

NOTE: I have VERY few gems installed:

```
% gem list | grep -ci "^[a-z]"
18
```

**Comment by zenspider** [comment]
One suspect:

https://github.com/guard/guard-minitest/blob/master/lib/minitest/guard_minitest_plugin.rb#L4

**Comment by jonahx** [comment]
@zenspider You are right, definitely not minitest itself.  And thanks for the offer to help.

> One suspect:
> 
> https://github.com/guard/guard-minitest/blob/master/lib/minitest/guard_minitest_plugin.rb#L4

So if I comment that line out of the gem, it does indeed trop the time from .45 to .20, on the test we've been using.  The problem is that it also makes the growl notifications stop working, although guard does still pick up file changes and reruns the tests in the console.  I don't really understand what that line is doing or why it's connected to growl... is there a way to leave the line commented out and get the growl notifications back?

Or do you have any other, possibly better solutions, to the overall problem?

**Comment by zenspider** [comment]
Are you on a real disk, or SSD?

You can probably get around it by keeping the require and just dropping the dirglob.

I'd try rerunning the whole thing under either stackprof or some other profiler and see where the time is objectively being spent. There's only so much you can shave off tho.

And yes, minitest-autorun is a competitor to guard (of a sorts). They're not meant to be run together.

**Comment by jonahx** [comment]
@zenspider I'm on SSD.  Removing the glob gets growl working again, but the time jumps back up to .45.  

I will try out minitest-autorun when I have a bit more time to set it up.  Thanks for your help.

**Comment by zenspider** [comment]
Do the profiler thing. It might be that one of your gems/plugins/whatever is a major piece of the pie. Filing an issue or finding a suitable substitute might take care of it and bring the times down to an acceptable level. I'm curious to see the results too. Might be worth noting somewhere on my side.

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
No response in 10 days. Closing.
