### ISSUE TITLE
Can minitest test with infinite loop

### ISSUE THREAD

**Issue by jinleileiking** [seattlerb/minitest#617]
`ruby -Ilib:test ./test_es.rb`
only run test once time.
Can the test run all the time . with fail percent report output ?

**Comment by utilum** [comment]
Infinitely?
If you often need this, you can write a rake task to do it.
If you often need this for many projects, perhaps a plug-in?
What are you testing?

**Comment by jinleileiking** [comment]
@utilum  I want to test the stability of my web service.

**Comment by utilum** [comment]
@jinleileiking So your test calls es and passes if the http status code is success?

**Comment by jinleileiking** [comment]
@utilum Yes.

**Comment by phiggins** [comment]
@jinleileiking Minitest isn't really made to do what you're trying to do, and I don't think you need something as complicated as minitest. You could just write a simple script to automate requesting your service repeatedly, something like this:

```
pete@balloon:/tmp$ cat test_webservice.rb 
require 'net/http'
require 'pp'

results = Hash.new {|h,k| h[k] = 0 }

uri = URI(ARGV.first)

begin
  loop do
    response = Net::HTTP.get_response(uri)
    results[response.class] += 1
  end
rescue Interrupt
  pp results
end
```

Here is me trying it out:

```
pete@balloon:/tmp$ ruby test_webservice.rb https://google.com
^C{Net::HTTPMovedPermanently=>70}
pete@balloon:/tmp$ ruby test_webservice.rb https://www.google.com
^C{Net::HTTPOK=>41}
```

Not the prettiest but it gets the point across.

**Comment by utilum** [comment]
It sounds like you want a monitoring tool more than a test tool. I think you'd have to code it if you wanted to use Minitest, but this isn't what it's made for. It's made to test your code, and there's tools to run the tests every time you change your code. 
How about NewRelic, or some [monitoring gem](https://rubygems.org/search?utf8=%E2%9C%93&query=monitoring)?

**Comment by jinleileiking** [comment]
@all Thanks, I will check newrelic @utilum
