### ISSUE TITLE
parallel execution of asserts fails a test

### ISSUE THREAD

**Issue by sumproxy** [seattlerb/minitest#621]
Here's the code 
https://gist.github.com/sumproxy/5da24716ffe456c288dec44c4107e22e
The test fails when asserts are placed in one method and works fine when each assert is wrapped in its own test method.

**Comment by nbekirov** [comment]
I think that minitest has nothing to do with your issue.

Executing 
```ruby
self.class.send(:define_method
``` 
in `Garden#initialize` adds a method to `Garden` class that is shared for **all** of its instances. 
Running it a [second time](https://gist.github.com/sumproxy/5da24716ffe456c288dec44c4107e22e#file-garden_test-rb-L16) overrides the first definition. Try to run `garden_1.bob` again after any call to `garden_2` and you will see for yourself.

As it seems that you want to define methods that are available only to particular garden isnatcnes may be what you need is a [singleton method](https://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/39-ruby-s-object-model/lessons/131-singleton-methods-and-metaclasses). 

Changing the line above to:
```ruby
self.send(:define_singleton_method
```
makes the test pass...

**Comment by sumproxy** [comment]
You're right! I'm really sorry for being irrelevant here, just couldn't find a place where I could get help on it. Thanks a lot!
