### ISSUE TITLE
Minitest::Assertions#assertions not initialize

### ISSUE THREAD

**Issue by mathieujobin** [seattlerb/minitest#624]
as explained in this cucumber issue https://github.com/cucumber/cucumber-ruby/issues/751

I have this bug where `self.assertions` on this line is nil, giving the NoMethodError + for NilClass

https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L135

so, in all my applications. I have this fix hack

```ruby
require 'minitest/spec'
module MinitestWorld
  extend Minitest::Assertions
  mattr_accessor :assertions
  self.assertions = 0
end

World(MinitestWorld)
```

would it make sense to initialize it in a `self.included` method in the Minitest::Assertions modules?
I could write that patch if it makes sense for you to merge it

**Comment by zenspider** [comment]
This is intentional and is documented here: https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L12-L16

Let me know if you need any further assistance.
