### ISSUE TITLE
repo not loadable as a gem

### ISSUE THREAD

**Issue by mathieujobin** [seattlerb/minitest#625]
how come this repo is not loadable like any gem ?

i can't do

`gem 'minitest', path: 'to/my/forks/minitest'`

**Comment by blowmage** [comment]
Because there is no `minitest.gemspec` file. The gem is published using Hoe, and the gemspec is generated as part of that process. The generated gemspec is not committed to the repo.

**Comment by zenspider** [comment]
Also because I release early and often. There's no need for the repo to be used as a gem. I release when the code is ready and it is almost always ready.

**Comment by mathieujobin** [comment]
thank you for the explanation.
how do you suggest I could load my fork of it when testing a modification I'd like to make ?

**Comment by zenspider** [comment]
`ruby -Ipath/to/repo/lib some/test/file.rb` always works
