### ISSUE TITLE
Can't covert nil into float

### ISSUE THREAD

**Issue by plynchnlm** [seattlerb/minitest#628]
When I do "rake test"  I get the following stacktrace (below), all of whose lines are from minitest.rb.  The test that seems to be running is a perftest, but that test runs fine on its own.  The problem it is running into is in these lines:

```
479   class ProgressReporter < Reporter
480     def record result # :nodoc:
481       io.print "%s#%s = %.2f s = " % [result.class, result.name, result.time] if
482         options[:verbose]
483       io.print result.result_code
484       io.puts if options[:verbose]
485     end
486   end
```

I'm not sure why result.time was nil, but I patched the problem by changing 482 to:

```
482         options[:verbose] and result.time
```

and my "rake test" now runs fine.

Here's the full stacktrace:

```

/depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:481:in `%': can't convert nil into Float (TypeError)
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:481:in `record'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:653:in `block in record'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:652:in `each'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:652:in `record'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:322:in `run_one_method'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:310:in `block (2 levels) in run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:309:in `each'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:309:in `block in run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:348:in `on_signal'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:335:in `with_info_handler'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:308:in `run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:158:in `block in __run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:158:in `map'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:158:in `__run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:135:in `run'
    from /depot/packages/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/minitest-5.9.0/lib/minitest.rb:62:in `block in autorun'
```

**Comment by zenspider** [comment]
I need a repro. You mixing anything into minitest? Plugins and the like?

**Comment by plynchnlm** [comment]
I don't find any references to minitest in my Rails app.  It looks like ActiveSupport uses it, and my tests must use it indirectly, but I don't directly reference it.   Also, ruby-prof, rails-perftest, and timecop (gems I am using) use it.  Timecop adds some private methods to Minitest::Unit::TestCase,  and Minitest::Test.

It seems to have something to do with my perftest, because when I remove that test the problem does not occur, yet when I run that test by itself it passes without problems.  This makes it difficult to provide a reproducible test case.

I was hoping that since the fix (or work-around) only affects one line, you might just go ahead and make that change if it doesn't seem likely to cause other problems.  It looks innocuous enough.

**Comment by zenspider** [comment]
Sorry. But I don't blindly apply patches without understanding the root cause. I need a reproduction or some better understanding other than a stack trace. It doesn't even mention rails so I'm not sure how I should have inferred that.

**Comment by zenspider** [comment]
Also, I have no idea what you're referring to when you say "perftest". That isn't something that minitest provides (by name, at least)

**Comment by plynchnlm** [comment]
I was referring to a test using the "rails-perftest" gem I mentioned.  I can understand your interest in a reproducible test case, but I was hoping you might agree that there isn't a good reason for 481 to execute when result.time is not defined.

```
481       io.print "%s#%s = %.2f s = " % [result.class, result.name, result.time] if
482         options[:verbose] and result.time
```

I don't know why result.time was not defined, and I'm not sure it is worth caring too much why-- it happened.  My view is that if there is a hole people can fall into, it is less important to find out why they were on that path than to put up a small guard rail.  I am just maintaining an old Rails system for a project that is no longer my focus, and I don't have the time we might like to investigate issues involving gems I am not familiar with, especially since I already have a patch that has gotten me past this point.  This is just one of many problems I've run into in trying to move from Rails 4.1 to 4.2.

**Comment by nateberkopec** [comment]
> but I was hoping you might agree that there isn't a good reason for 481 to execute when result.time is not defined.

Where do you stop? What if `result.name` isn't defined? What about `result.class`? 

Of course, if you have a monkeypatch that works for you, that's great and you should go ahead and use that. But if `minitest` put up "just one small guard rail" for every time this happened for anyone, it would no longer be `minitest` - it would be `maximumtest`!

**Comment by zenspider** [comment]
No, you never mentioned rails-perftest. You didn't even originally mention rails. I originally asked you for a repro and any extensions you might be using with minitest... You'd think this might come up. Blindly applying patches from someone who seems utterly unwilling to even describe their scenario, let alone give you a reproduction is not only against how I work, it is against how many (hopefully most) developers work. This could have gone much better if you'd been more cooperative and answered questions up front or, better, supplied needed information initially. 

https://www.google.com/search?q=how+to+file+a+good+bug+report has some useful hits on the first page. It might benefit you to check some of them out.

I didn't know about this gem until 2 days after you filed the bug, and now it is on me to dig into their code to see if I can find a workable repro with as little information as I currently have. Unfortunately I'm travelling later today, so this is nowtogether on be put on the back burner until I have time to deal with it (like I did the last two days). Again, please reconsider your strategy on filing bugs. We're trying to work together here.

**Comment by waldyr** [comment]
Sorry for bleding in but I've investigated this issue and since we can trust on this [ensure](https://github.com/seattlerb/minitest/blob/596f9bc007416629df98a0ea8069ce339c46ca5a/lib/minitest/test.rb#L252-L258) there's two possible causes besides monkey patching: Either a newly created object from Test class or `#marshal_load` a wrong array. Check the following snippet.

```
pr = Minitest::ProgressReporter.new($stdout, verbose: true)
pr.record(Minitest::Test.new('a-test'))

t = Minitest::Test.new('a-test')
t.marshal_load([])
pr.record(t)
```

Also there's no need to enhance the conditional on the guard clause a simple `result.time.to_f` can solve this issue.

**Comment by plynchnlm** [comment]
@zenspider- If you search for "rails-perftest", you'll see I did mention it in my initial reply to your questions.  Anyway, I appreciate the fact that you are still thinking about this issue, back burner or not.
I don't think the issue is urgent.

**Comment by zenspider** [comment]
This seems like a non-issue given that it is now 3+ years old and no response. Closing.
