### ISSUE TITLE
Get total number of tests that will be run

### ISSUE THREAD

**Issue by cmckni3** [seattlerb/minitest#629]
I need to get the total number of tests that will from within my plugin's start method. Is there any way to accomplish this?

**Comment by zenspider** [comment]
for a progress % or something? I have to run, but lemme think about it. But look at minitest-reporters for hints. I think they have something.

**Comment by cmckni3** [comment]
I'm using the total number of tests to figure out how many rows and dots per row. It makes a tree starting with 1 dots, 2 dots, and so on.

**Comment by cmckni3** [comment]
Thanks for the suggestion, @zenspider. I may have found the method I needed.

**Comment by cmckni3** [comment]
Pull the `total_count` method from [minitest-reporters](https://github.com/kern/minitest-reporters/blob/981a146a8a107b4b2a9a81e5035ff4f35332b167/lib/minitest/minitest_reporter_plugin.rb#L35). Thanks

**Comment by zenspider** [comment]
Looks like I should refactor my run class method. It now has negative exclusions so you're missing that part. What you have is good enough for now tho.

**Comment by cmckni3** [comment]
Would you consider adding a method to get the total number of tests?
