### ISSUE TITLE
Little improvement on the known extensions list

### ISSUE THREAD

**Issue by amiralles** [seattlerb/minitest#632]
Hi guys, I was looking for plugins at the known extensions list and I noticed that the extension name is not a link, just plain text. Wouldn't be better add a link that points to the extension repo?
I'm suggesting this because is a small improvement and I can do it myself if you want.
Thanks.

**Comment by sshaw** [comment]
> Wouldn't be better add a link that points to the extension repo

I was thinking the same thing.

**Comment by utilum** [comment]
See #547.
