### ISSUE TITLE
Files and describe blocks are shuffled in random order regardless of `test_order` setting

### ISSUE THREAD

**Issue by chrisnicola** [seattlerb/minitest#635]
So I managed to track down the core problem with tests being run out of order even with `:sorted` or `:alpha` set. That is that regardless of that setting the runables are being shuffled. I believe the culprit line is here:

https://github.com/seattlerb/minitest/blob/596f9bc007416629df98a0ea8069ce339c46ca5a/lib/minitest.rb#L150

A simple Rails app that I was using to narrow down my problem and reproduces the behavior is available here: https://github.com/chrisnicola/minitest_testing

**Comment by nateberkopec** [comment]
Agreed that if set to :sorted, Minitest should *not* shuffle the test class order.

**Comment by tenderlove** [comment]
> Agreed that if set to :sorted, Minitest should not shuffle the test class order.

I don't agree with this.  You set "sorted" on a per-class basis.  Having a setting in one class impact the whole suite seems counter intuitive to me.  I'd rather see a global "don't shuffle my classes" setting so that you can tweak class vs method shuffling.

**Comment by nateberkopec** [comment]
> You set "sorted" on a per-class basis.

Whoops, yeah I wasn't reading `Test` very closely. But speaking from a user's perspective, I think a user that has order-dependent tests and does `Minitest::Test.i_suck_and_my_tests_are_order_dependent!` expects deterministic test output. Maybe that method should also stop class shuffling, since it's already a "global-ish" method. 

[Previous discussion of this issue here](https://github.com/seattlerb/minitest/pull/550).

**Comment by chrisnicola** [comment]
Personally, I think a method named `i_suck_and_my_tests_are_order_dependent!` is a bad way to handle this altogether, but that is just me. My tests are not order dependent and I can't remember the last time I had a problem like that in my test suite. I don't believe that I suck nor does anyone else on my team, so there is basically zero chance of me checking in a line of code like that into our project.

Moving on...

I do partly agree with @tenderlove's thoughts, which is that it feels odd using `Minitest::Test.test_order` in the `Minitest` module. That said it is just a class method and Rails is using the same setting. It may make sense to have a `Minitest.suite_order` setting though as well as allowing both of these to by supplied/overridden via options arguments in the test runner command.

I do somewhat disagree with the idea that anyone would require that they can have the class/describe/files run in order while the containing tests are randomized or vice versa. I think either you want the tests run randomly, parallel or in the order you defined them in (personally, I don't think alphabetical makes much sense to me, but I can see why it might make sense as a setting).

One other thing. I do plan to keep the :random, or more precisely :parallel behaviour for the CI server where the test runner output ordering is not really important and I'm more than happy to keep that as a basic check against order dependent tests if that ever does occur.

Regardless I think at a minimum there is bug here, which is that you can't actually make the tests run in the order you want when the order is set to :sorted or :alpha.

**Comment by zenspider** [comment]
> Regardless I think at a minimum there is bug here, which is that you can't actually make the tests run in the order you want when the order is set to :sorted or :alpha.

I disagree with your reasoning here. You set the order at the class level and it is the class itself that it doing the running. How the classes are invoked is at an entirely different level.

**Comment by zenspider** [comment]
Yes, test classes are shuffled, and they will stay that way.

See #636 for the rest of my rationale on this issue.

I'm locking this down before this issue becomes as toxic as #636.
