### ISSUE TITLE
Alias `must_*` expectations as `to_*`

### ISSUE THREAD

**Issue by bryanp** [seattlerb/minitest#639]
The `must_*` syntax is awkward when paired with `expect`.

``` ruby
# reads great but will be deprecated
foo.must_be true

# also great
value(foo).must_be true

# not so great
expect(foo).must_be true

# better
expect(foo).to_be true
```

IMO if `expect` is supported, it should be paired with expectations that read well with it. Otherwise, remove `expect` and let people who prefer it rely on the minitest-spec-expect extension. Between these two options, I'd prefer that the following aliases were added:

```
#to_be
#to_be_close_to
#to_be_empty
#to_be_instance_of
#to_be_kind_of
#to_be_nil
#to_be_same_as
#to_be_silent
#to_be_within_delta
#to_be_within_epsilon
#to_equal
#to_include
#to_match
#to_output
#to_raise
#to_respond_to
#to_throw
#not_to_be
#not_to_be_close_to
#not_to_be_empty
#not_to_be_instance_of
#not_to_be_kind_of
#not_to_be_nil
#not_to_be_same_as
#not_to_be_within_delta
#not_to_be_within_epsilon
#not_to_equal
#not_to_include
#not_to_match
#not_to_respond_to
```

I see that this was (kind of) proposed in https://github.com/seattlerb/minitest/issues/365 but that was prior to `expect` being added to the api (Mar 10, 2015). And I didn't see this addressed in another issue, but apologies if I missed it.

Thoughts?

**Comment by zenspider** [comment]
What are your thoughts with something like `require "minitest/spec/extra"`?

The way they're currently written is to allow for a level of symmetry that allows for better visual pattern matching. Having positive / negative prefixes of different length breaks that (and it's REALLY hard to find antonyms of the same length!).

**Comment by bryanp** [comment]
Ah, interesting design decision. I hadn't noticed that before :-)

Your idea seems fine so long if that's how you enable both `expect` *and* `to_*` / `not_to_*`. It would be easy enough to explain that to enable the feature, just add the following code to your test helper:

```ruby
require "minitest/spec/expect"
```

**Comment by blowmage** [comment]
Sounds like a job for [minitest-shouldify](https://github.com/blowmage/minitest-shouldify)!

```ruby
require "minitest/shouldify"

MiniTest::Shouldify.register! "to", "to_not"
```

**Comment by bryanp** [comment]
Oh, and if anything actionable comes out of this issue I'll be more than happy to take it on!

**Comment by blowmage** [comment]
[`value(foo.bar).to_equal "bar"`](https://github.com/blowmage/minitest-shouldify/blob/58c9a8142c70a1c56f1f95333a1289c4bb9baa8e/test/test_to.rb#L56)

Minitest adds `expect` as an alias for `value`, so this could just as easily be written `expect(foo.bar).to_equal "bar"`.

**Comment by bryanp** [comment]
@blowmage I'd prefer this to work with no outside dependencies, but @zenspider knows best

**Comment by zenspider** [comment]
Please note that both `expect` and `value` are aliases for `_`... I actually prefer that one:

```ruby
_(foo.bar).must_equal "bar"
```

@blowmage should I close this and have a section in the FAQ about minitest-shouldify?

**Comment by blowmage** [comment]
Hah! I mostly wrote it to avoid bike shedding, and the README says, "This is a bad idea". That said, there isn't anything technically wrong with what it does AFAIK, but I don't know if it should be elevated to official guidance. 

I  wrote shouldify back when rspec was still using `should` and `should_not`. If you wanted to throw users at it I'd be tempted to give it a better name and API. Something not to :trollface:-y.

**Comment by bryanp** [comment]
What I'm really proposing here is an API that makes sense out of the box. IMO the `expect` alias is out of place. So, remove it or define more aliases that make it usable.

For people considering minitest, this seems like pretty user-friendly instruction:

> If you want expect syntax, use `minitest-spec-expect`.

Right now, expectations appear to be supported but won't live up to expectations (ha) unless you further extend the library with `minitest-spec-expect` or `minitest-shouldify`. I understand if that is okay with the maintainers, just wanted to make sure this issue was clear 🙂

**Comment by blowmage** [comment]
> What I'm really proposing here is an API that makes sense out of the box.

I think it does make sense. For example, here is expect when testing a block. 

```ruby
expect { 1/0 }.must_raise ZeroDivisionError
```

And here is expect with a more traditional example. 

```ruby
expect { hello }.must_equal "world!"
```

Do those not make sense? You seem to be under the assumption that any testing DSL must conform to whatever RSpec does. There are several places where Minitest diverges from RSpec. Why is this so different?

**Comment by zenspider** [comment]
@blowmage ... I'm gonna let you handle this. I don't have a vested interest either way.

**Comment by blowmage** [comment]
I see no difference in this request and the requests to change from `must_` and `wont_` to `should_` and `should_not_`. Shouldify and minitest-matchers exist if you want the customize the spec DSL and make it more like RSpec's DSL.

**Comment by bryanp** [comment]
Fair point, I understand your position on avoiding extensions to the MiniTest DSL. What about the other side of the proposal: removing `expect` since it is itself an extension of the MiniTest DSL?

**Comment by blowmage** [comment]
I haven't heard an argument worthy of breaking existing tests. I suppose perhaps `expect` could be removed in Minitest 6? But I like `expect`, and I think there are times that it makes semantic sense. I don't see the rationale for making a backwards incompatible, breaking change.

**Comment by zenspider** [comment]
> On Aug 29, 2016, at 16:44, Mike Moore <notifications@github.com> wrote:
> 
> I haven't heard an argument worthy of breaking existing tests. I suppose perhaps expect could be removed in Minitest 6? But I like expect, and I think there are times that it makes semantic sense. I don't see the rationale for making a backwards incompatible, breaking change. 

I'm not sure I understand where this is going (if not in circles)... If the basis of the argument is "I don't like 'must'", then why should we care? This sounds a lot like subjective personal preference and we've shown workarounds to get verbage you like.

If it isn't that, can you provide a _clear_ and _concise_ problem description?

**Comment by blowmage** [comment]
Circles, definitely circles.

I think this is the clearest statement @bryanp has made about this:

> What I'm really proposing here is an API that makes sense out of the box. IMO the `expect` alias is out of place. So, remove it or define more aliases that make it usable.

So yes, this is driven by personal preference. But you may want to also consider the [minitest-spec-expect](https://github.com/davejachimiak/minitest-spec-expect) gem pre-dates the addition of `expect`, and I suspect that this is causing some confusion for users of that extension? ¯\\\_(ツ)\_/¯

**Comment by zenspider** [comment]
> What I'm really proposing here is an API that makes sense [**to me**] out of the box. IMO the `expect` alias is out of place. So, remove it or define more aliases that make it usable.

Yeah. This seems subjective. Unfortunately, there's _always_ someone who objects to your method name choices. `refute` got flack too. Meh.

From my blog post on this subject:

http://www.zenspider.com/ruby/2015/04/great-expectations.html

> The method _ is also aliased to value if you prefer verbier tests. It is also aliased to expect, to make transitioning easier, but \<bikeshed\>1I really dislike that name\</bikeshed\> because it is non-descriptive. value is much better, and imo, _ is even better because it gets out of your way and lets you focus on the actual meat of the test.

> 1: <bikeshed> means: don’t argue with me about it. I don’t care to argue about it.

IOW... If this is the correct assessment, I don't care at this point. This is just arguing semantics and subjective preference. We all have better things to spend our time on. If you feel strongly about it, perhaps a new gem is in order (to be clear: from you, @bryanp)? I'm happy to help you get that up and running and published.

@bryanp if you happen to make it to nerd party tonight or our monthly next week, I'm happy to talk to you about it. I might still be missing something that isn't conveying well over text.

**Comment by bryanp** [comment]
Yeah, I am really not trying to argue semantics here; but maybe I am without realizing it. There's an aspect of what I'm proposing that I don't think is coming across well. Text might be a poor medium for this discussion. I'll be at the monthly next week and will talk out loud with @zenspider 🙂

**Comment by zenspider** [comment]
Cool. Looking forward to seeing you then.

**Comment by zenspider** [comment]
What's the status of this?

**Comment by bryanp** [comment]
I think this can be closed based on our conversation. Still want to contribute some docs, but that will happen separately if / when I have the time.

**Comment by zenspider** [comment]
kk. thanks!
