### ISSUE TITLE
Tests run more than once when subclassing test class

### ISSUE THREAD

**Issue by Florent2** [seattlerb/minitest#663]
When using subclasses to organize tests, tests that are not in subclasses are run more than once.

For instance running this test file

```ruby
# test.rb
require "minitest/autorun"

class MyTest < Minitest::Test

  class MySubTest < MyTest
    def test_subtest
      puts "subtest"
    end
  end

  def test_root
    puts "test"
  end
end
```

returns:

```bash
$ ruby test.rb
Run options: --seed 57588

# Running:

test
.subtest
.test
.

Finished in 0.001438s, 2086.7664 runs/s, 0.0000 assertions/s.

3 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by zenspider** [comment]
That is absolutely the intent. It is just ruby. Methods are inherited.

If you want a way around this (tho, imho, you shouldn't), you can use minitest/spec, which jumps through hoops to disable normal class inheritance.

**Comment by Florent2** [comment]
Got it, makes sense, thanks for your quick reply!
