### ISSUE TITLE
Bug: Order of assert_output and assert_raises matters

### ISSUE THREAD

**Issue by rrama** [seattlerb/minitest#673]
The order in which `assert_output` and `assert_raises` are specified makes a difference to whether the test will pass or fail. The same thing will happen when using `assert_silent` instead of `assert_output`.
It's as if `assert_output` is ignored when inside of an `assert_raises` block, but if the blocks are reversed the desired checking is achieved.

Example code:
```ruby
class TestClass < Minitest::Test
  
  # assert_silent after assert_raises.
  # This test passes when it shouldn't.
  def test_broken()
    assert_raises(IOError) do
      assert_silent() do
        puts "Noise!" # Clearly the output isn't silent, but the test still passes.
        raise IOError
      end
    end
  end
  
  # assert_silent before assert_raises.
  # This test fails, like it should.
  def test_working()
    assert_silent() do
      assert_raises(IOError) do
        puts "Noise!" # A puts when we're asserting silence fails the test in this scenario.
        raise IOError
      end
    end
  end

end
```

Ruby versions: `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`, `ruby 2.3.0p0 (2015-12-25) [x64-mingw32]` and `ruby 2.3.3p222 (2016-11-21) [x86_64-linux]`
Minitest versions: Using the Minitest version that comes shipped with the versions of Ruby above.

**Comment by zenspider** [comment]
Yes. True. Minitest is implemented in ruby and exceptions are jumps in ruby. That's how assert is implemented, using raise.

https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L139

**Comment by rrama** [comment]
I realised the reason would be because the IOError would cause immediate returns until it is caught (rescued) by the `assert_raises`, thus skipping the output assertion checks by the `assert_output`. IMO the assert_output yield should be should be surrounded in a begin/rescue to ensure that the output is still checked before re-raising any exceptions from the yield.

**Comment by zenspider** [comment]
Where should a `begin`/`rescue` wrapper go?

```ruby
    def assert_output stdout = nil, stderr = nil
      out, err = capture_io do
        yield                                                                    # Around here? Then what?
      end

      err_msg = Regexp === stderr ? :assert_match : :assert_equal if stderr
      out_msg = Regexp === stdout ? :assert_match : :assert_equal if stdout

      y = send err_msg, stderr, err, "In stderr" if err_msg
      x = send out_msg, stdout, out, "In stdout" if out_msg

      (!stdout || x) && (!stderr || y)
    end
```

And what should it do if an exception _**is**_ raised? What if raising the exception causes the output to be wrong? Would it make sense to report on the output being wrong if you had an unexpected exception? Which should be reported? Both? How?

**Comment by rrama** [comment]
MRW I come along to someone else's code base thinking a change will be easy to implement http://i.imgur.com/vOkx8zr.gif
Unless Ruby has some magical way to raise multiple exceptions at once then you're right it is best to just leave it how it is.
Hopefully, any other newbies like me who runs into this, will find this thread and spare staring at their code for an hour wondering what's up.
