### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by Paxa** [seattlerb/minitest#674]
Link in README is not really working (example http://docs.seattlerb.org/minitest/Minitest/Test.html)

Why not use rdoc.info? IMO it's more beautiful (example http://www.rubydoc.info/gems/minitest/Minitest/Test)

**Comment by utilum** [comment]
Works on this connection.

**Comment by Paxa** [comment]
I see it like this:
![screen shot 2017-01-05 at 11 42 33 am](https://cloud.githubusercontent.com/assets/26019/21668370/20dda0c8-d33c-11e6-9b94-83dc426a6054.png)

@utilum Do you see it same?
@zenspider Is it expected to be empty?

**Comment by utilum** [comment]
@Paxa I do see the same. What do you expect?

**Comment by Paxa** [comment]
I expect to see at least methods for `Minitest::Test` that defined here https://github.com/seattlerb/minitest/blob/master/lib/minitest/test.rb

**Comment by zenspider** [comment]
Ah. I thought you meant that there was a 404 somewhere... So this is a bug in rdoc generation? Joy...

**Comment by zenspider** [comment]
And for the record... Yard sucks just as much... Notice all the nodoc duties, for example.

**Comment by Paxa** [comment]
Right, maintainer of yard seems have a strong mind about `:nodoc:`.
Probably it's a bug of rdoc, I found out it happen because `#:nodoc:` in:
```ruby
class << self; attr_accessor :io_lock; end # :nodoc:
```
https://github.com/seattlerb/minitest/blob/3e982c9f602c05e70fc6efaaec485f98efe02045/lib/minitest/test.rb#L16

Working well with stopdoc & startdoc:
```ruby
# :stopdoc:
class << self; attr_accessor :io_lock; end
self.io_lock = Mutex.new
# :startdoc:
```

---

Btw, have you seen https://github.com/rdoc/hanna-nouveau? IMO it generates little prettier docs 
![screen shot 2017-01-05 at 9 27 34 pm](https://cloud.githubusercontent.com/assets/26019/21682137/ddd9cdf4-d38d-11e6-8edd-4a19f9853198.png)

**Comment by zenspider** [comment]
@hsbt can you take a look?

**Comment by zenspider** [comment]
This seems fixed. Closing.
