### ISSUE TITLE
Mandatory cleanup hooks

### ISSUE THREAD

**Issue by lowjoel** [seattlerb/minitest#677]
Hey there. When defining `MiniTest::Test` classes, there is an option to specify `setup` and `teardown` methods. However, the teardown methods are not called in the event of a Ctrl-C. What would be the best way to clean up resources that have been allocated in `setup`?

Offhand, I can think of:
1. Exclude Interrupt from the list of PASSTHROUGH_EXCEPTIONS. This makes the handling of exceptions more complex (manual cleanup and propagation?)
2. Run the teardown methods in an `ensure` block. This can change behaviour of the test library.
3. Define a new hook to be called when exiting a test, regardless of path (kind of like a test-based ensure block)

Thoughts?

**Comment by zenspider** [comment]
`Interrupt` is there for a reason. The second I support your case, someone else will file an issue saying I'm not honoring `Interrupt`.

You can use `Minitest.after_run { ... }` if you absolutely need this type of handling or you can override `Minitest::Test.run` with `super` & your own `ensure`. I don't feel that this is an edge case that minitest should handle normally.

**Comment by lowjoel** [comment]
Ah yes, overriding `Minitest::Test.run` seems like a good idea. I understand that this is a potentially nasty thing to ask for -- I was just wondering if there was a better approach than using `at_exit` or `Minitest.after_run`.

Thanks!
