### ISSUE TITLE
assert_equal does not work with MiniTest::Mock

### ISSUE THREAD

**Issue by voxik** [seattlerb/minitest#679]
Commit 89afe99593a0a3480dfa breaks some tests:

~~~
$ ruby - << EOF
> gem 'minitest', '5.10.1'
> require 'minitest/autorun'
> require 'minitest/mock'
> 
> class TestMiniTestMock < Minitest::Test
>   def test_mock
>     t = MiniTest::Mock.new
>     def t.==(other); object_id == other.object_id; end
> 
>     assert_equal t, t
>   end
> end
> 
> EOF
Run options: --seed 35903

# Running:

E

Finished in 0.000658s, 1519.7662 runs/s, 1519.7662 assertions/s.

  1) Error:
TestMiniTestMock#test_mock:
NoMethodError: unmocked method :nil?, expected one of []
    -:10:in `test_mock'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
~~~

While it used to work with minitest 5.8.5:

~~~
$ ruby - << EOF
> gem 'minitest', '5.8.5'
> require 'minitest/autorun'
> require 'minitest/mock'
> 
> class TestMiniTestMock < Minitest::Test
>   def test_mock
>     t = MiniTest::Mock.new
>     def t.==(other); object_id == other.object_id; end
> 
>     assert_equal t, t
>   end
> end
> 
> EOF
Run options: --seed 24257

# Running:

.

Finished in 0.000678s, 1475.6356 runs/s, 1475.6356 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
~~~

I am not sure the warning introduced by the commit is worth of breaking backward compatibility. But may be this is just wrong use of Mock object?

BTW the original test case which triggered this issue is here [[1]]

[1]: https://github.com/fog/fog-core/blob/master/spec/service_spec.rb#L174

**Comment by GregMacdonald** [comment]
The relevant change is pretty annoying. Previously, assert_equal answered the question of whether two objects are equal. The change says that in all cases a nil value is illegal and tests must now resolve ( (!a && !b) || a == b) - which means one elegant check became a blob of distracting mess.

Effectively, assert_equal was changed to assert_equal_but_not_nil. Where's the tautology in that? It would make sense to add an assert method for the special condition, but why break an existing contract?

As an example use case, let's say you have a custom cloning\deriving mechanism that copies selected properties. You can't compare the objects, you must compare individual properties. For some properties, it doesn't matter if they are nil or not, as long as those properties in the derived object are equal.  Now you write a good test and then generate a bunch of objects to run through that test.  Well, maybe not. Arrgh.

**Comment by zenspider** [comment]
@GregMacdonald maybe you meant to put this comment on #626?

**Comment by zenspider** [comment]
@voxik I'm not entirely sure I understand the use case. You're not actually using the Mock as intended. Here's your real code:

```ruby
  describe "when config object can configure the service itself" do
    it "ignores the global and its values" do
      @config = MiniTest::Mock.new
      def @config.config_service?;  true; end
      def @config.nil?; false; end
      def @config.==(other); object_id == other.object_id; end

      unexpected_usage = lambda { raise "Accessing global!" }
      Fog.stub :credentials, unexpected_usage do
        @service = TestService.new(@config)
        assert_equal @config, @service.options
      end
    end
  end
```

if you change from `Minitest::Mock.new` to `Object.new` then this should pass, no?

Basically, if you're not using `expect` and `verify`, then you don't need a Mock instance.

If I'm not seeing the bigger picture tho... please let me know.

**Comment by zenspider** [comment]
I also just changed the call to `nil?` to `== nil`.
