### ISSUE TITLE
How to run multiple tests in a describe block?

### ISSUE THREAD

**Issue by pts-owentran** [seattlerb/minitest#682]
With rails test runner, you can run tests by specifying line number. Is there a way to run all the tests under a describe block if the line number of the describe is given?

```
class FoobarTest < ActiveSupport::TestCase
  describe 'related tests' do
    setup do
      # shared setup code
    end

    it 'does foo' do
    end

    it 'does bar' do
    end
  end

  test 'some other test' do
  end
end
```

Let's say the describe block starts on line 2. Is there a way to run the foo and bar tests by doing?

```
bin/rails test test/models/foobar_test.rb:2
```

Current work around is just giving bin/rails test multiple line numbers, but wonder if there's a easier/lazier way? Thanks!

**Comment by zenspider** [comment]
The rails test runner is provided by rails... You should ask them.

**Comment by pts-owentran** [comment]
Good point. Closing.
