### ISSUE TITLE
how do i build it from the sources here?

### ISSUE THREAD

**Issue by themaddoctor** [seattlerb/minitest#685]
How do I build it? there is now spec file in these sources.

No, I do NOT want to download a prepackaged thing.

**Comment by zenspider** [comment]
There is no building. But if you want to package the gem:

```
gem install hoe
rake gem
```

**Comment by zenspider** [comment]
No response here or on https://github.com/seattlerb/hoe/issues/80

Should I close?

**Comment by zenspider** [comment]
OP doesn't want to communicate. Closing.

**Comment by themaddoctor** [comment]
I didn't realize that a response was necessary. Thank you.


On 10/31/17, Ryan Davis <notifications@github.com> wrote:
> OP doesn't want to communicate. Closing.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/seattlerb/minitest/issues/685#issuecomment-340917035


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F
