### ISSUE TITLE
Running Minitest continuously

### ISSUE THREAD

**Issue by BackOrder** [seattlerb/minitest#688]
Hello, I would like to be able to run programmatically a series of tests multiple times / continuously but once `Minitest.run` is performed for the first time, it will subsequently not run tests anymore. Is there a way to reset Minitest programmatically or something?

**Comment by zenspider** [comment]
What are you actually trying to accomplish?

Can you show me what you've tried so far?

**Comment by BackOrder** [comment]
I have tried several things without success, including minitest-autotest and minitest-server. Not helping that Autotest/Minitest-server are not working on Windows because they require DRbUNIX instead of TCP based DRb. My ideal solution would however be in-memory tests and need to access reports programatically.

* Custom Minitest Reporter
* A Minitest unit test
* A dynamically defined class to test against
* Loop
  * Minitest.run
  * Check report
  * Modify instance methods if necessary

**Comment by zenspider** [comment]
Didn't answer that first question...

And please file an issue about running minitest-server on windows. I can't fix it if I don't know about it.

**Comment by BackOrder** [comment]
Doing something similar to [heckle](https://github.com/seattlerb/heckle) + continous integration on a system that is not supposed to be shut down. It would be preferable to do everything in memory, without any files, but if autotest would work on Windows, it would be an acceptable compromise. 

See minitest-server issue seattlerb/minitest-server#1

**Comment by zenspider** [comment]
```ruby
#!/usr/bin/env ruby -w

require "minitest/autorun"

module Minitest
  mc = class << self; self; end

  mc.send :alias_method, :old_run, :run

  def self.run args = []
    loop do
      old_run args
      sleep 1
    end
  end
end

class TestX < Minitest::Test
  def test_something
    assert true
  end
end
```

works for me... If you're doing something like heckle then you'd put some mutation steps in before the call to old_run and you'd check the result. See https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L108-L118 for how minitest runs things. You might prefer a different point to inject.

**Comment by BackOrder** [comment]
Your approach is working and a good starting point until I tried to `parallelize_me!`. Thereafter back to starting point where subsequent tests are not ran. Here is some code for you to play with.

```ruby
#!/usr/bin/env ruby -w

require "minitest/autorun"

module Minitest
   class Test
      parallelize_me!
   end
   
  mc = class << self; self; end

  mc.send :alias_method, :old_run, :run

  def self.run args = []
    loop do
      old_run args
      sleep 1
    end
  end
end

class OneFakeTest < Minitest::Test
   (1..100).each do |i|
      define_method("test_#{ i }") do
         (1..8000).reduce(:*)
         assert(true)
      end
   end
end
```

**Comment by zenspider** [comment]
Your code works for me. What are you seeing vs expecting?

**Comment by BackOrder** [comment]
> Your code works for me. What are you seeing vs expecting?

It seems to behave properly on FreeBSD. This might be a problem on Windows. On Windows, the first iteration (loop) runs the tests properly but the subsequent iterations will not run the tests.

**Comment by zenspider** [comment]
I can't test against windows... but I can't fathom a reason why that'd be the case. Minitest is pretty OS agnostic given that it barely knows what a file is, doesn't make system calls, doesn't open sockets, etc... It's pretty much just pure ruby... Thread.new is the only thing that might be causing problems, but I can't guess why.

What actually happens on the second iteration? Can you try to dig down into the problem?

**Comment by MSP-Greg** [comment]
@BackOrder

I just tried your code with trunk (`ruby 2.5.0dev (2017-12-24 trunk 61430) [x64-mingw32]`), and it's running fine.  I've got several ruby versions loaded, what version of ruby are you using?  Minitest extensions?

**Comment by zenspider** [comment]
No response. Closing.
