### ISSUE TITLE
Verbose output is missing spec names when run in parallel

### ISSUE THREAD

**Issue by chanks** [seattlerb/minitest#690]
Reproduction script:
```ruby
require 'minitest/autorun'

puts Minitest::VERSION

describe "a thing" do
  parallelize_me!

  it "should blah" do
  end
end
```

Output:
```
$ ruby minitest_bug.rb -v
5.10.1
Run options: -v --seed 51919

# Running:

0.00 s = .

Finished in 0.000504s, 1984.0364 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

The expected output, and what I see if I comment out the `parallelize_me!`:

```
$ ruby minitest_bug.rb -v
5.10.1
Run options: -v --seed 17059

# Running:

a thing#test_0001_should blah = 0.00 s = .

Finished in 0.000588s, 1699.3480 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

I noticed this in a project after I updated it from 5.9.1 to 5.10.2 - I believe the bug was introduced somewhere between those versions.

Thanks!

**Comment by zenspider** [comment]
fascinating...

**Comment by zenspider** [comment]
Fixed. Thanks for the report!

**Comment by chanks** [comment]
Thank you!

**Comment by chanks** [comment]
This is a bit delayed, but can you cut a new release? This would help me track down a test failure, and since there's no gemspec I can't just point Bundler at the git repository.

Thanks again!
