### ISSUE TITLE
Stubs not threadsafe

### ISSUE THREAD

**Issue by nateberkopec** [seattlerb/minitest#691]
Maybe I'm the only person crazy (stupid?) enough to want to use stubs with parallel tests, but would it be possible to make stubs thread-local? Or just throw a mutex around them?

**Comment by zenspider** [comment]
I have no clue how you'd do that in a way that still works for parallel tests (as in, they actually stay parallel).

Do you have an idea in mind?

And yes, you're crazy, but probably not for (just) this reason. 😛

**Comment by nateberkopec** [comment]
No, don't really have an idea. My only idea was a mutex so that only one test gets to stub MyClass.method at once.

**Comment by zenspider** [comment]
Well... take a whack at it? It's block oriented so you know the exact lifespan. And you know the class and method, so you can create a mutex directly on the class. SHOULD work...

Lemme know.

**Comment by nateberkopec** [comment]
Alright, whack incoming.

**Comment by zenspider** [comment]
HAH!

**Comment by nateberkopec** [comment]
Okay, it's so stupid it works:

```ruby
def stub name, val_or_callable, *block_args
    new_name = "__minitest_stub__#{name}"

    metaclass = class << self; self; end
    
    while respond_to? new_name
      # wait
    end
    # ...
end
```

Tell me why this won't work.

**Comment by nateberkopec** [comment]
Yeah, adding a sleep makes my tests run a little faster:

```ruby
while respond_to? new_name
  sleep(0.1)
end
```

Probably just because it avoids checking on every other CPU cycle or whatever.

**Comment by nateberkopec** [comment]
Matthew pointed out there's a race between the while check and aliasing the current method to the old one. His idea: https://twitter.com/_matthewd/status/863073569600700417

**Comment by matthewd** [comment]
That doesn't help with `stub(:foo); Thread.new { foo }`, of course. You could use a Thread*Group* registry to get past that... which only leaves you open to problems if the CUT uses ThreadGroups itself.

Solving *that* would require a tracepoint that tracks thread parentage. I really wish `Thread#parent` was just a built-in always-populated thing.

**Comment by zenspider** [comment]
warning: I suck at thread safe thinking... but I think @matthewd is going off the deep-end wrt ThreadGroups.

First, `stub` is always block-oriented, so that last scenario doesn't make sense.

Second, rather than a `while` loop (always dangerous is this context), I think what is probably needed is a mutex registry created for stubbing, synchronizing around the aliasing+yield, then this should work.

That said, I don't really see the point in parallel tests + synchronized method stubs. (other than extra test pain? I guess)

**Comment by nateberkopec** [comment]
> That said, I don't really see the point in parallel tests + synchronized method stubs. (other than extra test pain? I guess)

Yeah I mean that's the whole reason I do parallel tests :)

Mutex registry was my next thought, but I had no idea how to set that up. You need a mutex for each class/method combination being stubbed, and then another mutex for the registry itself, right?

**Comment by matthewd** [comment]
> First, stub is always block-oriented, so that last scenario doesn't make sense.

Okay: `stub(:foo, 42) { Thread.new { foo }.join }`, maybe?

The point is that the `foo` call in the thread [spawned by the code under test, in a less collapsed scenario] "expects" to hit the stub.

---

A mutex inside `stub`, suitably wielded, is sufficient to prevent two conflicting stubbings -- but that doesn't help you if one test is stubbing the method while another calls it expecting the real/original method to respond.

At that point, you either need a registry of suitable reactions per calling thread, or for the stubbing to stop the world for any parallel tests.

**Comment by nateberkopec** [comment]
I think we can leave the "new thread inside a test" scenario aside for now. Just getting it working in the regular/usual case would be a big improvement.

> A mutex inside stub, suitably wielded, is sufficient to prevent two conflicting stubbings -- but that doesn't help you if one test is stubbing the method while another calls it expecting the real/original method to respond.

Not if we override `send`! 😆 

At this point, maybe I should just not parallelize test classes with stubs 😬

**Comment by zenspider** [comment]
Chances are, if a test is stubbing a method then it cares about the result. If another test does not stub that same method then it does not and should be able to pass regardless of its result or side-effects. Otherwise, it too should stub.

**Comment by nateberkopec** [comment]
> Chances are, if a test is stubbing a method then it cares about the result. If another test does not stub that same method then it does not and should be able to pass regardless of its result or side-effects. Otherwise, it too should stub.

That happens to be true for my particular case. However, I could see a situation where somebody stubs a method and expects, say, an exception to be raised as a result. Even so, *anything* is better than the current behavior, which doesn't work for *any* case.

**Comment by matthewd** [comment]
> If another test does not stub that same method then it does not and should be able to pass regardless of its result or side-effects.

I'm not so convinced... while that seems fair for something like `Time.now`, if one test stubs `File.open` or `Process.spawn`, every other test is now obliged to either stub them back to reality, or pass regardless of what fake file handle / never-executed-process they might get? :confused:

That would seem to imply there's no point using blocks on stubs anyway: if all tests are obliged to pass with any other test's [non-conflicting] stubs in place, it should never be necessary to "unstub" when a test finishes. And that definitely doesn't sound right to me.

---

To be clear, the ThreadGroup etc stuff is indeed over-engineering -- just being explicit about the limitations (and what it would take to narrow them) of my original proposal, which remains my recommendation.

But of course, I'm just passing through.. tbh, I'm not sure I even knew `stub` was a thing, though we are using it in Rails. And we don't currently have any truly thread-parallel tests... though I guess we would need this if we wanted to change that.

**Comment by nateberkopec** [comment]
For anyone coming here wondering "what should I do if I want to use stubs and parallel execution?", I just ended up creating two test classes:

```ruby
class MyGem::ThreadUnsafeTest < Minitest::Test
end

class MyGem::Test < Raven::MyGem::ThreadUnsafeTest
  parallelize_me!
end
```

**Comment by zenspider** [comment]
@nateberkopec should this be closed?

**Comment by cout** [comment]
As an alternative to making stubs threadsafe, we do this with Minitest 4 (go ahead and laugh) to run tests in separate _processes_ instead of separate threads.  It will probably work in Minitest 5, but I've never tried.

```ruby
  def self.tests_in_separate_processes!
    define_method(:run) do |runner|
      r, w = UNIXSocket.pair
      pid = fork do
        begin
          runner = ForkingRunner.new(runner)
          res = super(runner)
          recorded = runner.recorded
          puked = runner.puked
        ensure
          w.write(Marshal.dump([res, $!, recorded, puked]))
          exit!
        end 
      end 
      res, exc, recorded, puked = Marshal.load(r)
      Process.waitpid(pid)
      raise exc if exc 
      recorded.each { |s, *rest| runner.record(ObjectSpace._id2ref(s), *rest) }
      puked.each { |k, *rest| runner.puke(ObjectSpace._id2ref(k), *rest) }
      return res 
    end 
  end 

  class ForkingRunner
    attr_reader :recorded
    attr_reader :puked

    def initialize(runner)
      @runner = runner
      @recorded = [ ] 
      @puked = [ ] 
    end 

    def record(suite, method, assertions, time, error)
      @recorded << [ suite.object_id, method, assertions, time, error ]
      return @runner.record(suite, method, assertions, time, error)
    end 

    def puke(klass, meth, e)
      @puked << [ klass.object_id, meth, e ] 
      return @runner.puke(klass, meth, e)
    end 

    def method_missing(*args)
      @runner.send(*args)
    end 
  end 
```

**Comment by zenspider** [comment]
This is a valid strategy. It is even easier in MT5 (see IsolationTest (iirc) in rails). We’ve pushed to ensure that things are Marshalable. MT6 will push even further on this.

**Comment by nateberkopec** [comment]
I'll close this. I've just changed my workflow to use two test classes in the same file, one for parallelizable tests and one for tests that need global stubs.
