### ISSUE TITLE
Feature Request: after suite/test/case

### ISSUE THREAD

**Issue by skladd** [seattlerb/minitest#700]
#192 addressed this already, and there are some possibilities to implement before suite/case, but I am missing a way to run code once after finishing all tests in a case and before running other cases.

If I use the teardown method, I have to rerun the (quite heavy) setup code for every test in the case.
after_run is executed after all tests in all cases have finished, i.e. too late.

**Comment by zenspider** [comment]
Like this?

```ruby
class MyHeavyTest < Minitest::Test
  def self.run(*args)
    # do stuff before suite
    super
    # do stuff after suite
  end
end
```

**Comment by zenspider** [comment]
No response. Closing.
