### ISSUE TITLE
Missing second call against a mock gives very odd error message

### ISSUE THREAD

**Issue by andy-twosticks** [seattlerb/minitest#703]
I've just spent two hours trying to work out what an error message from a test means. Apparently Minitest is correctly detecting that a method is only called once when it should be called twice. But instead of telling me that, it gives me a very odd error, like this: `expected foo("lalala2") => nil, got [foo("lalala1") => nil]`

I can duplicate the problem trivially. Here's some code:

```
class ThingOne
  def initialize(thingtwo);  @thingtwo = thingtwo;  end

  def do_it(param)
    @thingtwo.foo(param + "1")
  end
end
```

Here's a test class (note that we expect `@thingtwo.foo` to be called twice, so this should fail):

```
require "minitest/autorun"
require_relative "code"

class TestCode < Minitest::Test

  def setup
    @mock  = Minitest::Mock.new
    @thing = ThingOne.new(@mock)
  end

  def test_things
    @thing.do_it("lalala")
    @mock.expect :foo, nil, ["lalala1"]
    @mock.expect :foo, nil, ["lalala2"]
    @mock.verify
  end

end
```

Here's the actual output of the test:

```
(1) andy@kaylee[~/andy/coding/minitest_oops]%: ruby -Ilib:test test.rb
Run options: --seed 10546

# Running:

E

Finished in 0.001579s, 633.2906 runs/s, 0.0000 assertions/s.

  1) Error:
TestCode#test_things:
MockExpectationError: expected foo("lalala2") => nil, got [foo("lalala1") => nil]
    test.rb:17:in `test_things'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by srbaker** [comment]
Thanks for pointing this out, that error message is terrible. I'm looking into making it better.

**Comment by srbaker** [comment]
I'm not sure if this is better or not. In the original, it says "I expected this thing, but got these things instead". In this one it just says "I didn't get the thing I expected."

**Comment by andy-twosticks** [comment]
I think it would be a big win if it simply made clear that a test had failed.  Most of my problem was that it looked like an exception had occurred in Minitest, making me think that either I had broken basic syntax in the test file, or that I had found a bug in Minitest (which was arguably the case, but).

On the other hand, If you are looking for a target to aim at in terms of what Minitest should *ideally* do, I would recommend seeing the output of ... sorry about this ... Mocha.

From memory (right now I'm 30 miles away from where I can run the project that spawned this problem) it says something like "I expected x to be called two times, but it was called only once".  You don't get better than that. Rspec is worse than that...

**Comment by srbaker** [comment]
Heya, I'm currently trying to clean up a fix that basically said "We expected these things, but got those instead." In my playing with it, I found that when dealing with multiple expectations on an object, it's best to just lay them all out: "I expected x,y,z but got x,z".

Will get to this during the week.

**Comment by zenspider** [comment]
ping

**Comment by zenspider** [comment]
No response from OP _or_ the maintainer... Not sure what to do... but closing.
