### ISSUE TITLE
Not issue but feature request: 'softassert'

### ISSUE THREAD

**Issue by goodzzj** [seattlerb/minitest#706]
Are there any assertion methods same as SoftAssert in TestNG ? 'softassert' will log error messages but not throw assertion exception, 'assertall' will summarize the error log and throw assertion exception if there are errors.
This function can be used to some cases contains several assert points, but don't want to interrupt the case execution until the end of the case. if use 'assert', the case will be stopped when there is any one 'assert' fail during the case run.

I am QA in EMC, in my project, I just need this type of assert function. I have already created such functions. If you think is useful for the 'minitest' project, I can contribute the code.

**Comment by zenspider** [comment]
No, I don't know of any such functionality for minitest. You're welcome to package this up as an add-on gem, but I don't think it is a fit for minitest directly. Thank you.
