### ISSUE TITLE
Feature Request for MT6: Remove plugin auto-loading

### ISSUE THREAD

**Issue by pnomolos** [seattlerb/minitest#707]
I was trying to use minitest-reporters together with minitest-parallel_fork, and (rightly) ran into an issue due to what minitest-parallel_fork expects in terms of output.  I realize there is probably several ways of solving this problem, however the approach I took led me down the rabbit hole until I figured out that MT was autoloading plugins, which in turn meant that minitest-reporters only had to be somewhere on my gem path for everything to blow up.  This also means it's ~impossible~ much more difficult than it should be to test minitest-parallel_fork in both cases. (See https://github.com/jeremyevans/minitest-parallel_fork/pull/3)

I'm going to guess that minitest's autoloading of plugins is more due to history and the fact that it's been around longer than bundler has.  Is there any chance of it being removed for MT6?

(Ref #331 for another place where this caused issues)

/cc @os97673

**Comment by jeremyevans** [comment]
I would also like to request the removal of automatic loading of plugins in Minitest 6 due to the issues it causes.  I think plugin loading should be explicit.

**Comment by zenspider** [comment]
I view auto loading of plugins as a feature, not a bug.

**Comment by jeremyevans** [comment]
How do recommend handling the situation where you install a plugin for use in project A, and it breaks project B, even though you do not intend to use the plugin in project B?

Would you be open to adding an option to disable the automatic loading of plugins, considering there are situations where that "feature" can have a negative effect?

**Comment by zenspider** [comment]
I recommend filing a bug on the problematic plugin. `minitest-reporters` in this case should NOT be adding a report delegator into the mix until the user has opted in (and they ESPECIALLY should not be replacing the whole reporter chain).

https://github.com/kern/minitest-reporters/blob/master/lib/minitest/minitest_reporter_plugin.rb#L70-L74

**Comment by zenspider** [comment]
This is addressed via `--no-plugins`... but I also filed https://github.com/kern/minitest-reporters/issues/247
