### ISSUE TITLE
Let in spec syntax is broken?

### ISSUE THREAD

**Issue by sovetnik** [seattlerb/minitest#709]
```ruby
require 'minitest/autorun'

describe 'example' do
  subject { 4 }
  describe 'sum' do
    let :sum { 2 + 2 }
    it 'should work' do
      _(sum).must_equal subject
    end
  end
end
```

This should work, but i get 
```
> ruby example_spec.rb 
example_spec.rb:6: syntax error, unexpected '{', expecting keyword_end
    let :sum { 2 + 2 }
              ^
example_spec.rb:6: syntax error, unexpected '}', expecting keyword_end
    let :sum { 2 + 2 }
                      ^
example_spec.rb:10: syntax error, unexpected keyword_end, expecting end-of-input
  end
     ^
```
Ruby version 2.4.2, Minitest::VERSION => "5.10.3"

**Comment by zenspider** [comment]
No... A syntax error is way before minitest is involved. This is how ruby works (apparently up until 2.4.x??)... maybe you're not running the version of ruby that you think you're running.

```
10029 % rbenv shell 2.2.6
10037 % ruby blah.rb 
blah.rb:6: syntax error, unexpected '{', expecting keyword_end
    let :sum { 2 + 2 }
              ^
blah.rb:6: syntax error, unexpected '}', expecting keyword_end
10046 % rbenv shell 2.3.3 
10056 % ruby blah.rb 
blah.rb:6: syntax error, unexpected '{', expecting keyword_end
    let :sum { 2 + 2 }
              ^
blah.rb:6: syntax error, unexpected '}', expecting keyword_end
10067 % rbenv shell 2.4.1 
10079 % ruby blah.rb 
Run options: --seed 35082

# Running:

.

Finished in 0.001036s, 965.2510 runs/s, 965.2510 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

You can fix this by either adding parens ( `let(:sum) { ... }` ) or using `do`/`end`.

**Comment by sovetnik** [comment]
Thanks for quick response!
Yes, with parens and do/end it works. but ruby is 2.4.2
I added ```puts RUBY_VERSION``` in beginning of script, and get
```
> ruby example_spec.rb 
2.4.2
Run options: --seed 50752
# Running:
Run options: --seed 50752
# Running:
..
Finished in 0.000999s, 1001.0011 runs/s, 1001.0011 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```
with ```let(:sum) { ... } ``` and same errors without round brackets.

**Comment by zenspider** [comment]
I don't know what to tell you. Something is definitely up but I don't think it is minitest (directly). A syntax error means that ruby can't even run the code. The fact that you're getting 2 run headers is a hint that _something_ is wrong.

What gems do you have installed?

**Comment by zenspider** [comment]
anything?

**Comment by sovetnik** [comment]
I  just followed your advice and added parentheses. Now it works.
But I still do not know how it worked before. Maybe close issue?
