### ISSUE TITLE
minitest .rb:63:in `block in autorun' while running individual Minitest function

### ISSUE THREAD

**Issue by devvpm** [seattlerb/minitest#712]
I am trying to run a specific test in Minitest like this.

`ruby my_test_file.rb --name=test_fun_name
`
and I get the following error :

> from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:670:in `each'
>     from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:670:in `start'
>     from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:134:in `run'
>     from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun' 
> 

However when I run `ruby my_test_file.rb` its working fine.

**Minitest version 5.10.2**

I got the issue on Minitest 5.10.3 as well.

**Ruby version is 2.3.3**

What could be the issue?

**Comment by zenspider** [comment]
That's not an error...just part of a stock trace. I can't help without real info

**Comment by devvpm** [comment]
I am able to run the whole file with ruby test_file_name.rb
But when I give the option --name=test_fun_name
It does not run the test and here is the response I get: 

C:\watir>ruby -Ilib test\tests\remap\mono\diablo\test_zu9eg_remaps.rb --name=tes
t_analysis_ku5p
ansi: 'gem install win32console' to use color on Windows
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/lib/minitest/mi
nitest_reporter_plugin.rb:61:in `detect': stack level too deep (SystemStackError
)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:61:in `guard_reporter'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:52:in `init_all_reporters'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:47:in `all_reporters'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:26:in `report'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:42:in `block in total_count'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:41:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:41:in `find_all'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.1.15/li
b/minitest/minitest_reporter_plugin.rb:41:in `total_count'
         ... 1841 levels...
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest
.rb:670:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest
.rb:670:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest
.rb:134:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/minitest-5.10.2/lib/minitest
.rb:63:in `block in autorun'

**Comment by zenspider** [comment]
That looks like a problem with minitest-reporters

**Comment by devvpm** [comment]
Thank you, It was minitest-reporters version issue.

**Comment by ak15** [comment]
@devvpm which version did you use?
