### ISSUE TITLE
Minitest On failure Event

### ISSUE THREAD

**Issue by devvpm** [seattlerb/minitest#713]
Is there a way I can capture MiniTest on failure?
Currently, I use [Minitest-Retry](https://github.com/y-yagi/minitest-retry) library for this.

The following code takes a screenshot on failure.  How to do this in MiniTest?
```

Minitest::Retry.on_failure do |klass, test_name|
    if $browser
        $browser.screenshot.save("test/screenshots/#{host_name}_#{klass}_#{test_name}.png")
        logout()
    end
end
```

**Comment by zenspider** [comment]
I don't know what you mean by "capture Minitest on failure".

**Comment by nateberkopec** [comment]
I think he wants to be able to run a block any time a test fails.

**Comment by devvpm** [comment]
Yes, I need to run a block of code whenever a test fails.

**Comment by devvpm** [comment]
Is it possible to write a block globally that runs when a test fails?

**Comment by zenspider** [comment]
Globally? No, but that's a good thing. Storing a browser snapshot when your basic unit tests fail doesn't make sense. For your integration tests, you can override `run` on your `Minitest::Test` subclass, rescue the `Assertion` exception, do your thing if necessary.

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
No response. Closing.
