### ISSUE TITLE
Documentation suggestion on stubbing methods with raising exception

### ISSUE THREAD

**Issue by hmistry** [seattlerb/minitest#720]
@zenspider I'd like to suggest incorporating @kytrinyx's [response](https://github.com/seattlerb/minitest/issues/440#issuecomment-49036039) into the Minitest documentation when stubbing methods to raise an exception. The key things I learned are: 

- wrap the raise exception in a proc, 
- then use the proc to stub the method, 
- and the proc must have same number of arguments as the method it's stubbing. 

It was not apparent from all the Minitest documentation I read, the issues here, SO, blogs, etc, as most of them presented solutions like your examples in that issue, which works for overriding methods but not when it comes to raising exceptions. In my trials, Minitest kept giving errors until it was wrapped in a proc. (It's possible I could have missed something but after many tries, the proc approach worked.)

@kytrinyx Thank you so much for writing this [example](https://github.com/seattlerb/minitest/issues/440#issuecomment-49036039). After many hours of googling and reading the docs, it was the key to solving my problem.

**Comment by zenspider** [comment]
I'm not clear on what you want the doco to say. You use too many pronouns so I'm not sure what you're referring to when you say ambiguous things like "it". How about you draft what you want there to be added?

**Comment by zenspider** [comment]
No response. Closing.
