### ISSUE TITLE
Can you stub a method that yields a block?

### ISSUE THREAD

**Issue by blackfist** [seattlerb/minitest#722]
It appears that if you stub a method that takes a block the block will always run

```
Thread.stub(:new, nil) {Thread.new {puts "shouldn't print"}}
shouldn't print
=> nil
```

I see that #414 talked about this last year and was closed. Was this ever resolved or is this a missed case?

**Comment by blackfist** [comment]
Here is another unsuccessful attempt at stubing this

```
require 'minitest/mock'

mock = Minitest::Mock.new
mock.expect :call, true

Thread.stub(:new, mock) do
  Thread.new do
    loop do
      sleep 2
      puts "what"
     end
  end
end
```

**Comment by zenspider** [comment]
This behavior is intentional tho I can't remember _why_  and I'm open to changing it for particular cases.

I have a change that I'm poking at that still fails with your original example because you're returning a plain nil. It does, however, pass with:

```ruby
Thread.stub(:new, proc { p :good! }) do
  Thread.new do
    raise "no!"
  end
end
```

I'd like to run this by @srbaker to verify that I'm not missing anything.

```diff
diff -r old/lib/minitest/mock.rb new/lib/minitest/mock.rb
--- old/lib/minitest/mock.rb
+++ new/lib/minitest/mock.rb
@@ -223,13 +223,15 @@
     metaclass.send :alias_method, new_name, name
 
     metaclass.send :define_method, name do |*args, &blk|
-      ret = if val_or_callable.respond_to? :call then
+      callable = val_or_callable.respond_to? :call
+
+      ret = if callable then
               val_or_callable.call(*args)
             else
               val_or_callable
             end
 
-      blk.call(*block_args) if blk
+      blk.call(*block_args) if blk unless callable
 
       ret
     end
diff -r old/test/minitest/test_minitest_mock.rb new/test/minitest/test_minitest_mock.rb
--- old/test/minitest/test_minitest_mock.rb
+++ new/test/minitest/test_minitest_mock.rb
@@ -509,4 +509,18 @@
     @tc.assert_equal true, rs
   end
 
+  def test_mock_with_yield_and_callable
+    mock = Minitest::Mock.new
+    mock.expect(:write, true) do
+      true
+    end
+    rs = nil
+
+    File.stub :open, proc { rs = true }, mock do
+      File.open "foo.txt", "r" do |f|
+        raise "No!"
+      end
+    end
+    @tc.assert_equal true, rs
+  end
 end
```

**Comment by zenspider** [comment]
@srbaker dude.

**Comment by zenspider** [comment]
I've already put several hours on this documenting the current (sometimes buggy) behavior... I'm about to finish polishing it and pushing it up for discussion. AFAICT, there's at least 2 bugs in the current implementation:

1. I now disagree with the change introduced by #414 (the way it was done). It should _only_ be calling the block if is is stubbed with a value. And really, it shouldn't even be called then (as you can provide a lambda that can call it yourself)
2. The block isn't passed to the stub's result lambda. (which means you can't currently do what I just suggested).
3. In the case of lambda + block_args (to the stub call), it should raise an exception as the current behavior is beyond nonsensical. 

(NOTE: "block" here refers to a block passed to the stubbed method, "lambda" refers to a callable that returns a result for that stubbed method, and "value" refers to a static object for the stubbed method)

I'm not yet decided which of these are "bugs" that need fixing now vs backwards-incompatible changes to behavior.

```ruby
  ## Permutation Sets:

  # [:value, :lambda]
  # [:*,     :block,     :block_call]
  # [:**,    :block_args]
  #
  # Where:
  #
  # :value      = a normal value
  # :lambda     = callable or lambda
  # :*          = no block
  # :block      = normal block
  # :block_call = :lambda invokes the block (N/A for :value)
  # :**         = no args
  # :args       = args passed to stub

  ## Permutations

  # [:call,   :*,          :**]   =>5 callable+block FIX: CALL BOTH (bug)
  # [:call,   :*,          :**]   =>6 callable

  # [:lambda, :*,          :**]   =>  lambda result

  # [:lambda, :*,          :args] =>  lambda result NO ARGS

  # [:lambda, :block,      :**]   =>5 lambda result FIX: CALL BOTH (bug)
  # [:lambda, :block,      :**]   =>6 lambda result

  # [:lambda, :block,      :args] =>5 lambda result FIX: CALL BOTH (bug)
  # [:lambda, :block,      :args] =>6 lambda result
  # [:lambda, :block,      :args] =>7 raise ArgumentError

  # [:lambda, :block_call, :**]   =>5 lambda FIX: BUG!-not passed block to lambda
  # [:lambda, :block_call, :**]   =>6 lambda+block result

  # [:lambda, :block_call, :args] =>5 lambda FIX: BUG!-not passed block to lambda
  # [:lambda, :block_call, :args] =>6 lambda+block result

  # [:value,  :*,          :**]   =>  value

  # [:value,  :*,          :args] =>  value, ignore args

  # [:value,  :block,      :**]   =>5 value, call block
  # [:value,  :block,      :**]   =>6 value

  # [:value,  :block,      :args] =>5 value, call block w/ args
  # [:value,  :block,      :args] =>6 value, call block w/ args, deprecated
  # [:value,  :block,      :args] =>7 raise ArgumentError

  # [:value,  :block_call, :**]   =>  N/A

  # [:value,  :block_call, :args] =>  N/A
```

* 5 = current behavior, whether I like it or not
* 6 = next version of stub, which might go into 5
* 7 = definitely backwards incompatible, might go into 6
```

**Comment by zenspider** [comment]
My current (and future) tests:

https://gist.github.com/7694f47409b0dcb410a28646f02897ac

**Comment by zenspider** [comment]
I've committed the tests showing current behavior. The next commit afterwards will show how it is buggy and include a fix.

**Comment by zenspider** [comment]
Here are my proposed changes: https://gist.github.com/5a83fcbc1173606fb121d35f30a160f2

This means that the original example still runs the block. The second example given is convoluted because it really has nothing to do with mocks, but the fact that the mock is a callable is just confusing. So a plain proc can suffice.

Running the following:

```ruby
require "minitest/mock"

Thread.stub(:new, :good!) {
  p Thread.new {
    puts "prints... but returns :good"
  }
}

Thread.stub(:new, proc { :good! }) {
  p Thread.new {
    raise "no"
  }
}


class Thingy
  def self.go &blk
    blk.call :good!
  end
end

Thingy.go do |x|
  p x
end

Thingy.stub :go, proc { p :good! } do
  Thingy.go do |x|
    raise "no"
  end
end

Thread.stub(:new, proc { p :good! }) do
  Thread.new do
    raise "no"
  end
end

mock = Minitest::Mock.new
mock.expect :call, true

Thread.stub(:new, mock) do
  Thread.new do
    raise "no"
  end
end
```

has the following output:

```
prints... but returns :good
:good!
:good!
:good!
:good!
:good!
```

I'm pretty happy with this compromise. @tenderlove is too AFAIK. It fixes 2 functional bugs in the current implementation (block isn't passed down to the callable and block is ALWAYS run even if you stub with a callable) and makes the above possible. I think I'm going to push my changes as they currently stand and am open to negotiating other changes, as needed.
