### ISSUE TITLE
ruby 2.5 - argument stack underflow

### ISSUE THREAD

**Issue by rickhull** [seattlerb/minitest#723]
getting an error from `minitest/spec.rb` on [ruby-head](https://travis-ci.org/rickhull/compsci/jobs/302341660)

```
Traceback (most recent call last):
/home/travis/.rvm/gems/ruby-head/gems/minitest-5.10.3/lib/minitest/spec.rb: /home/travis/.rvm/gems/ruby-head/gems/minitest-5.10.3/lib/minitest/spec.rb:20: argument stack underflow (-1) (SyntaxError)
rake aborted!
Command failed with status (1)
/home/travis/.rvm/gems/ruby-head@global/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => examples => test
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.
```

**Comment by rickhull** [comment]
I think it relates to https://github.com/ruby/ruby/commit/04b3328cd9ba138d717e68d1105ca4620de0a070#diff-89f770b631618387d3b3f6da6eb38a6cR1601

**Comment by zenspider** [comment]
There isn't enough information to work with here. Is there something to reproduce with?

@nobu ? Any ideas? I feel like I've seen this come up before...

**Comment by zenspider** [comment]
I just installed ruby 2.5.0 preview 1 and from trunk and can't repro.

**Comment by zenspider** [comment]
The line in question:

```ruby
when #{block} && Proc === target then
```

**Comment by rickhull** [comment]
Working on making this simpler and reproducible.

**Comment by zenspider** [comment]
I _just_ built, so my trunk is probably fixed, but my preview1 should still have it.

Based on the wording in a couple issues, and where the code is breaking in minitest, I think this is dependent upon the test(s)/impl(s) themselves.

**Comment by rickhull** [comment]
I'm not sure which of these would trigger it: https://github.com/rickhull/compsci/tree/master/test

They are all pretty basic and follow the template, with probably max 3 `describe` nesting:

```
describe TheClass do
  it "must some_method" do
    true.must_equal true
  end
end
```

**Comment by nobu** [comment]
It caused by removal of `trace` instruction at ruby/ruby@665ba24b446971fdf652a9c57c32b176d0018636, and I think it's fixed by ruby/ruby@c00265bbcc5deb1bcfcd0faa0cf8c4c42968de8e.

**Comment by zenspider** [comment]
OH... so this bug is only a 2 day span of existence... I misinterpreted and thought it might also exist in 2.5 preview 1.

@rickhull should this be closed?

**Comment by rickhull** [comment]
Yep, for sure.  Didn't mean to cause any unnecessary strife with this.  Every little breakage on `ruby-head`  doesn't need a ticket.  This was the best place I could come up with to note the misbehavior.  Now that I understand more about how this works, I can raise future `ruby-head` issues to the appropriate channel.  Not sure if that would be an issue for ruby/ruby or something more bleeding edge focused.
