### ISSUE TITLE
`assert(true, result_boolean)` will pass, but should have failed

### ISSUE THREAD

**Issue by redbar0n** [seattlerb/minitest#724]
Have you seen this in tests?

1.
```
result_boolean = some_method_returning_a_boolean_result
assert(true, result_boolean)
```

Where the programmer forgot to use:

2.
```
result_boolean = some_method_returning_a_boolean_result
assert_equal(true, result_boolean)
```

But the test (1.) still passed! Leaving the programmer to think everything was ok.

This happens since assert is defined as `assert(test, msg = nil)`
http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#method-i-assert

So it's like writing `assert(true)` but also passing the result_boolean in as a msg.

Maybe there should be some sort of modification to assert or other provision that would catch such erroneous use and raise an exception or whatnot? Maybe disallow passing a boolean to msg?

**Comment by nateberkopec** [comment]
`assert` is only aware that a value has been passed. It only "sees" the `true`, so from the method's perspective, the following two tests are exactly the same:

```ruby
assert(true)
assert(something_that_evaluates_to_true)
```

I don't think there's anything Minitest can do.

**Comment by zenspider** [comment]
@nateberkopec I dunno... Maybe a type check on `msg` for stringy or callable? 

I question the actual value of it. I doubt this happens that much so I'm not sure how well this'll pay for itself in the long run. It'll still let some bad use through. It'll cost more for EVERY assertion (since they all bubble up to `assert`). And stringy/callable values are both truthy, so they could be misuse as well.

I see more value in something that can "lint" tests. Check for literal values in the first slot of assert. Suggest using better assertions like `assert_predicate` instead of `assert`. That type of thing.

Thoughts?

**Comment by redbar0n** [comment]
@zenspider What about a type check on `msg` for boolean specifically (not truthy)? To disallow boolean values, like I mentioned.

Example:
```
>> a = true
=> true
>> a == true || a == false
=> true

>> a = false
=> false
>> a == true || a == false
=> true

# But will not give true for "truthy" values
>> a = 1
=> 1
>> a == true || a == false
=> false
>> a = 'string'
=> "string"
>> a == true || a == false
=> false
```

Not sure about how much that `a == true || a == false` check costs in terms of milliseconds though, but if expensive it could be a point that it would make asserts with `msg` defined more slow (if for example thousands of such asserts are in the test suite). Asserts without msg defined should not be affected, ideally.

**Comment by nateberkopec** [comment]
@redbar0n I *only* use `assert` when the expression is (suppose to) evaluate to `true`, though. Otherwise I use `assert_equal` and actually state the thing being returned. 

```ruby
assert @thing.predicate_method?
assert_equal "foo", @thing.something

assert @thing.something # this test could say *more* about what @thing.something returns
assert_equal true, @thing.predicate_method? # this just feels verbose to me.
```

**Comment by zenspider** [comment]
@nateberkopec that's kinda funny. I do the opposite. I _only_ use `assert` if it is supposed to be some truthy value. If it needs to be `true` specifically, I'll document that with `assert_equal` instead.

**Comment by zenspider** [comment]
@redbar0n I'm not entirely sure what you're suggesting. 

Which of these should be a problem?

```ruby
assert true, true
assert true, false
assert true, proc { ... }
assert true, 42
assert true, Object.new
assert false, true
assert false, false
assert false, proc { ... }
assert false, 42
assert false, Object.new
```

Of those that are problems, what should happen? How does your proposal fit in here:

```ruby
    def assert test, msg = nil
      self.assertions += 1
      unless test then
        msg ||= "Expected #{mu_pp test} to be truthy."
        msg = msg.call if Proc === msg
        raise Minitest::Assertion, msg
      end
      true
    end
```

**Comment by redbar0n** [comment]
@nateberkopec Yes, and you probably use it the correct way. However, the problem arises when some other programmer has used it in the way I described in the original post. It should raise an error to that programmer, so the erroneously implemented test doesn't pass (like it currently does).

**Comment by redbar0n** [comment]
@zenspider Great with concrete examples. 

I'm proposing:

```ruby
assert true, true # => should raise error
assert true, false # => should raise error
assert true, proc { ... }
assert true, 42
assert true, Object.new
assert false, true # => should raise error
assert false, false # => should raise error
assert false, proc { ... }
assert false, 42
assert false, Object.new
```

The ones I didn't comment above should pass as they normally would. Since the second parameter here is actually a `msg` and the programmer may - on a failed assertion - want to output either of those objects as the message (or call the proc, for reasons unknown to me).

Perhaps like this:

```ruby
def assert test, msg = nil
  raise IncorrectUseError if msg == true || msg == false
  self.assertions += 1
  unless test then
    msg ||= "Expected #{mu_pp test} to be truthy."
    msg = msg.call if Proc === msg
    raise Minitest::Assertion, msg
  end
  true
end

def IncorrectUseError < Minitest::Error
  def message
    "The second parameter to assert is the assertion msg, and cannot be true/false.
     When asserting boolean values, simply put the expected result as the first parameter. 
     Or, alternatively, use assert_equals to compare boolean values."
  end
end
```

**Comment by zenspider** [comment]
I think I'm just going to have to reject this one. I still don't see the value in this.
