### ISSUE TITLE
Appveyor/windows testing?

### ISSUE THREAD

**Issue by MSP-Greg** [seattlerb/minitest#731]
@zenspider

Not that familiar with CircleCI, but a quick glance didn't show many ruby versions.

I'd be happy to set up Appveyor testing if you'd like (free for open source). Ruby versions 1.9.3 thru head/trunk are available (2.5 soon), I'd set trunk for 'allow failure'.

Trunk is my build (used by RubyGems, ruby/spec, Puma, etc), so you can always ping me if there are  issues.  I believe mine is better tested than the Travis builds (mine's done three times a day, and the most recent 'passing' build is made available for testing)...

**Comment by zenspider** [comment]
I almost never have issues on windows so I'm not convinced this would be worth the hassle. Thank you tho.
