### ISSUE TITLE
MiniTest 5.11.1 -- error or failure also causes undefined method (for test name) backtrace

### ISSUE THREAD

**Issue by ChrisBr** [seattlerb/minitest#732]
Unfortunately I can not reopen https://github.com/seattlerb/minitest/issues/730 so I'm opening a new one. Release 5.11.1 did not fix the issue, I still get the same error (see https://github.com/seattlerb/minitest/issues/730).

From my POV  #729 and #730 are unrelated.

```rb
class Minitest::Result
  def method name
    o = Object.new
    def o.source_location
      ["unknown", -1]
    end
  end
end
```

Your suggestion did fix the issue, however, wouldn't that be always return ``["unknown", -1]`` for source location? Also it would return just an ``Object`` instead of a ``MethodObject``.

What about only storing the ``MethodObject`` instead of only the source location? This also worked for me:

```rb
def method name
  if name.to_sym == method_object.name
    method_object
  else
    orig_method(name)
  end
end
```

Your other suggestions would require to patch ActiveSupport, no?

Thanks!

**Comment by zenspider** [comment]
_I_ can reopen #730. Can you copy/paste this over to there to keep one stream going?

**Comment by ChrisBr** [comment]
copied over to #730, closing ...
