### ISSUE TITLE
API change in version 5.11.x causes break in third party gems that utilize test results

### ISSUE THREAD

**Issue by mbround18** [seattlerb/minitest#738]
A change occurred  at https://github.com/seattlerb/minitest/commit/00433fc0a4fdd0e6b302aace633384ba13122376#diff-444fa8babd8886c012733b064d709db5 which altered the the way minitest passes around the result of a test. This API change in a minor version caused a break in the way third party gems utilize the results from a test. In the case of the minitest-reportes, in the base reporter the gem utilizes the test results to run a couple methods called before_suite and after_suite. More on the issue can be found at https://github.com/kern/minitest-reporters/issues/248 as well as https://github.com/kern/minitest-reporters/pull/249 with the potential fix being at https://github.com/kern/minitest-reporters/pull/250 To view the issue for yourselves please create a directory and place the following ruby snippet in a file called `test_suite.rb` and bash script in the directory then run the bash script. With this issue I would like to open up a conversation about the intended use of the results of a test, whether or not this method should be utilized by third party gems, or if the change to the API should have caused a bump in major version on the minitest side. 

The contents of the snippet below should go into a file called `test_suite.rb`
```ruby
require 'minitest/autorun'
require 'minitest/reporters'
MiniTest.load_plugins
MiniTest::Reporters.use! MiniTest::Reporters::SpecReporter.new

class TestSuite < MiniTest::Test
	5.times { |i| define_method(format('test_pass_%03d', i).to_sym) { assert true } }
end
```

The contents of the snippet below should go into a bash script with the file extension of `.sh` but can be under any file name.
```bash
#!/usr/bin/env bash
if [ -d "$HOME/.rvm" ]; then
    export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
elif [ -d "$HOME/.rbenv" ]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
else
    raise "The script cannot seem to find an installation of rbenv or rvm!!!"
fi

echo "This is executing on minitest version < 5.10.3"
if [ -e './Gemfile'  ];
then
   rm ./Gemfile
   rm ./Gemfile.lock
fi

bundle init
    echo "gem 'minitest', '< 5.10.3'" >> ./Gemfile
    echo "gem 'minitest-reporters'" >> ./Gemfile

bundle install
bundle exec ruby ./test_suite.rb

echo "This is executing on minitest version > 5.10.3"
if [ -e './Gemfile'  ];
then
   rm ./Gemfile
   rm ./Gemfile.lock
fi

bundle init
echo "gem 'minitest', '> 5.10.3'" >> ./Gemfile
echo "gem 'minitest-reporters'" >> ./Gemfile

bundle install
bundle exec ruby ./test_suite.rb
```

**Comment by zenspider** [comment]
> With this issue I would like to open up a conversation about the intended use of the results of a test, whether or not this method should be utilized by third party gems, or if the change to the API should have caused a bump in major version on the minitest side.

In the case of minitest-reporters, time and again the problems they have are caused by not respecting minitest's internals. It's gotten to be too difficult to deal with. In this case, it looks like the code was checking sameness of class of the result of a run in order to determine if minitest has moved from one suite to another (even expecting that is an assumption you shouldn't make) instead of using the public documented API. IOW, "Death to haphazard monkey-patching" via fairly haphazard monkey-patching is going to result in problems.
