### ISSUE TITLE
Using minitest as education tool - alias for i_suck_and_my_tests_are_order_dependent!

### ISSUE THREAD

**Issue by itggot-daniel-berg** [seattlerb/minitest#739]
I teach introductory programming.

I have assignments with tests I want to run in a specific order - for instance

1. Checking that the method does indeed exist, (and giving helpful advise if it does not)
2. Checking that the method takes the expected arguments (and giving helpful advise if it does not).

However, I would rather not have my students see "i_suck_and_my_tests_are_order_dependent!" in the test file.

I'm therefore trying to create an alias for `i_suck_and_my_tests_are_order_dependent!` but have, so far, been unsuccessful. How would I best go about doing that?

I have other helper functions I'm using, so in the end the alias (or other workaround) will probably end up in a gem.

**Comment by splattael** [comment]
Hi @itggot-daniel-berg,

As discussed in #400 you could do:

```ruby
def self.test_order
  :alpha
end
```

:arrow_right: https://github.com/seattlerb/minitest/pull/400#issuecomment-35087377

Rails used an `alias`:

```ruby
class << self
  alias :my_tests_are_order_dependent! :i_suck_and_my_tests_are_order_dependent!
end
```

:arrow_right: https://github.com/rails/rails/commit/e81f3c210eca074ed6227bd1c40835d44761c09e#diff-cbef10f252bdfb6975e32c5b9c32a84bR18

I hope this helps!

Kind regards,
  Peter

**Comment by itggot-daniel-berg** [comment]
Thanks!
