### ISSUE TITLE
Running minitest (with railties installed) results in duplicate results

### ISSUE THREAD

**Issue by yuuu** [seattlerb/minitest#740]
Running a simple `minitest` in my environment will result in duplicate results.

test

```ruby:sample.rb
require 'minitest/autorun'

class SampleTest < Minitest::Test
  def test_sample
    assert true
  end
end
```

result

```sh
Run options: --seed 51797

# Running:

Run options: --seed 51797

# Running:

..

Finished in 0.000657s, 1522.0700 runs/s, 1522.0700 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips


Finished in 0.000682s, 1466.2757 runs/s, 1466.2757 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

```

As a result of survey, it turned out that the following methods were executed three times in the environment where `railties` was installed.

minitest.rb
```ruby:minitest.rb
    def << reporter
      self.reporters << reporter
    end
```

If you uninstall `railties` as a trial, the number of executions of the above method is 2 and the problem no longer occurs.

**Comment by zenspider** [comment]
This is true. This is a problem with railties' minitest plugin. Using bundler or not having rails globally installed avoids this.

As a (bad) workaround, you can also use `--no-plugins` or `$MT_NO_PLUGINS`.
