### ISSUE TITLE
Breaking change from 5.11.1 to 5.11.2

### ISSUE THREAD

**Issue by composerinteralia** [seattlerb/minitest#741]
1146f43e56e8b6decd2c8ddd88d9fd9b9d3deedb
caused failures in the Rails travis build, since we expect `Minitest::Test` to have an `error?` method

https://github.com/rails/rails/pull/31799

**Comment by zenspider** [comment]
Uuugh I suck. This is now released. Thanks for the timely report and PR!

**Comment by composerinteralia** [comment]
No worries! Thanks for the timely release!
