### ISSUE TITLE
Wrong number of arguments error in minitest:initialize method

### ISSUE THREAD

**Issue by mukarramali** [seattlerb/minitest#747]
https://github.com/seattlerb/minitest/blob/005a3ba42c07d04797e2d00ac2c53e3be127c12f/lib/minitest.rb#L400

Why do I have to pass a name, that I don't even want to use. Shouldn't this be nil by default?

**Comment by mukarramali** [comment]
Pull Request:
https://github.com/mukarramali/minitest/pull/1

**Comment by mukarramali** [comment]
Sorry ho gya. My bad, had some issue in my own test controller namespace.

**Comment by zenspider** [comment]
please close if this is no longer applicable...
