### ISSUE TITLE
Install from git

### ISSUE THREAD

**Issue by Paxa** [seattlerb/minitest#750]
If this repo had `minitest.gemspec` file in it, then we could install latest version like this:
```ruby
gem 'minitest', github: 'seattlerb/minitest'
```

But it doesn't have it :(

**Comment by SuperSandro2000** [comment]
PR's are always welcome everywhere 😃

**Comment by zenspider** [comment]
I release minitest as frequently as is reasonable. I support running minitest from a released gem and _I do not support_ running it directly from git. 

Unfortunately, @SuperSandro2000 is wrong. PRs are not always welcome in this case.

**Comment by Paxa** [comment]
Would it be bad if people can install minitest from git? (for example make a fork and use it easily)

**Comment by utilum** [comment]
Well... if you fork and want a git installable fork, you can add a gemspec.

**Comment by SuperSandro2000** [comment]
> I support running minitest from a released gem and I do not support running it directly from git.
Doesn't mean it couldn't be added.

> Unfortunately, @SuperSandro2000 is wrong. PRs are not always welcome in this case.
First time in my life I hear that. PR's are always welcome except they change things in a bigge scope or break things. This would kinda fall under it.
I think the more correct way would be to do a PR's to hoe that allows generating a gemspec.

Unrelated: a Gemfile wouldn't hurt the project. You could look up that this uses hoe, google about it and make the conclusion that the manifest is important.
