### ISSUE TITLE
Bug in string diff

### ISSUE THREAD

**Issue by graywolf** [seattlerb/minitest#753]
I think I've found a bug in string diff functionality:

	require 'minitest'
	require 'minitest/autorun'

	class Foo < Minitest::Test
		def test_with_bf
			expected = <<~EOF
				a
				\x00
				b
				\x00
				c
				\xbf
				d
			EOF

			r, w = IO.pipe
			w << expected
			actual = r.read(expected.size)

			assert_equal(expected, actual)
		end
		def test_without_bf
			expected = <<~EOF
				a
				\x00
				b
				\x00
				c
				d
			EOF

			r, w = IO.pipe
			w << expected
			actual = r.read(expected.size)

			assert_equal(expected, actual)
		end
	end

Produced this when executed:

	Run options: --seed 58584

	# Running:

	F.

	Finished in 0.003157s, 633.5929 runs/s, 633.5929 assertions/s.

	  1) Failure:
	Foo#test_with_bf [test.rb:20]:
	--- expected
	+++ actual
	@@ -1,7 +1,8 @@
	+# encoding: ASCII-8BIT
	 "a
	-\u0000
	+\x00
	 b
	-\u0000
	+\x00
	 c
	 \xBF
	 d

In the diff we have the null bytes marked as different, while the real issue
here is the `\xBF` byte. But that is not marked as different, so I think this
is a bug?

**Comment by zenspider** [comment]
I don't think I understand what you're saying about `\xBF` "not marked as different". It isn't different, so why would it be?

AFAICT, this has nothing to do with minitest at all and entirely about how ruby deals with string representations... but I'm poking to see what I can do to normalize it.

**Comment by zenspider** [comment]
Also, PLEASE don't use tabs. Ever. Nobody in the ruby community uses tabs in their source code. It's ugly and non-idiomatic formatting. 2 spaces per indent has been our gold standard since the beginning.

**Comment by zenspider** [comment]
So... there are two things about that diff that stand out. Obviously the difference in the representation of the null bytes, but also that first diff about the encoding. It turns out that your string is _not_ a `valid_encoding?`, and as such, I'm not sure how much minitest _should_ be doing about this. The diff is accurate as far as I'm concerned (the representations differences are a bit odd, but totally understandable when you realize that `expected` in (invalid) UTF-8 and `actual` is binary.

Right now, `mu_pp` tacks on the encoding if the value is a string. I guess I could also tack on the result of `valid_encoding?` as well. Beyond that? I don't know what else minitest _should_ do.

Thoughts?

**Comment by graywolf** [comment]
Thinking back about this I think what would actually suffice is to print warning or something in case the `expected` and `actual` have difference encodings.

So in the case that comparison fails, together with the diff print warning saying that `expected.encoding (XXX) != actual.encoding (YYY)`.

Would that be possible?

**Comment by zenspider** [comment]
The diff _is_ printing that there is a difference in encodings. That's why that `ASCII-8BIT` line is showing with a `+`.

**Comment by zenspider** [comment]
Anything? Does that suffice?

**Comment by graywolf** [comment]
Sorry, I've somehow missed the previous email with notification.

I see, I guess I've expected something like

```
-# encoding: UTF-8
+# encoding: ASCII-8BIT
```

but now I understand.

But anyway, does comparing strings of different encoding even make sense? Shouldn't that fail automatically (because it's likely not something programmer wants to do) or at least print big warning even when the strings do technically match?

**Comment by zenspider** [comment]
I don't determine what ruby decides is equal, ruby does:

```
  def test_string_experiment
    a = "hello"
    b = "hello".b

    assert_equal a, b
    refute_equal a.encoding, b.encoding
  end
```

that test passes.

I've since made it so that the encoding is printed on both sides, so they will show up in the diff output as well.
