### ISSUE TITLE
Location for "Use assert_nil if expecting nil from" warning

### ISSUE THREAD

**Issue by kwerle** [seattlerb/minitest#757]
It'd be spiffy cool if this warning stated the test location (file path:line number) causing it.

**Comment by zenspider** [comment]
It does? https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L179-L183

**Comment by kwerle** [comment]
OK - it's leaving something not entirely useful to me:

`DEPRECATED: Use assert_nil if expecting nil from /usr/local/bundle/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:212. This will fail in Minitest 6.`

Maybe I need to update rspec-rails...

    minitest (5.11.3)
    rspec-rails (3.7.2)

**Comment by utilum** [comment]
It looks like you already use the latest version of rspec-rails.

**Comment by jbosse** [comment]
I dislike this deprecation all together. Sometimes I need to assert that to things are the same (like source and mapped data) when they both may or may not be nil.

**Comment by zenspider** [comment]
@jbosse Absolutely nothing about this is stopping you. You just need to be more explicit now. Please don't piggy back on (fairly) unrelated issues. Open a new one if you must.

**Comment by zenspider** [comment]
This seems like an issue with rspec-rails and not with minitest. Closing and locking because I'm tired of this nil argument.
