### ISSUE TITLE
Recent Minitest Change Broke Rubymine Reporting

### ISSUE THREAD

**Issue by tleish** [seattlerb/minitest#759]
A recent change in Minitest 5.11.0 caused an issue in Rubymine where the reporting output no longer works correctly. see: https://youtrack.jetbrains.com/issue/RUBY-20717

I narrowed down the commit in minitest that caused the issue in Rubymine to 00433fc0a4fdd0e6b302aace633384ba131223.

Did this break minitest-reporters which Rubymine uses?

**Comment by zenspider** [comment]
I can't (won't) read the ticket on jetbrains because it requires a lawyer and more time/patience than I'm willing to give just to read an error report. If there wasn't a 10 page legal agreement involved I'd poke around more.

Just to clarify, as I don't use rubymine. Are **you** using minitest-reporters, or is that something rubymine uses automatically (or both) to get results back into the editor?

**Comment by Pepan** [comment]
Hi.
You can look at page https://www.jetbrains.com/help/ruby/minitest-reporters.html (publicly available). Where is explained your question.
Rubymine works without minitest-reporters but with much uglier output.

**Comment by zenspider** [comment]
@Pepan thank you. That helps. The doco there says that if you're running minitest 5+ then you don't need minitest-reporters. You say it is uglier output tho. Does that mean that rubymine doesn't hook into the reporter system to report back to the editor?

@tleish why did you close this ticket? Doing so without explanation doesn't help the next person to come along with the same or similar problem.

**Comment by tleish** [comment]
Sorry, I closed the ticket because it felt like I poked a stick in a soft spot and didn't want to make anyone mad.

Rubymine automatically uses minitest-reporters.  The bug was originally reported to IntelliJ, which then pointed to minitest-reporters here: https://github.com/kern/minitest-reporters/issues/248#issuecomment-386036148.  Neither seemed to be fixing the issue, so I spent some time digging.

Using an and older or newer version of minitest-reporters doesn't cause any change in behavior, but pulling different commits from minitest does.  Commit 00433fc0a4fdd0e6b302aace633384ba13122376 changed something (either in the output or the API) which somehow altered the output which I believe Rubymine parses and the puts into it's UI.

**Comment by tleish** [comment]
Minitest-reporter isn't required if using Minitest 5+, but it improves the readability.  From the documentation: 

> ## Important note
> As mentioned before, minitest-reporters gem is required for integration with RubyMine for minitest version lower than 5.0.0.
> 
> However, this gem is still essential for the higher versions of minitest, if you want to see the test results in a tree view:
> 
> ![image](https://user-images.githubusercontent.com/1099993/39654513-5cffed92-4fb2-11e8-9969-c305475aafb0.png)
> rather than as plain list:
> 
> ![image](https://user-images.githubusercontent.com/1099993/39654520-615490e6-4fb2-11e8-9382-65b3291e70b1.png)

https://www.jetbrains.com/help/ruby/minitest-reporters.html
