### ISSUE TITLE
Pretty diff for Struct?

### ISSUE THREAD

**Issue by Nakilon** [seattlerb/minitest#760]
When I `assert_equal` structs it does not look nice:
```
--- expected
+++ actual
@@ -1 +1 @@
-#<struct url={:url=>"http://www.aeronautica.difesa.it/organizzazione/REPARTI/divolo/PublishingImages/6%C2%B0%2
0Stormo/2013-decollo%20al%20tramonto%20REX%201280.jpg", :width=>nil, :height=>nil, :type=>nil}, width=nil, heig
ht=nil, type=nil>
+#<struct url={:url=>"http://www.aeronautica.difesa.it/organizzazione/REPARTI/divolo/PublishingImages/6%C2%B0%2
0Stormo/2013-decollo%20al%20tramonto%20REX%201280.jpg", :width=>1280, :height=>853, :type=>:jpeg}, width=nil, h
eight=nil, type=nil>
```
Docs say:
> You can override this to use #pretty_print if you want.

But I don't really understand how am I supposed to do that. Instead I rewrote the beginning of `mu_pp` like this:
```ruby
    def mu_pp obj
      require "pp"
      s = obj.is_a?(Struct) ? obj.pretty_inspect : obj.inspect
```
and got nice:
```
--- expected
+++ actual
@@ -2,9 +2,9 @@
  url=
   {:url=>
     "http://www.aeronautica.difesa.it/organizzazione/REPARTI/divolo/PublishingImages/6%C2%B0%20Stormo/2013-decollo%20al%20tramonto%20REX%201280.jpg",
-   :width=>nil,
-   :height=>nil,
-   :type=>nil},
+   :width=>1280,
+   :height=>853,
+   :type=>:jpeg},
  width=nil,
  height=nil,
  type=nil>
```
I don't have a pull request because I'm not sure how minitest solves this for arrays (does system `diff` utility split them in lines?) and where to put the `require "pp"`.

**Comment by zenspider** [comment]
I might be misunderstanding something (no coffee yet), but I think you want to call `make_my_diffs_pretty!` in your test class:

https://github.com/seattlerb/minitest/blob/master/lib/minitest/test.rb#L44

**Comment by zenspider** [comment]
No response. Closing.
