### ISSUE TITLE
Add ability to customize assertion failure location

### ISSUE THREAD

**Issue by fmwr** [seattlerb/minitest#761]
This how failure location looks now:

```
  1) Failure:
HappyPathTest#test_happy_path_with_api [/Users/tomek/my_project/test/api_test.rb:19]:
Expected false to be truthy.
```

Only one line of failure location trace is shown due to: https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L823-L830

Fine for most cases. But I often happen to have assertion calls inside "nested" methods (invoked from test body), like this:

```
def test_works
  assert_works
end

private

def assert_works
  assert false
end
```

In such case its impossible to localise the assertion which actually failed.

I can easily change this behavior by monkeypatching `Minitest::Assertion#location` method:
```
module Minitest
  class Assertion
    def location
      "\n" + backtrace.join("\n") + "\n"
    end
  end
end
```

But it would be nice to be able to customize this behavior without resorting to monkey patching, perhaps in a manner similar to `Minitest.backtrace_filter`.

I'm aware that using a custom reporter can solve it as well, but it might be nice to be able to do it without it.

Thoughts?

**Comment by fmwr** [comment]
I have test cases where I need to break it down into smaller methods (private or not). I'm aware it might not be the best test design, I hope to get there one day :) In the meantime, the assumption, that the assertion will always reside in main test method, seems to be a little too restrictive.

**Comment by fmwr** [comment]
> I'm aware that using a custom reporter can solve it as well, but it might be nice to be able to do it without it.

After a closer look it seems to me it's not solvable by introducing a custom reporter. I have to resort to monkey patching `Minitest::Assertion#location` anyway. 

@zenspider @drbrain Would you welcome a PR that'd expose a way of customising this behavior without monkey patching, perhaps in a manner similar to `Minitest.backtrace_filter`?

**Comment by zenspider** [comment]
Assuming I understand your request (that you want inner-assertion locations to be reported), then I am going to reject this. This is an intended feature that the top level assertion is the thing reported as failing. If you don't want that, don't name your assertions with "assert" or "refute" as a prefix. Use "check" or something else instead and it'll report the inner-assertion instead.

If I am not understanding this, please correct.

**Comment by zenspider** [comment]
No response. Closing.
