### ISSUE TITLE
Stubbed method evaluation/execution occurs before block

### ISSUE THREAD

**Issue by DanDevine** [seattlerb/minitest#763]
I've stubbed a method for the _subject_ class that I will be testing, and the stubbed method is being called/evaluated *before* the subject even begins execution.

Example:

```
img = subject.stub :get_from_remote_origin, fake_get_from_remote_origin do
    subject.execute(tempfile.path, request_params)
end
```

In this case, the _subject.execute()_ method will first to look in the local cache, do some other things, and then if the needed file doesn't exist, call the method _get_from_remote_origin_ and download the file.  In order to fake this process, I'm copying the test file into the cache location and returning a response that the download went fine...  

What I'm finding is that the _fake_get_from_remote_origin_ method is being called *before* execution of the subject is even started, causing a situation where the file is already in place before the subject test begins.

Expected result:  
subject.execute starts and proceeds until it encounters a call to the stubbed method _get_from_remote_origin_, at which point it will execute/evaluate the _fake_get_from_remote_origin_ for the method, return the result, and continue until finished. 

Actual result:  
_fake_get_from_remote_origin_ is being executed first, the fake file is being downloaded and put into the local cache before execution of the subject even starts, and therefore the test isn't really testing what I'm expecting.

Do I have something mis-configured?  Does anyone else see the same behavior.

Thanks

**Comment by utilum** [comment]
I've not tried this, but I think something along these lines should work:
```
def test_something
  subject.stub(:get_from_remote_origin, fake_get_from_remote_origin) do
    image = subject.execute(tempfile.path, request_params)

    assert image.is_just_as_I_expected
  end
end
```

**Comment by zenspider** [comment]
Yeah. Agreed. If `fake_get_from_remote_origin` is a method, then the `do`/`end` is binding to it and you need parens to disambiguate. If it isn't being reused across tests, can also make it a local variable w/ a proc and then the `do`/`end` should bind to the `stub` call.

**Comment by DanDevine** [comment]
Yes, *fake_get_from_remote_origin* is a method call.
When re-written like
```
   img = subject.stub (:get_from_remote_origin, fake_get_from_remote_origin) do
      subject.execute(tempfile.path, request_params)
    end
```
I get error:
```
syntax error, unexpected ',', expecting ')'
....stub (:get_from_remote_origin, fake_get_from_remote_origin)...
...    
```                           ^

**Comment by utilum** [comment]
Well... try running `ruby -cw your_test_file.rb`

**Comment by DanDevine** [comment]
When you operate any tests like these...does your stub method execute *before* the subject in the block starts?

**Comment by zenspider** [comment]
(the syntax error is from the space before the paren)

Use this for better doco: http://docs.seattlerb.org/minitest/Object.html

Given your example, fixed with parens and removed space:

```ruby
   subject.stub(:get_from_remote_origin, fake_get_from_remote_origin) do
      subject.execute(tempfile.path, request_params)
    end
```

`fake_get_from_remote_origin` is STILL a method call and you need to address that. Exactly the same as when you do something like:

```ruby
sum = 1 + 2 + some_method_call

# or:

some_method_call(1, 2, other_method_call)
```

In order for the expression to be evaluated, all arguments need to be evaluated first... that's just how ruby (and math for that matter) works. So either that method call needs to NOT happen, by passing a proc/callable, or that method call needs to return something that can be used for the stub... either the value you want, or a proc/callable.

Does that make sense? Lemme know if you have any questions or want a more concrete example.

**Comment by DanDevine** [comment]
Here's a test case you can run to see for yourself:

```
#  Runs test case....
def perform_test
    testclass = TestClass.new
    testclass.stub(:real_method, fake_method) do
      testclass.under_test
    end
end

# Fake method stub
def fake_method
    File.new('testfile.txt', 'w+')
end

#  Stand-in for real class being tested, illustrates the issue...
class TestClass
    #  Some internal method of the subject being tested...target of stub...
    def real_method
      print('blah, blah, blah...')
    end

    #  Larger internal method of subject being tested... called from inside block
    def under_test
      if File.exist?('testfile.txt')
        print('Failed...stub method executed before call...not supposed to exist yet')
      end
      real_method
    end
end
```

If you run the test case and see "Failed..." message, then the stub has been executed **before** it should have been.

**Comment by zenspider** [comment]
Your expectation is wrong and is a misunderstanding of the execution model of ruby. This is plain ruby code. There is no magic. As I said above, method arguments MUST be evaluated before the method is called and that is exactly what your code above illustrates.

If you want to delay an action, you return a proc that captures that action and will do that action later. This works in your example:

```ruby
def fake_method
  proc { File.new('testfile.txt', 'w+') }
end
```

**Comment by DanDevine** [comment]
That's just how I solved it, and I though these 'stubs' were essentially doing that too, with the added benefit of unwrapping the definition after the block.

Putting something in the documentation about this would be really helpful too.

**Comment by zenspider** [comment]
I'm happy to clarify the documentation. Can you point to where you feel it is insufficient and suggest language you think would help?

**Comment by zenspider** [comment]
No response from OP to my last question.

Closing, as I believe this issue to not be a bug in minitest but a misunderstanding of how ruby works. I'm not against clarifying in the documentation but I don't see what/where anything is needed myself.
