### ISSUE TITLE
Minitest::Result not marshallable if any failure contains exception with unmarshallable data

### ISSUE THREAD

**Issue by jeremyevans** [seattlerb/minitest#768]
If a test/spec raises an exception, minitest stores a reference to the exception in `Minitest::UnexpectedError#exception`, and includes the `Minitest::UnexpectedError` instance in `Minitest::Result#failures`.  If the exception contains unmarshallable data, that makes the `Minitest::Result` not marshallable, and the whole point of `Minitest::Result` is to be marshallable.

I had to work around this in minitest-parallel_fork: https://github.com/jeremyevans/minitest-parallel_fork/commit/9226f1a017c1b3a57f1c5eb8ecaeb8055917cfc1#diff-b9aaa6d358fee521899490d21e5475dbR61

 This is not a theoretical case, I hit it in a real application because a test raised a `PG::Error` exception, which contains a reference to `PG::Connection`, which is not marshallable.

**Comment by zenspider** [comment]
@jeremyevans in your commit above... not sure where you're getting `#exception=` from... but I'm going about this in a slightly different way so I am not mutating:

```ruby
    def sanitize_exception e # :nodoc:
      Marshal.dump e
      e
    rescue TypeError
      bt = e.backtrace
      e = RuntimeError.new "Wrapped undumpable exception for: #{e.class}: #{e.message}"
      e.set_backtrace bt
      e
    end
```

**Comment by jeremyevans** [comment]
@zenspider Since this was posted 3.5 years ago, you changed the API in a backwards incompatible manner (5802aa08280a3609b684e0ebef95dabfbd3ec9ff). The attribute is now named `error` instead of `exception`.  minitest-parallel_fork was updated to handle that (https://github.com/jeremyevans/minitest-parallel_fork/commit/ce27ec0f63e744ba81bedda7cbec9869d71e31df).

**Comment by zenspider** [comment]
I've got this working with a slightly different solution. Sorry it took me so long.

**Comment by jeremyevans** [comment]
No problem, thanks for fixing it!
