### ISSUE TITLE
null-pointer exception in parallel with certain Bundler options

### ISSUE THREAD

**Issue by jamesarosen** [seattlerb/minitest#773]
When I run a test suite with
```rb
Bundler.require
```
everything runs fine.

When I run it with
```rb
Bundler.require(:default, :test)
```
I get
```
/usr/local/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest/parallel.rb:52:in `shutdown': undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/minitest-reporter-api-0.0.5/lib/minitest/reporter_api.rb:37:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```

That's [this line](https://github.com/seattlerb/minitest/blob/2362e328883ff133140fd8bea5e9ec9a714a7999/lib/minitest/parallel.rb#L52) in `Minitest::Parallel::Executor#shutdown`. It seems that `#start` was never called.

The relevant section of my `Gemfile`:
```rb
group :test, :development do
  gem 'guard-minitest'
  gem 'minitap'
  gem 'minitest', '~> 5.0'
  gem 'minitest-fail-fast', '0.0.2.fastly'
  gem 'minitest-reporters'
end
```

In both cases, the minitest initializers that run are
```rb
plugin_minitest_reporter_init
plugin_fail_fast_init
plugin_minitap_init
plugin_guard_minitest_init
plugin_pride_init
```

I don't know whether this is a problem with Minitest, Bundler, or my understanding of `Bundler.require`.

**Comment by utilum** [comment]
Is there a particular reason you launch your tests with `Bundler.require`, not `ruby`, or `rake`, or even `bundle exec rake` ?

**Comment by jamesarosen** [comment]
I am calling `bundle exec rake test TEST=…`. The `Bundler.require` is in my application code.

**Comment by jamesarosen** [comment]
It looks like [minitest-reporter-api](https://rubygems.org/gems/minitest-reporter-api) is a dependency of [minitap](https://rubygems.org/gems/minitap), which also hasn't been updated in years.

```diff
-   gem 'minitap'
```

seems to be the answer :)
