### ISSUE TITLE
Aggregating failures. Feature

### ISSUE THREAD

**Issue by vtm9** [seattlerb/minitest#774]
Hi all!
Thanks for good gem!

Is there a way to aggregate failures with multiple asserts like in [rspec aggregating failures feature](https://relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures)?
This feature will speed up the tests.
If it's not there, I can help make it.

**Comment by utilum** [comment]
Do you mean that you'd like to have a single test method continue asserting after an assertion fails? Why? If the following assertions do not depend on the first passing, why don't you put them in a separate test method?

**Comment by vtm9** [comment]
I think that sometimes you have multiple asserts in one test. According this great [gem test-prof](https://github.com/palkan/test-prof) it speeds up tests `~3x faster`. This feature exists in rspec, it would be cool to add it to minitest. Thanks.

Example test from my project:
```ruby
test 'sends email' do
  @user = users(:default)

  perform_enqueued_jobs do
    visit login_path
    fill_in :user_email, with: @user.email
    fill_in :user_password, with: 'password'
    click_on 'SIGN IN'
  end

  email = ActionMailer::Base.deliveries.last

  aggregate_failures "login mailer" do
    assert { email.to == [@user.email] }
    assert { email.from == ['test@test.com'] }
    assert { email.subject == 'Login' }
  end
end
```

**Comment by zenspider** [comment]
I think the `~3x faster` is a misnomer. It will speed you up by whatever factor is spent on your test setup. If you have an expensive setup, as you do above, then it'll speed you up a lot. If you don't, then it won't really get you much of anything (in minitest—costs of running tests in minitest are minimal, this isn't as true in rspec).

Thank you for filing this issue, but I don't think I want to add this feature to minitest. I don't think it is necessary for writing tests. It mostly exists, as you've pointed out, to deal with the repercussions of slow tests. But, I'm happy to help you implement and package it up as an add-on gem and then list it in the minitest readme. Let me know if you want any help or have questions/clarifications.

**Comment by vtm9** [comment]
@zenspider I did some benchmarks, and think that you are right. It's a my mistake about 3x faster. Thanks

**Comment by Nakilon** [comment]
I want to migrate my little gem spec from RSpec to Minitest but I need this feature.
The test is doing things like:
```ruby
aggregate_failures do
  [
    [img1, 23654, 398769], 
    [img2, 651234, 40586948], 
    [img3, 1234, 5678], 
    [img4, 111, 222222], 
  ].each do |test_image, min, max|
    expect(my_function(test_image)).to be_between(min, max)
  end
```
So the array of test data can vary without changing the number of tests and at the end if there is a regression (i.e. `my_function` stopped fitting into the allowed range) you see all failures without need to make the listing report manually.
