### ISSUE TITLE
Require assertion call definitely must take place

### ISSUE THREAD

**Issue by molfar** [seattlerb/minitest#777]
```
test "require assertion" do
  WarehouseReservation.reserve(2) do |quantity|
    assert_equal 1, quantity
  end
end
```
This test will pass when "quantity is 1" OR "reserve method does not yield block at all".
But expected it to passed only if "reserve method yields block" AND "quantity is 1".

I think it is wrong behavior, as not yielding block should fail test and notify developer about problems in  reserve method.
I know, this can be figured out with mocks, but that would look too complicated and less readable in my opinion.

**Comment by zenspider** [comment]
You might want to look at the minitest-proveit plugin.

https://github.com/seattlerb/minitest-proveit

**Comment by molfar** [comment]
@zenspider Thank you, there is a gem for that. But I think this "assertion required" behavior must be enabled by default. Could you give an example case, where you really need your test pass without any assertions? For empty tests (aka boilerplates, todo-items) there is a nice skip method.

**Comment by zenspider** [comment]
I completely agree... but the behavior is there and people expect it. "London School" of thought (aka mockist) does not agree as they believe (as I understand it) that the mock's existence itself is basically an assertion. I've added an assertion `assert_mock` to try to push in that direction, but I think it has missed its mark.

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
No response. Closing.
