### ISSUE TITLE
:assert_equal of values that may or may not be nil

### ISSUE THREAD

**Issue by aceofbassgreg** [seattlerb/minitest#779]
In #757 the following exchange happened: 

https://github.com/seattlerb/minitest/issues/757#issuecomment-426386695

https://github.com/seattlerb/minitest/issues/757#issuecomment-426817804

I want to motivate the position @jbosse has. My exact test scenario is this:  I am tested a random member of an array that comes back from an API. I am comparing the equality of the member's data with the represented object's method response (something like `assert_equal data["points"], stat.points`. These should always be equal, but sometimes both are `nil`. 

One thing I might do is modify my `vcr` cassette so that there are no `nil` values, but I would rather have the data represent reality. I would advocate for maintaining `assert_equal`'s current behavior rather than having this kind of test fail in Minitest 6.

**Comment by aceofbassgreg** [comment]
Ah, great idea. I'm fine with doing that and therefore closing this request.

**Comment by nobu** [comment]
It is degeneration > `assert a == b`
The message when it failed is worse than `assert_equal`.

**Comment by swistak** [comment]
I have to agree with it. Just encountered this problem also. My use case is I'm testing the code with whole bunch of the examples, eg.

```
    [
      'Mr and Mrs John and Jane st. Germain' => ['Mr and Mrs', 'John and Jane st.', 'Germain'],
      'Alfonso Beneficio Celicio Darencio Emero Fernando Giskard' => ['', 'Alfonso Beneficio Celicio Darencio Emero Fernando', 'Giskard'],
      '1234567890' * 5 => nil, # Overlong unsplittable names.
    ].each do |recipient, fields|
      assert_equal fields, importer.split_recipient(recipient), recipient
    end
```

This is just an example, but not an uncommon pattern, in all cases I expect the equality check to work regardless if expected value is nil.

This flies straight into face of DRY, and makes some refactorings impossible.

Using `assert a == b` has problems - it looses the default error message, and is less semantic.
