### ISSUE TITLE
Why is a period appended to assertion message?

### ISSUE THREAD

**Issue by jschulenklopper** [seattlerb/minitest#780]
So I made an assertion with an error message to be displayed if the test failed. That error message, like a proper complete sentence, included a period at the end... but that resulted in _two dots_ in the message shown once the test failed.

Question (or suggestion:) should the message be displayed precisely as defined in the assertion message? So, not adding a period at the end of that message?

My test:
```
assert_equal(8, sheet.nr_of_rows, "Wrong number of rows.")
```

The output when failing (notice the superfluous period on the third line):
```
  2) Failure:
TestDiffer#test_read_file [/Users/jschulen/Code/project/test/test_differ.rb:19]:
Wrong number of rows..
Expected: 8
  Actual: 9
```

Minitest's own test covering this case is in:
https://github.com/seattlerb/minitest/blob/master/test/minitest/test_minitest_test.rb#L1677.

The code responsible for adding the period at the end of the message is in:
https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L517

I can create a PR for the change, to no longer add the closing period to the message.

**Comment by zenspider** [comment]
Or, you can not add your own period?

**Comment by jschulenklopper** [comment]
> Or, you can not add your own period?

Sure you can... but then the output message contains two periods :-) And if I wanted to have my message end with an exclamation mark, `Wrong number of rows!` the output becomes `Wrong number of rows!.`

So, by this logic, it would be better to have minitest _not_ add a period to the end of the message.

**Comment by zenspider** [comment]
Sorry. I am simply uninterested in this. Having the tool default to adding a period makes my tests cleaner across the board. As far as the exclamation mark goes, I say: calm yourself, your test is already failing so the urgency is already there.

**Comment by jschulenklopper** [comment]
> Sorry. I am simply uninterested in this.

Which is completely fine; it’s your call.

It was merely my view, and a suggestion to not alter a user-specified error message by adding a period. It is similar to that the code also does not capitalize the first character.

(The exclamation mark was just an example of an error message ending for which an additional closing period could be misplaced.)
