### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [seattlerb/minitest#787]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by SuperSandro2000** [comment]
Don't think so.
It uses autotest with this file https://github.com/seattlerb/minitest/blob/master/.autotest

**Comment by gustavosizilio** [comment]
Thank you very much

**Comment by zenspider** [comment]
Minitest and many of my projects were on circleci for quite some time:

https://circleci.com/gh/seattlerb/minitest

But their latest version doesn't work as well so I've not maintained it. I also run my own for all my projects here:

http://www.zenspider.com/~ryan/dashboard/

I believe it has also used travis or jenkins back in the day, but I've never liked their UI.
