### ISSUE TITLE
Incorrect assert_equal output with escaped backslash before "n"

### ISSUE THREAD

**Issue by Ruin0x11** [seattlerb/minitest#791]
When running this test:

```ruby
def test_escapes
  assert_equal "\\n", "\\"
end
```

I get this output:

```
 FAIL["test_escapes", #<Minitest::Reporters::Suite:0x000055748a415f88 @name="DecoderTest">, 0.0051554389065131545]
 test_escapes#DecoderTest (0.01s)
        --- expected
        +++ actual
        @@ -1,2 +1 @@
        -"\
        -"
        +"\\"
        test/unit/decoder_test.rb:443:in `test_escapes'
```

Shouldn't the expected output print `\\n` instead of an actual newline instead?

**Comment by zenspider** [comment]
This is a wonderfully fucked-up edge case. Thank you. It is thoroughly flummoxing me.

I think my current strategy is to extend the pretty diff with extra logic to make sure that no string has both real newlines and escaped ones... but I need to translate the above into the edge case combos I'm thinking of. Debugging diffed diffs is a bitch tho.
