### ISSUE TITLE
Parallel executor creates threads and does work even when no parallel tests

### ISSUE THREAD

**Issue by nateberkopec** [seattlerb/minitest#795]
I was debugging startup time in Puma's test suite and noticed that Minitest creates threads for the parallel executor regardless of whether or not any test classes use it.

Can we make this lazy somehow? I tried looking for an obvious patch opportunity but I couldn't find one.

**Comment by zenspider** [comment]
@tenderlove? this is on you. 😘

**Comment by tenderlove** [comment]
> Can we make this lazy somehow?

We probably could, but I think it means deferring until a job is queued, or some way to detect that the suite will use parallel tests.

I'm curious though, why do we need to do this?

**Comment by tenderlove** [comment]
I think this will do it (but it's not tested):

```diff
diff --git a/lib/minitest.rb b/lib/minitest.rb
index c0296b5..9d6e5b1 100644
--- a/lib/minitest.rb
+++ b/lib/minitest.rb
@@ -23,8 +23,6 @@ module Minitest
   mc.send :attr_accessor, :parallel_executor
 
   warn "DEPRECATED: use MT_CPU instead of N for parallel test runs" if ENV["N"]
-  n_threads = (ENV["MT_CPU"] || ENV["N"] || 2).to_i
-  self.parallel_executor = Parallel::Executor.new n_threads
 
   ##
   # Filter object for backtraces.
@@ -140,7 +138,7 @@ module Minitest
     rescue Interrupt
       warn "Interrupted. Exiting..."
     end
-    self.parallel_executor.shutdown
+    self.parallel_executor.shutdown if parallel_executor.respond_to?(:shutdown)
     reporter.report
 
     reporter.passed?
diff --git a/lib/minitest/parallel.rb b/lib/minitest/parallel.rb
index 40ac709..6d1805a 100644
--- a/lib/minitest/parallel.rb
+++ b/lib/minitest/parallel.rb
@@ -54,6 +54,12 @@ module Minitest
     end
 
     module Test # :nodoc:
+      def self.included(_)
+        n_threads = (ENV["MT_CPU"] || ENV["N"] || 2).to_i
+        Minitest.parallel_executor ||= Parallel::Executor.new n_threads
+        super
+      end
+
       def _synchronize; Minitest::Test.io_lock.synchronize { yield }; end # :nodoc:
 
       module ClassMethods # :nodoc:
```

**Comment by nateberkopec** [comment]
> I'm curious though, why do we need to do this?

It kept showing up in my ruby-prof runs of profiling the puma testsuite. It's kind of hard to tell with 3+ threads going whether or not removing them would improve the overall time so I was curious.

I applied your patch though and it made no meaningful impact on `time ruby some_test_file.rb` so I guess I was wrong.

I kind of like the new patch anyway as it moves parallel execution code in parallel.rb and out of minitest.rb, but I'll leave that up to Ryan. My issue is solved, which is that eager parallel execution preparation doesn't have a perf impact.

**Comment by zenspider** [comment]
> On Aug 27, 2019, at 23:59, Nate Berkopec <notifications@github.com> wrote:
> 
> I'm curious though, why do we need to do this?
> 
> It kept showing up in my ruby-prof runs of profiling the puma testsuite. It's kind of hard to tell with 3+ threads going whether or not removing them would improve the overall time so I was curious.
> 
> I applied your patch though and it made no meaningful impact on time ruby some_test_file.rb so I guess I was wrong.
> 
> I kind of like the new patch anyway as it moves parallel execution code in parallel.rb and out of minitest.rb, but I'll leave that up to Ryan. My issue is solved, which is that eager parallel execution preparation doesn't have a perf impact.

prolly depends on tooling but I’ve seen some serious bullshit in a profile the second that threads are brought into play.

**Comment by nateberkopec** [comment]
It's not really the tool, it's just like there's no way to tell how much of the work is being done in parallel and how much of it is blocking up the other threads by holding the GVL. You just have to remove and test.
