### ISSUE TITLE
Plugin woes

### ISSUE THREAD

**Issue by nateberkopec** [seattlerb/minitest#796]
The current plugin loading system uses `Gem.find_files("minitest/*_plugin.rb")`, which, unfortunately, is kinda slow. In the Puma test suite, it adds about 100ms of startup time.

IMO, the plugin itself should be responsible for registering itself with Minitest as a plugin, rather than Minitest searching *all installed files in all gems* to go find them.

It's pretty easy to hack this into Minitest (e.g. make minitest-pride just register itself in extensions) but I have no idea if we could set up a faster plugin loading system so that Gem.find_files doesn't have to be called.

**Comment by zenspider** [comment]
> IMO, the plugin itself should be responsible for registering itself with Minitest as a plugin, rather than Minitest searching all installed files in all gems to go find them.

How does that code run?

**Comment by zenspider** [comment]
> In the Puma test suite, it adds about 100ms of startup time.

The time is proportional to the number of gems you have installed. It costs me roughly nothing because I have 25 gems installed globally and use isolate for per-project deps.

What's the time for puma if you do `export GEM_HOME=xxx`, unset `GEM_PATH`, install your deps, and then run your tests sans-bundler?

(I honestly don't know if `Bundler.require` is smart enough to scope `Gem.find_files`, but that might be worth looking into)

**Comment by nateberkopec** [comment]
> IMO, the plugin itself should be responsible for registering itself with Minitest as a plugin, rather than Minitest searching all installed files in all gems to go find them.

Require? Inherited callbacks? Not sure. But Minitest is probably too far down the river to change this.

> (I honestly don't know if Bundler.require is smart enough to scope Gem.find_files, but that might be worth looking into)

This seems more profitable, but how would you scope it? Not all minitest plugins start with `mini-test-` I presume? The Rails one doesn't, I guess?

**Comment by nateberkopec** [comment]
Also I wonder if this would be responsible for weird output I see in Puma's test suite where it looks like the Rails plugin is being loaded (how it tells you what to put in your shell to re-run the test that failed, except it's wrong because I'm not in a Rails app).

**Comment by nateberkopec** [comment]
[TIL what the "Rubygems Plugin System" is.](https://github.com/bundler/bundler/blob/d44d803357506895555ff97f73e60d593820a0de/man/bundle-exec.ronn#rubygems-plugins).

That's the only mention of `Gem.find_files` in the entire Bundler core...so I'm going to go ahead and say no, it doesn't do that. I'm 99% sure there is another method that does. I'll figure it out and PR. Changing scope of this issue.

**Comment by nateberkopec** [comment]
Actually maybe not. For some I reason I thought there were already references to `Bundler` in minitest but there aren't.

**Comment by nateberkopec** [comment]
So, given the way the plugin system works ("search all installed rubygems for minitest plugin files"), then: 

> The rails one does, which was/is a problem... And I've tried to get them to fix it time and again.

How is the rails plugin been loaded the Rails project's fault? I don't understand. It seems to be working exactly as intended.

**Comment by nateberkopec** [comment]
With Bundle exec, without RUBYGEMS_GEMDEPS=-:       0.45 sec
With Bundle exec, with RUBYGEMS_GEMDEPS=-:            0.60 sec, plus a warning
Without Bundle exec, without RUBYGEMS_GEMDEPS=-: 0.26 sec, no plugins (?)
With Bundle exec, with RUBYGEMS_GEMDEPS=-:            0.27 sec, plugins load correctly

**Comment by zenspider** [comment]
Fascinating... Clearly we should all dump bundler for the `RUBYGEMS_GEMDEPS=-` feature?

Besides "woe", where is this?

**Comment by nateberkopec** [comment]
I'll close, this isn't actionable for now.
