### ISSUE TITLE
Docs on _(…) and must_raise

### ISSUE THREAD

**Issue by svoop** [seattlerb/minitest#806]
Ruby 2.6.4 and Minitest 5.12.2

In preparation for Minitest 6, I'm updating my test suites to no longer assert on Object but use `_(…)` instead. 

However, I came across the following problem: I didn't find any example for `must_raise` in the docs. So let's try it out:

```ruby
require 'date'
require 'minitest/autorun'

class AnyDate
  ROOT_DATE = Date.parse('2015-06-25').freeze

  def initialize(any_date)
    @any_date = any_date ? Date.parse(any_date.to_s) : Date.today
    fail(ArgumentError, "cannot calculate dates before #{ROOT_DATE}") if @any_date < ROOT_DATE
  end
end

describe AnyDate do
  it "1 - block only: won't accept dates prior to root date" do
    -> { AnyDate.new(AnyDate::ROOT_DATE - 1) }.must_raise ArgumentError
  end

  it "2 - block only: won't accept unparsable dates" do
    -> { AnyDate.new(0) }.must_raise ArgumentError
  end

  it "3 - value wrapper only: won't accept dates prior to root date" do
    _(AnyDate.new(AnyDate::ROOT_DATE - 1)).must_raise ArgumentError
  end

  it "4 - value wrapper only: won't accept unparsable dates" do
    _(AnyDate.new(0)).must_raise ArgumentError
  end

  it "5 - value wrapper and block: won't accept dates prior to root date" do
    _(-> { AnyDate.new(AnyDate::ROOT_DATE - 1) }).must_raise ArgumentError
  end

  it "6 - value wrapper and block: won't accept unparsable dates" do
    _(-> { AnyDate.new(0) }).must_raise ArgumentError
  end
end
```

Here's the output:

```
EDEPRECATED: global use of must_raise from minitest_must_raise.rb:15. Use _(obj).must_raise instead. This will fail in Minitest 6.
..DEPRECATED: global use of must_raise from minitest_must_raise.rb:19. Use _(obj).must_raise instead. This will fail in Minitest 6.
.E.

Finished in 0.002192s, 2737.2264 runs/s, 1824.8176 assertions/s.

  1) Error:
AnyDate#test_0004_4 - value wrapper only: won't accept unparsable dates:
ArgumentError: invalid date
    minitest_must_raise.rb:8:in `parse'
    minitest_must_raise.rb:8:in `initialize'
    minitest_must_raise.rb:27:in `new'
    minitest_must_raise.rb:27:in `block (2 levels) in <main>'

  2) Error:
AnyDate#test_0003_3 - value wrapper only: won't accept dates prior to root date:
ArgumentError: cannot calculate dates before 2015-06-25
    minitest_must_raise.rb:9:in `initialize'
    minitest_must_raise.rb:23:in `new'
    minitest_must_raise.rb:23:in `block (2 levels) in <main>'

6 runs, 4 assertions, 0 failures, 2 errors, 0 skips
```

As expected, spec 1 and 2 are old school and trigger the deprecations. Spec 3 and 4 error and only the specs 5 and 6 (wrapped in both  `_(…)` and a Proc) work, so this seems to be the new syntax there:

```ruby
_(-> { AnyDate.new(0) }).must_raise ArgumentError
```

It hurts my eyes to be honest, but if that's the way to do it now, then so be it.

However, how about adding an example to the README for a smoother transition?

**Comment by blowmage** [comment]
I pass the block to `_` instead of passing a proc as an argument:

```ruby
_ { AnyDate.new(0) }.must_raise ArgumentError
```

Actually, for errors I use the `expect` alias because to me it reads better:

```ruby
expect { AnyDate.new(0) }.must_raise ArgumentError
```

**Comment by zenspider** [comment]
Thank you for pointing this out. The doco was indeed improverished for this method. I've improved it and credited you in the commit. 

See (and please critique) here: http://docs.seattlerb.org/minitest/Minitest/Spec/DSL/InstanceMethods.html

**Comment by svoop** [comment]
@zenspider Perfect, thanks a bunch for the doc. 
@blowmage Indeed, dropping the brackets for `_ { … }.must_raise` is ways better to look at. Thanks for the hint, I should have come up with this myself. :smile:

**Comment by joshtune** [comment]
@blowmage - that works for me thanks

**Comment by zenspider** [comment]
@svoop unless I'm misunderstanding: you _cannot_ drop the brackets. `must_raise` absolutely requires a block to work at all.

**Comment by joshtune** [comment]
@zenspider - I am currently working on writing tests using must_raise, and yes I couldn't get `_ (...).must_raise` to work, you have to use something like `_ {...}.must_raise` and example would be something like

Test File: book_test.rb
```
_ { Book.new(2) }.must_raise MyClass::CustomError
```

where `Book` would be defined something like

Class File: book.rb
```
class Book

  class CustomError < StandardError;

  def initialize(title)
    raise CustomError unless title.kind_of?(String)
  end

end
```

Hope that helps

**Comment by svoop** [comment]
@zenspider 

> unless I'm misunderstanding: you cannot drop the brackets. must_raise absolutely requires a block to work at all

The block is required, yes, but as @blowmage suggested, I drop the round brackets which works like a charm:

```
_(expr).must_be :valid?
_{ block }.must_raise Error
```
