### ISSUE TITLE
Scope of describe blocks

### ISSUE THREAD

**Issue by mig-hub** [seattlerb/minitest#810]
Hello, I encountered an issue and wanted to seek guidance. Basically I often run separated tests for quite a while, and then at some point I start to run all tests in one with the Rake task. I don't really like the Rake task because I would like to keep separation of scope and run each test separately. But the global report is convenient and more importantly, it probably should not break when they are all mixed.

My issue is regarding constants that have similar names across test cases. Here is a dummy example:

```ruby
require 'minitest/autorun'

# Classes to be tested
One = Struct.new :x
Two = Struct.new :x

describe One do
  Fake = 1
  def test_this
    assert_equal 1, Fake
  end
end

describe Two do
  Fake = 2
  def test_this
    assert_equal 2, Fake
  end
end
```

I understand this is probably not idiomatic minitest since it mixes test syntax and spec syntax. I actually prefer assertions, but I like the convenience of the nested `describe` blocks and the use of `it`.

What happens is that the constants `Fake` seem to be declared on the global scope where I was under the impression that using the `describe` block is pretty much like declaring a `Minitest::Test` subclass. But if I put my tests in subclasses of `Minitest::Test` instead, it works fine. 

I am sure this is on global scope because I get the Ruby warning that the constant is being redefined.

Is this something that should/can be fixed ? Or am I supposed to do things differently when using the spec syntax?

These constants are generally fake objects and they can be different from one file to another because they only have the desired interface for the current test case. 

Thank you in advance,
mig

**Comment by mig-hub** [comment]
I think what happens is what @zenspider refers to on the talk about creating a test framework from scratch when he says why he prefers defining a method instead of using a method called `test` with a yielded block. But I was under the impression the scope was closed when using `define_method` or when calling the block instead of yielding. But `describe` uses `class_eval`, so it is probably that.

The thing is that I use the explanation in the [design rationale](https://github.com/seattlerb/minitest/blob/master/design_rationale.rb) as a mental representation but there are always tricky details hidden in abstractions.

**Comment by blowmage** [comment]
For the most part, the Minitest spec DSL is analogous to creating classes and methods. So the same rules for scope applies. When using named classes the constants created will be scoped to the class, and you can use constants like you are. However, when using anonymous classes, the constant is scoped to the global scope.

You can accomplish the same behavior as the spec DSL without using the spec DSL by doing the following:

```ruby
require 'minitest/autorun'

# Classes to be tested
One = Struct.new :x
Two = Struct.new :x

Class.new Minitest::Test do
  Fake = 1
  def test_this
    assert_equal 1, Fake
  end
end

Class.new Minitest::Test do
  Fake = 2
  def test_this
    assert_equal 2, Fake
  end
end
```

**Comment by mig-hub** [comment]
@blowmage thank you so much for the explanation. I have read the code many times and for some reason missed this. I thought it was creating a class with a name prepending "Test" to the described class.

I am not sure if I should ditch the spec syntax or find a work around. For the moment I've made sure the constant names are unique but it gets ugly in places. Obviously I have use a simple variable for my example, but in reality they are classes, overwise I would have a method, not a constant.
