### ISSUE TITLE
Circle CI is not working after the 1.0 version is now deprecated.

### ISSUE THREAD

**Issue by GermanDZ** [seattlerb/minitest#812]
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/570991/67429660-ea116a00-f5e0-11e9-8d95-cf5234a8933b.png">

**Comment by zenspider** [comment]
Meh. I never depended on circleci and the move to 2.0 requires me to put turd files in all my projects? no thank you. I should figure out how to delete them, but I was hoping they'd do that automatically after not using it long enough.
