### ISSUE TITLE
Use assert_nil if expecting nil from -- No way to solve for dynamic asserts

### ISSUE THREAD

**Issue by fzakaria** [seattlerb/minitest#829]
We have some tests that do something similar to:

```
it 'some test'
    actual = run_task()
    expected = {
        :a  => "a,
        :b => nil,
        :c => "c"',
        :d => nil,
        :e => "e",
        :f => "f",
        :g => "g",
    }
    expected.each{|k, v| expect(actual[k]).must_equal v, k}
end
```
It's a simply way to make a single line assertion handle a Hash of potential values.
Unfortunately, Minitest is warning with:

```DEPRECATED: Use assert_nil if expecting nil from $FILE. This will fail in Minitest 6.```

Can this be removed -- I don't see why the forcing of `assert_nil` is required here. 
I understand the deprecation notice for the expectation monad.

Furthermore, can the **warn** be toggled off via environment variable?

**Comment by fzakaria** [comment]
I ended up using this approach in my code for now:

```ruby
module MiniTest::Assertions
  alias_method :assert_equal_old, :assert_equal

  # We redefine assert_equal here to squelch the DEPRECATED warnings for using assert_nil
  # https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L227
  # @see https://github.com/seattlerb/minitest/issues/829
  def assert_equal(exp, act, msg = nil)
    if exp.nil?
      assert_nil act, msg
    else
      assert_equal_old exp, act, msg
    end
  end

end
```

**Comment by zenspider** [comment]
When your "no way to solve" is literally solved with an `if`... 

Closing. I don't have time or patience for hyperbole.
