### ISSUE TITLE
How to use Minitest for general purpose test

### ISSUE THREAD

**Issue by rodrigosiqueira** [seattlerb/minitest#835]
I have a set of tests written in C/shell that validate some OS features in an embedded device; now I'm re-implement these tests as a ruby gem. However, I don't want to implement assertions and other related things from scratch, I want to use minitest for this purpose which means that I added it as my dependency (`spec.add_dependency 'minitest', '~> 5.14'`).

My gem is organized like this:
```sh
bin  Gemfile  Gemfile.lock lib  Rakefile  README.md  system_test.gemspec 
./bin:
console  setup  system_test
./lib:
system_test  system_test
./lib/system_test:
cli.rb  basic_display_test.rb  version.rb
...
```
Inside the `cli.rb` class I tried to instantiate the `basic_display_test`, as follows:
```ruby
require 'optparse'
require 'ostruct'
require 'system_test/basic_display_test'

module SytemTest
  class Cli
    def run(argv = ARGV)
      parser_options(argv)
      execute_actions
    end

    def parser_options(args = ARGV)
    ... excute_actions ...
    end

    def execute_actions
      ...
      display = BasicDisplayTest.new
      display.run_test
      ...
    end
...
```
`basic_display_test.rb` looks like this:
```ruby
require 'minitest/autorun'                                                                                                                                                                          

class TestSquareRoot < Minitest::Test
  def test_make_it_work_first
    assert_equal 3, 3
  end                                                                               
end
```
However, I try `ruby -Ilib ./bin/system_test --all` constantly got the following error:
```
...
/home/PATH/gems/minitest-5.14.0/lib/minitest.rb:405:in `initialize': wrong number of arguments (given 0, expected 1) (ArgumentError)
```
What should be the correct way for my gem to start the required test? Which parameter `Minitest :: Test` expects? Additionally, I don't want to run tests in parallel how can I make the test sequential?

**Comment by zenspider** [comment]
1. Why are you reimplementing the runner? There's probably an easier way to fold what you want on top of minitest.

2. Without a proper set of source and stack trace, I can only guess that this:

```
      display = BasicDisplayTest.new
      display.run_test
```

should probably be:

```
      display = BasicDisplayTest.new :test_make_it_work_first
      display.run_test
```

**Comment by zenspider** [comment]
No response. Closing.
