### ISSUE TITLE
Minitest Spec depreciation

### ISSUE THREAD

**Issue by pitosalas** [seattlerb/minitest#836]
Is it correct that as of minitest 6, it will be required to write minitest specs like this: `_(@my_age).must_equal 25`

I ask for 2 reasons:

1) I want to make sure I am right. Because the warning says "global use of must_equal". What is global use? Maybe theres a way to turn it off.
2) I think it's really ugly and want to go back to `@my_age.must_equal 25.

I vaguely remember that there was a long argument why @my_age.must_eqaul 25 had to go. But was that an argument that traded convenience for "purity"? I mean life seemed to be fine before. Can I go back? Is there a secret setting?

**Comment by zenspider** [comment]
1. Yes it is true.
2. You can use `expect` or `value` instead if you object to `_`.
3. No, there's no going back. Monkeypatching Object is just bad.

**Comment by pitosalas** [comment]
Thanks, I  respect your work here and I'm sure this decision was not come to lightly.

**Comment by zenspider** [comment]
and If you really dislike it, use assertions.
