### ISSUE TITLE
Tests run multiple times when using describe

### ISSUE THREAD

**Issue by Linuus** [seattlerb/minitest#839]
When using `describe` the test cases defined outside of the describe blocks will run once for each describe block. I guess it's because the describe inherits from the surrounding class, which has the other test defined in it.

Is that intentional?

```ruby
class Foo < ActiveSupport::TestCase
  describe("something") do
    test("foo") do
      "my test"
    end
  end

  describe("something else") do
    test("bar") do
      "something"
    end
  end

  test("baz") do
    "I will run 3 times"
  end
end
```

If yes, is it documented somewhere (it's a bit surprising when using the describe syntax)? :)

What's the recommended approach to write tests like this? Just make sure to wrap all tests in describe or no tests - no mixing?

**Comment by blowmage** [comment]
> Is that intentional?

Yes.

> is it documented somewhere

This behavior is how the RSpec DSL works. Minitest's Spec DSL is intended to be mostly compatible with it. This is one of the few places where Ruby's classes/methods are not perfectly analogous to the Spec DSL's `it`/`describe` blocks.

> What's the recommended approach to write tests like this?

I don't think there is a recommended way of doing anything. You can do as you like.

**Comment by Linuus** [comment]
Ok thanks! Then I know it's not a bug at least :)
