### ISSUE TITLE
`i_suck_and_my_tests_are_order_dependent` documentation should be more informative, less derogatory

### ISSUE THREAD

**Issue by crispinheneise** [seattlerb/minitest#840]
I understand the reasoning behind the documentation for `i_suck_and_my_tests_are_order_dependent`. However I feel that this method name and its comment are glib and do not provide adequate rationale for why tests should be order independent. Nor does it allow for the possibility that there are a very limited number of legitimate reasons to want tests to be run sequentially, particularly when dealing with third-party services. 

https://github.com/seattlerb/minitest/blob/e6bc4485730403faff6966c1671cf5de72b2d233/lib/minitest/test.rb#L26-L31

I recommend renaming the method and changing the wording of the explanation. Something like: 

```rb
## 
# Place this at the top of your tests when you absolutely 
# positively need to have ordered tests. Understand that 
# doing so may obfuscate certain weaknesses in your code 
# by requiring logic to be executed in a certain order. 

def self.execute_tests_in_order_even_though_not_recommended!
  # ...
end
```

**Comment by splattael** [comment]
We've seen a number of [similar issues](https://github.com/seattlerb/minitest/issues?q=is%3Aissue+i_suck_and_my_tests_are_order_dependent+is%3Aclosed) already with a number of workarounds.

One workaronud (from https://github.com/seattlerb/minitest/issues/739#issuecomment-360091954) is to redefine `test_order` like this:

```ruby
def self.test_order
  :alpha
end
```

I hope this helps :+1:

**Comment by crispinheneise** [comment]
I've seen that also, and it's a fine workaround. But my point for submitting this issue is that I think the documentation could be made more helpful. The current docs for this method feel snarky, and I think the rationale for why tests should be order independent could be expanded upon to help other developers understand why it's important to develop better tests. Just saying "your tests are weak" is kind of ... well, dismissive.

**Comment by crispinheneise** [comment]
Those other issues, lol!

**Comment by crispinheneise** [comment]
@splattael I see you submitted this as a PR #400. It makes me sad that was rejected. IMO this method name is almost as bad as that stupid comment in #398. ¯\_(ツ)_/¯

**Comment by crispinheneise** [comment]
Apparently even the Rails core team thinks this method is offensive enough to warrant renaming. https://github.com/rails/rails/commit/e81f3c210eca074ed6227bd1c40835d44761c09e
