### ISSUE TITLE
Public cert not available

### ISSUE THREAD

**Issue by svoop** [seattlerb/minitest#842]
Trying to install minitest with MediumSecurity:

```
The gem minitest-5.14.0 can't be installed because the security policy didn't
allow it, with the message: root cert /CN=ryand-ruby/DC=zenspider/DC=com is not
trusted
```

There's an old locked issue #469 with a download link that returns "forbidden".

I've recently signed my gems according to the [Rubygems Security guide](https://guides.rubygems.org/security/). Since most gem sources are on GitHub these days, there's a predefined location in the repo for the public key now. Assuming you've created the public key as mentioned in the security guide at `~/.ssh/gem-public_cert.pem`, here's what to do:

```
cd /path/to/your/gem
mkdir certs
cp ~/.ssh/gem-public_cert.pem certs/seattlerb.pem
git add certs/seattlerb.pem
git commit -m "Add public cert"
git push
```

Or remove signatures altogether. 🤕

**Comment by zenspider** [comment]
I was watching your requests come through the error log as I was fixing up userdir configuration and permissions. This should be fine now. Please confirm.

**Comment by svoop** [comment]
@zenspider Worked, thank you! (However, I hope one day we find a better solution as to where to publish/find the certificates.)
