### ISSUE TITLE
Multiple test output from `m` execution of tests

### ISSUE THREAD

**Issue by schneems** [seattlerb/minitest#844]
When I try to run a focus test that uses `fork`:

```
cd /tmp
git clone https://github.com/zombocom/rate_throttle_client
cd rate_throttle_client/
git checkout b7aa2f1c1cb4a4cb2238bc4afeb6d9ccfc453641
bundle
m test/demo_test.rb:14
```

It produces this output:

```
$ m test/demo_test.rb:14
Run options: -n "/^(test_time_scale)$/" --seed 4244

# Running:

Run options: --seed 60997

# Running:

............

Finished in 15.785675s, 0.7602 runs/s, 1.1403 assertions/s.

12 runs, 18 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 21472

# Running:

............

Finished in 15.904356s, 0.7545 runs/s, 1.1318 assertions/s.

12 runs, 18 assertions, 0 failures, 0 errors, 0 skips
.

Finished in 37.193820s, 0.0269 runs/s, 0.0269 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

It seems to run the whole suite first and then the focused test. I'm able to workaround this issue by switching to explicitly running minitest (This is me re-introducing the bug https://github.com/zombocom/rate_throttle_client/commit/b7aa2f1c1cb4a4cb2238bc4afeb6d9ccfc453641). 

This is related to the conversation on https://github.com/seattlerb/minitest/pull/683#issuecomment-611493066

**Comment by dylanahsmith** [comment]
`m` isn't a minitest executable.  I would suggest simplifying how to reproduce the bug so that it is clear that it is actually a minitest issue and to reduce how much context the maintainers of this library need to actually understand what is going on.  For example, see how the description of #683 includes a minimal self-contained script that reproduces the issue.

**Comment by zenspider** [comment]
@schneems try running w/o `m`... 

```
ruby -Ilib test/demo_test.rb
```

If that works, then this is a problem in `m`. If not, then we should also ensure that you don't have `RUBYLIB` or something similar infecting things.

**Comment by schneems** [comment]
Thanks, looks like it's a bug in the `m` gem:

```
$ be ruby -Ilib:test test/demo_test.rb -n test_starting_limit
Run options: -n test_starting_limit --seed 16929

# Running:

.

Finished in 1.459583s, 0.6851 runs/s, 0.6851 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```
