### ISSUE TITLE
Domain https://docs.seattlerb.org/minitest/ has SSL certs for fastly only.

### ISSUE THREAD

**Issue by berkes** [seattlerb/minitest#848]
Hello,

The domain https://docs.seattlerb.org/minitest/ is presenting an invalid SSL cert. 

https://www.ssllabs.com/ssltest/analyze.html?d=docs.seattlerb.org ( Certificate name mismatch )

You might either want to disable https (and port 443) entirely, or get a (free) certificate on fast.ly. I don't know fasly, though, so cannot help there.

**Comment by zenspider** [comment]
Paging @drbrain...

**Comment by drbrain** [comment]
@zenspider can you either:

make `docs.seattlerb.org` a CNAME for `j.sni.global.fastly.net`

or:

add four `A` records for `docs.seattlerb.org` pointing to `151.101.2.132`, `151.101.66.132`, `151.101.130.132`, and `151.101.194.132`

**Comment by zenspider** [comment]
dropped the ball here but just got another nudge on it.

I just did the former. Should resolve within the hour.

**Comment by zenspider** [comment]
This appears fixed. Thank you both!
