### ISSUE TITLE
Can't access method from inherited controller in test environment

### ISSUE THREAD

**Issue by Magesh-B** [seattlerb/minitest#850]
I am trying to write a test to check a user flow in my application. For that, I need to test a method called ```is_apple``` that is in  ```AppleController```, AppleController is inherited from ```FruitsController```. I have a method in FruitsController called ```taste``` which can be used inside ```AppleController's is_apple``` method. The output is the same as expected in the Development and Production environment. But In the Test environment, The method from the FruitsController is undefined in AppleController. I am new to rails testing, I don't know what is potentially causing this issue in my application's test environment.

test_helper.rb

    ENV['RAILS_ENV'] ||= 'test'
    require File.expand_path('../../config/environment', __FILE__)
    require 'rails/test_help'
    
    class ActiveSupport::TestCase
      def setup
        puts "starting a test"
        post "v1/is_apple", params: {colour: 'red', taste: 'sweet'} 
      end
    end

apple_controller.rb

    module V1
      class AppleController < FruitsController
        def is_apple
          return true if taste and params[:colour].eql?('red')
        end
      end
    end

fruits_controller.rb

    module V1
      class FruitsController < ActionController::API
        def taste
          # assume
          return true
        end
      end
    end

I am using minitest '5.10.3' and rails 6. When I run rails test, am getting undefined_method 'taste' in AppleController. Is there any mistakes in my code? , If yes, How can I achieve the behaviour I wanted. Thanks in advance!

**Comment by zenspider** [comment]
How is minitest involved in this at all? This sounds like a rails code loading issue or something else... but it is way outside of minitest either way.

Try something like `RAILS_ENV=test rails console` and then try to reproduce from there (you should have http verb methods just like in controller/integration tests).

**Comment by zenspider** [comment]
No response. Closing.
