### ISSUE TITLE
How to hide DEPRECATED warnings

### ISSUE THREAD

**Issue by inspire22** [seattlerb/minitest#851]
My latest bundle update has destroyed my rails test since there's 10,000 of these lines printed as every test runs.  How to hide it?  It looks like you used to be able to add t.warning = false to the Rake::Task.tasks.each loop in Rakefile, but that doesn't work anymore.

Also: _ is the ugliest method name ever seen.  Aliases are better but not great.  Imo, the internal ugliness of monkey-patching on object is so much less ugly than the external ugliness of wrapping every object you ever use with a method call.

**Comment by zenspider** [comment]
Don't file 2 issues in 1.

**Comment by abdullaachilov** [comment]
@inspire22  user `assert_match` then, instead of `_(obj).must`
