### ISSUE TITLE
Minitest files installed via RubyGems are read-only

### ISSUE THREAD

**Issue by johlym** [seattlerb/minitest#852]
It appears that when one installs `minitest` from RubyGems, the files themselves are written as read-only (0444).

Here's how I was able to reproduce:

1. `rvm use 2.7.1` (I'm using 2.7.1, haven't tried it with other versions, mainly because this is the only gem I've run into with this issue)
2. `gem install minitest` (and a bunch of others)
3. in `/Users/johnathan.lyman/.rvm/gems/ruby-2.7.1`, run `find . -type f -perm 444`
4. Get the output of all read-only files within (only `minitest`, in this case)

Here's all the info I've been able to collect so far:

```
ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

**Installed via RubyGems (`gem install minitest`):**

```
➜  minitest-5.14.1 ls -al
total 176
drwxr-xr-x   10 johnathan.lyman  staff    320 Aug 24 10:37 .
drwxr-xr-x  193 johnathan.lyman  staff   6176 Aug 24 10:37 ..
-r--r--r--    1 johnathan.lyman  staff   1107 Aug 24 10:37 .autotest
-r--r--r--    1 johnathan.lyman  staff  43879 Aug 24 10:37 History.rdoc
-r--r--r--    1 johnathan.lyman  staff    661 Aug 24 10:37 Manifest.txt
-r--r--r--    1 johnathan.lyman  staff  28600 Aug 24 10:37 README.rdoc
-r--r--r--    1 johnathan.lyman  staff   2148 Aug 24 10:37 Rakefile
-r--r--r--    1 johnathan.lyman  staff   1918 Aug 24 10:37 design_rationale.rb
drwxr-xr-x    5 johnathan.lyman  staff    160 Aug 24 10:37 lib
drwxr-xr-x    3 johnathan.lyman  staff     96 Aug 24 10:37 test
```

installed via GitHub source:

1. `git glone https://github.com/seattlerb/minitest.git`
2. `rake gem`
3. `gem install pkg/minitest-5.14.1.gem`

```
➜  minitest-5.14.1 ls -al
total 176
drwxr-xr-x   10 johnathan.lyman  staff    320 Aug 24 10:42 .
drwxr-xr-x  194 johnathan.lyman  staff   6208 Aug 24 10:42 ..
-rw-r--r--    1 johnathan.lyman  staff   1107 Aug 24 10:42 .autotest
-rw-r--r--    1 johnathan.lyman  staff  43879 Aug 24 10:42 History.rdoc
-rw-r--r--    1 johnathan.lyman  staff    661 Aug 24 10:42 Manifest.txt
-rw-r--r--    1 johnathan.lyman  staff  28600 Aug 24 10:42 README.rdoc
-rw-r--r--    1 johnathan.lyman  staff   2148 Aug 24 10:42 Rakefile
-rw-r--r--    1 johnathan.lyman  staff   1918 Aug 24 10:42 design_rationale.rb
drwxr-xr-x    5 johnathan.lyman  staff    160 Aug 24 10:42 lib
drwxr-xr-x    3 johnathan.lyman  staff     96 Aug 24 10:42 test
```

This is also reproducible with `5.14.0`, too. I've also seen this reproducible on Linux, as well.

The read-only nature of these files caused an edge-case bug to surface via https://github.com/heroku/heroku-buildpack-ruby/issues/1049, as well. The buildpack doesn't expect gems' files to be read-only so it falls over when faced with an interactive prompt from the shell to delete.

**Comment by zenspider** [comment]
This is intentional.

**Comment by johlym** [comment]
Out of curiosity, why?

**Comment by zenspider** [comment]
Because that's the state they're in when I package gems.
