### ISSUE TITLE
Couldn't install minitest with ruby/ruby master

### ISSUE THREAD

**Issue by hsbt** [seattlerb/minitest#853]
Hi,  @matz decide to bump the version to 3.0 from 2.8 in ruby/ruby repository.

https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11

After that, I couldn't install minitest with Ruby 3.0.0 because https://github.com/seattlerb/minitest/blob/master/Rakefile#L14

Can you relax the its require version? Thanks.

**Comment by zenspider** [comment]
Fixed! Thank you!

**Comment by hsbt** [comment]
Thanks to your quick fix!
