### ISSUE TITLE
undefined method `context` when using minitest/spec

### ISSUE THREAD

**Issue by mullermp** [seattlerb/minitest#859]
I'm unable to use a context block with spec integration. AFAIK context is an alias of describe in RSpec.

I tested locally and confirmed that adding `alias_method :context, :describe` from within `class Minitest::Spec` will work.

**Comment by zenspider** [comment]
Correct. Minitest != RSpec.

**Comment by mullermp** [comment]
Hey, I'm aware that Minitest is not Rspec. I'm talking specifically about the [Minitest/spec](https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb) functionality, which appears to provide a compatibility layer between the two. Describe blocks work as expected, but not contexts, but they work the same way.
