### ISSUE TITLE
assert_no_changes throws assert_nil deprecation warning when the observed value is nil

### ISSUE THREAD

**Issue by jacek213** [seattlerb/minitest#860]
The code

     assert_no_changes -> { calc_model.reload.savings } do
       service.call
     end

The problem:

`calc_model.savings` is `nil` and I need it to stay that way. Please notice, that I'm not asserting nils explicitly in any manner.

It yields:

`DEPRECATED: Use assert_nil if expecting nil from...`

**Comment by adam12** [comment]
This is actually in Rails and not Minitest. Here's the [PR](https://github.com/rails/rails/pull/31069); it was fixed in Rails 5.2.

**Comment by jacek213** [comment]
@adam12 thank you, I've upgraded Rails to 5.2 and now it's all good. Closing.
