### ISSUE TITLE
GitHub Actions for CI?

### ISSUE THREAD

**Issue by MSP-Greg** [seattlerb/minitest#863]
Any interest?  Ubuntu 16.04, 18.04 & 20.04, macOS 10.15 & 11.0, Windows 2016 & 2019, MRI 2.2 thru head, JRuby. TruffleRuby.

Twenty Ubuntu & Windows jobs run concurrently, five for macOS.

Note sure what to run, `rake test` & `rake test:isolated`?

Locally, checking with Ruby master, Ubuntu is fine, Windows may need two skips, only looked at one (srand problem), failures below:
```
  1) Failure:
TestMinitestUnitTestCase#test_runnable_methods_random [C:/Greg/GitHub/minitest/test/minitest/test_minitest_test.rb:863]:
--- expected
+++ actual
@@ -1 +1 @@
-["test_test2", "test_test1", "test_test3"]
+["test_test2", "test_test3", "test_test1"]


  2) Failure:
TestMinitestAssertions#test_skip_until [C:/Greg/GitHub/minitest/test/minitest/test_minitest_assertions.rb:1359]:
In stderr.
Expected /Stale skip_until \"not yet\" at .*?:\d+$/ to match "Stale skip_until \"not yet\" at C:/Greg/GitHub/minitest/test/minitest/test_minitest_assertions.rb\n".
```

**Comment by zenspider** [comment]
Sorry... yes, I'd be down.

`rake test` for regular matrix work. A separate single run of `isolated` should suffice.
