### ISSUE TITLE
A way to opt into Minitest 6 `assert_equal nil, x` behavior today?

### ISSUE THREAD

**Issue by mkilling** [seattlerb/minitest#868]
Hi, I welcome the upcoming change that will make `assert_equal nil, x` fail in minitest 6. I encountered a situation today where this behavior would have caught a potential bug. However, our test suite was only fully run in CI and nobody noticed the deprecation warning.

I was wondering whether it could be made possible to opt into the new assert_equal behavior today. From looking at minitest’s source, it seems the only way is to change the minitest version to 6 though.

**Comment by blowmage** [comment]
Have you tried monkey patching the existing method to use the new behavior? You could add something like this in your test helper file:

```ruby
module Minitest
  module Assertions
    def assert_equal exp, act, msg = nil
      msg = message(msg, E) { diff exp, act }
      result = assert exp == act, msg

      refute_nil exp, "Use assert_nil if expecting nil."

      result
    end
  end
end
```

**Comment by zenspider** [comment]
Or, mess around with the version for fun:
```ruby
Minitest::VERSION.replace "6.haha"
```

Probably the cleanest is to add this to your test helper or wherever makes sense to you:

```ruby
class Minitest::Test
  def assert_equal exp, act, msg = nil
    refute_nil exp
    super
  end
end
```

**Comment by zenspider** [comment]
No response. Closing
