### ISSUE TITLE
Tests run multiple times when using describe

### ISSUE THREAD

**Issue by jensljungblad** [seattlerb/minitest#874]
I'd like to report the same issue as here: https://github.com/seattlerb/minitest/issues/839.

> @blowmage This behavior is how the RSpec DSL works. Minitest's Spec DSL is intended to be mostly compatible with it. This is one of the few places where Ruby's classes/methods are not perfectly analogous to the Spec DSL's it/describe blocks.

This doesn't seem to be true though. It's not how rspec works, which is documented here with an example: https://rspec.info/documentation/3.10/rspec-core/#a-word-on-scope

To use a similar example to the previous issue:

```ruby
# With RSpec
RSpec.describe("Foobar") do
  describe("some context") do
    it("does something") do
      puts("does something")
    end
  end

  it("does something else") do
    puts("will only run once")
  end
end

# With Minitest::Spec
class Foo < ActiveSupport::TestCase
  describe("some context") do
    test("it does something") do
      puts("does something")
    end
  end

  test("does something else") do
    puts("will run two times")
  end
end
```

So I would say it's pretty unexpected behavior, if the intention is to mostly be compatible with rspec?

**Comment by amckinnie** [comment]
I opened a PR to deal with the issue here: https://github.com/seattlerb/minitest/pull/865

I ended up just monkey patching it into the app that was using it, though that's not really a good long term solution for dealing with issues like this.

**Comment by zenspider** [comment]
@jensljungblad  except the examples you provide aren't analogous, are they? Seems apples-to-oranges if you're showing a mixture of classes and describes on the minitest side vs only describes on the rspec side.

**Comment by jensljungblad** [comment]
> @jensljungblad except the examples you provide aren't analogous, are they? Seems apples-to-oranges if you're showing a mixture of classes and describes on the minitest side vs only describes on the rspec side.

You're right, I didn't realize you could use top-level describe in Minitest::Spec. And it actually seems like you are supposed to, because doing that revealed that you shouldn't use `test`, but rather must use `it`. For some reason I thought that was optional, and you could mix the styles, i.e. use a class, write `test`, but still leverage `describe` and `let`.

My bad!
