### ISSUE TITLE
Ability to assert "thrown object" (second `throw` argument)

### ISSUE THREAD

**Issue by volmer** [seattlerb/minitest#875]
Hello!

The `throw` method accepts a second, optional argument, which is the value that the matching `catch` block returns in case the symbol is caught: https://ruby-doc.org/core-3.0.1/Kernel.html#method-i-throw

Currently it is not possible to use `assert_throw` to test code that is supposed to throw a certain symbol as well as a specific return value for `catch`. I would like to suggest adapting Minitest to offer an easy way to write an assertion for this.

My suggestion would be to let `assert_throw` have a similar behaviour as `assert_raises`: it could return the value returned by its internal `catch` block, allowing test writers to write assertions around that object. This, of course, would come to the expense of `assert_throw` no longer returning `true` when the assertion passes. Not sure how important this is for API compliance. 

Thoughts?

**Comment by zenspider** [comment]
20 years... and I'm still learning stuff about ruby...

**Comment by zenspider** [comment]
Done! Thanks!

**Comment by volmer** [comment]
Amazing, thank you!!
