### ISSUE TITLE
I wish the assert_equal failure messages were aligned

### ISSUE THREAD

**Issue by kevin-smartpatients** [seattlerb/minitest#876]
Spot the difference!

```
Minitest::Assertion: <You have 1 private messsage waiting for you.> expected but was
<You have 1 private message waiting for you.>
```

I wish the expected and actual were aligned to make it easier to spot the differences.

*Funny that now I pasted this into GitHub my browser is flagging the misspelling of messages!*

**Comment by zenspider** [comment]
```ruby
    a = "You have 1 private messsage waiting for you."
    b = "You have 1 private message waiting for you."

    assert_equal a, b
```
outputs:
```
  1) Failure:
assert_equal#test_0001_quicky [eq.rb:8]:
--- expected
+++ actual
@@ -1 +1 @@
-"You have 1 private messsage waiting for you."
+"You have 1 private message waiting for you."
```

**Comment by kevin-smartpatients** [comment]
> @@ -1 +1 @@
> -"You have 1 private messsage waiting for you."
> +"You have 1 private message waiting for you."
> ```

Interesting. I wonder if it's RubyMine's formatting.

**Comment by zenspider** [comment]
Probably not? It'd be strange to "unformat" something. Take a look at this:

https://github.com/seattlerb/minitest/blob/master/lib/minitest/assertions.rb#L29-L120

**Comment by kevin-smartpatients** [comment]
It is, in fact, the RubyMine reporter that is messing it up.

```
msg = exception.nil? ? '' : "#{exception.class.name}: #{exception.message}"
```

in `Minitest::RubyMineReporter#with_message_and_backtrace` line 263.

Sorry for reporting it without investigating first!

**Comment by kevin-smartpatients** [comment]
Thanks for minitest BTW. I love it.
