### ISSUE TITLE
Tests are labeled as "rails test"

### ISSUE THREAD

**Issue by Hal9000** [seattlerb/minitest#883]
Not a "huge" deal perhaps, but annoys me.

Can't see a way around it. I once patched my local gem to stop it, 
but it quit working for some reason.

**Comment by zenspider** [comment]
This is from rails, not minitest.

**Comment by Hal9000** [comment]
How does that work? I’m not running Rails
or invoking it in any way.

Do I have to uninstall Rails?

**Comment by zenspider** [comment]
It works because rails is rude and takes advantage of the minitest plugin system without doing any sanity checks against your current project. Uninstalling is one way to fix this.

Try this: `GEM_HOME=/tmp/blah GEM_PATH= rake test` (or however you run your stuff).

**Comment by Hal9000** [comment]
Rails is rude indeed.

Thanks for the explanation.

**Comment by zenspider** [comment]
Use gemsets (eg use ohmygems or just `export GEM_PATH=xxx`) to put rails into projects rather than globally... Closing.
