### ISSUE TITLE
Unsightly method names in Minitest::Reporters::SpecReporter output

### ISSUE THREAD

**Issue by MatzFan** [seattlerb/minitest#884]
I use the `minitest-reporters` gem to emulate RSpec's spec'ing output, but with your small & perfectly formed test framework.

The otherwise beautiful output is marred only by the test name prefixes defined [here](https://github.com/seattlerb/minitest/blob/f4f57afaeb3a11bd0b86ab0757704cb78db96cf4/lib/minitest/spec.rb#L222). An example:

```ruby
describe Meme do
  before do
    @meme = Meme.new
  end

  describe "when asked about cheeseburgers" do
    it "must respond positively" do
      _(@meme.i_can_has_cheezburger?).must_equal "OHAI!"
    end
  end
end
```

With `Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new` results in the following output:

```
Meme::when asked about cheeseburgers
  test_0001_must respond positively                               PASS (0.00s)
```

Is the `test_0001_` part absolutely necessary?

The issue seems to have been discussed [some time back](https://github.com/seattlerb/minitest/pull/131).

Thanks in advance for your indulgence.

**Comment by blowmage** [comment]
IMO this issue should be opened on [minitest-reporters](https://github.com/minitest-reporters/minitest-reporters).

I would try updating getting `Minitest::Reporters::SpecReporter` to remove the method name prefix when reporting the test results. Perhaps by using the regexp `/^test\_\d{4,}\_/` to replace the prefix?

**Comment by MatzFan** [comment]
I will do that, thanks. Rather than any solution relying on the current internals of the `it` method, might it be possible to expose the method name prefix in the public API? Would you accept a PR to move the prefix string definition to a `Minitest::Spec::DSL#method_name_prefix` for example? If not I'll close this issue.

**Comment by zenspider** [comment]
Strictly necessary? no... but people who do BDD have proven wierd from time to time. This is one of those times... They have often wanted to have tests run, not just in sorted order, but in order of definition. This allows for that.

Not gonna fix (would only cause more problems down the road)
