### ISSUE TITLE
Ruby 3.1 error_highlight requires to update tests to handle message as Regexp

### ISSUE THREAD

**Issue by yahonda** [seattlerb/minitest#894]
Ruby 3.1 error_highlight requires updating tests to handle messages as Regexp

### Steps to reproduce

- ruby31_error_highlight_minitest.rb
```ruby
require 'minitest/autorun'

Foo = Struct.new(:foo, :bar)

class SomeTest < Minitest::Test
  def setup
    @obj = Foo.new('FOO', 'BAR')
  end

  def test_something
    e = assert_raises NameError do
      @obj[:baz]
    end
    assert_equal "no member 'baz' in struct", e.message
  end
end
```

### Expected behavior
This test should pass.

### Actual behavior
It fails because the `e.message` is Regexp.

```
% ruby ruby31_error_highlight_minitest.rb
Run options: --seed 12010

# Running:

F

Failure:
SomeTest#test_something [ruby31_error_highlight_minitest.rb:14]:
--- expected
+++ actual
@@ -1 +1,7 @@
-"no member 'baz' in struct"
+# encoding: US-ASCII
+#    valid: true
+"no member 'baz' in struct
+
+      @obj[:baz]
+          ^^^^^^
+Did you mean?  bar"



rails test ruby31_error_highlight_minitest.rb:10



Finished in 0.007305s, 136.8925 runs/s, 273.7851 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
%
```

### Environment
% ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]

**Comment by yahonda** [comment]
Changing `e.message` to `e.original_message` would address this failure. Refer to https://github.com/rspec/rspec-expectations/pull/1339 for the similar change at RSpec.

**Comment by zenspider** [comment]
> Expected behavior
> This test should pass.

As written, on ruby 3.1 with error_highlight enabled, that test should NOT pass, no?

`e` in that test is the `NameError` originally thrown and so `message` is overridden / extended by error_highlight.

I'm confused as to what you want to change. Could you show me what you think should happen?

All my tests pass on 2.7 (and below), 3.0, and 3.1. I think the best I could do is modify the exception coming back from `assert_raises`:

```ruby
      rescue *exp => e
        pass # count assertion
        def e.message; original_message; end if e.respond_to? :original_message
        return e
```

the other possibility is you write your test differently (oddly, disabling `error_highlight` doesn't fix this). These all pass now:

```ruby
    assert_includes e.message, "no member 'baz' in struct"
    assert_equal "no member 'baz' in struct", e.original_message
    assert_equal "no member 'baz' in struct", e.message # now passes with the above
```

**Comment by yahonda** [comment]
Thanks for the info. Yes, using `original_message` addresses my questions.
