### ISSUE TITLE
Anniversary reboot of the "context" alias 🎂

### ISSUE THREAD

**Issue by svoop** [seattlerb/minitest#898]
Honoring the 10th anniversary of #52 (Alias `describe` to `context`), I'd like to give it another shot with two somewhat fresh arguments. @zenspider In case you still disagree, simply shut down this issue and put it to sleep for another ten. 😄 

I find the semantic distinction between `describe` and `context` in MT specs very useful, however, adding the alias in the `spec_helper` (or by requiring some ridiculously small gem) comes with a hefty downside: Since it's not part of core MT, editors won't honor `context` when they build and display e.g. a "structure view" sidebar. There's usually no easy fix for this, if you're lucky, you can fork the underlying editor add-on.

> I don't think it brings much of any value, honestly, so I'm going to suggest this goes into an add-on gem.

The value of "context" is the possibility to express "what you are testing" (describe) and then to set up different stages "how your are testing" (context) within.

Whether you'd use it is a matter of taste, but it does serve a purpose and is not just a shortcut such as `subject` instead of `let :subject` is. (Or other suggestions such as `must` instead of `it "must ..."` would have been.)

**Comment by zenspider** [comment]
No. https://rubygems.org/gems/minitest-spec-context exists. Use it.
