### ISSUE TITLE
How create fixture for nested columns?

### ISSUE THREAD

**Issue by murilomendes** [seattlerb/minitest#905]
Hello everyone. 

I'm new into Minitest so I've some little problems.
My scenario: 

I have a table called "assessments" and it has_many "sections".  In my API, I return: 
 return render json: assessment, include: {  sections } [...]

But I facing some problems in the fixture creation. How can I do?
I tried put an "sections" into assessments.yml but no success, getting the error:
ActiveRecord::Fixture::FixtureError: table "assessments" has no columns named "sections".

Thank you so much. :)

**Comment by zenspider** [comment]
This is a rails question, not a minitest question. Please refile this with rails/rails (or maybe rails/activerecord ?)
